<x-layouts.app :title="__('ui.tokens.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <div><p class="page-kicker">{{ $workspace->name }}</p><h1 class="page-title mt-1">{{ __('ui.tokens.title') }}</h1><p class="page-description">{{ __('ui.tokens.description') }}</p></div>
    @if(session('plain_token'))<div class="mt-7 rounded-3xl border border-amber-200 bg-amber-50 p-5" x-data="clipboard"><p class="font-bold text-amber-950">{{ __('ui.tokens.copy_now') }}</p><p class="mt-1 text-sm text-amber-800">{{ __('ui.tokens.copy_warning') }}</p><div class="mt-4 flex flex-col gap-3 sm:flex-row"><code class="min-w-0 flex-1 break-all rounded-xl border border-amber-200 bg-white p-4 text-sm">{{ session('plain_token') }}</code><button class="btn-primary" type="button" @click="copy(@js(session('plain_token')))" x-text="copied ? @js(__('ui.common.copied')) : @js(__('ui.common.copy'))"></button></div></div>@endif

    <div class="mt-7 grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]">
      <form class="panel h-fit" method="post" action="{{ route('tokens.store') }}">@csrf<h2 class="text-lg font-bold text-slate-950">{{ __('ui.tokens.create_title') }}</h2><div class="mt-5"><label class="label">{{ __('ui.tokens.name') }}</label><input class="input" name="name" value="{{ old('name') }}" required></div><div class="mt-4"><label class="label">Expiration</label><input class="input" type="datetime-local" name="expires_at"></div><div class="mt-4"><label class="label">Abilities</label><div class="mt-2 grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-3">@foreach(['*','links:read','links:write','analytics:read','domains:read','domains:write','texts:read','texts:write','files:read','files:write','profiles:read','profiles:write','webhooks:read','webhooks:write','conversions:write'] as $ability)<label class="flex items-center gap-2 text-xs"><input type="checkbox" name="abilities[]" value="{{ $ability }}" @checked($ability==='*')><code>{{ $ability }}</code></label>@endforeach</div></div><button class="btn-brand mt-5 w-full py-3">{{ __('ui.tokens.create_button') }}</button></form>
      <div class="space-y-4">@forelse($tokens as $token)<article class="card"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-700">⌘</span><div><h2 class="font-bold text-slate-950">{{ $token->name }}</h2><p class="mt-1 text-xs text-slate-500">{{ __('ui.tokens.last_used',['time'=>$token->last_used_at?->diffForHumans() ?? __('ui.common.never')]) }} · {{ $token->expires_at?->diffForHumans() ?? 'No expiration' }}</p></div></div><div class="mt-4 flex flex-wrap gap-2">@foreach($token->abilities ?? ['*'] as $ability)<span class="badge-neutral"><code>{{ $ability }}</code></span>@endforeach</div></div><form method="post" action="{{ route('tokens.destroy',$token) }}" onsubmit="return confirm(@js(__('ui.tokens.revoke_confirm'))) ">@csrf @method('delete')<button class="btn-danger">{{ __('ui.tokens.revoke') }}</button></form></div></article>@empty<div class="empty-state">{{ __('ui.tokens.empty') }}</div>@endforelse</div>
    </div>

    <div class="card mt-7"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="font-bold text-slate-950">{{ __('ui.tokens.base_url') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('ui.tokens.authorization') }}</p></div><a class="btn-secondary" href="{{ route('api-docs') }}" target="_blank">API documentation ↗</a></div><code class="code-panel mt-4 block">{{ url('/api/v1') }}</code><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Links & routing','Analytics & conversions','Domains & DNS','Text, files & profiles','Webhooks & events'] as $group)<div class="rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-600">{{ $group }}</div>@endforeach</div></div>
  </section>
</x-layouts.app>
