import { expect, test } from '@playwright/test';
const staticRoutes=['/products/','/products/links/','/products/qr-codes/','/products/files/','/products/text-sharing/','/products/link-in-bio/','/products/analytics/','/products/smart-routing/','/products/custom-domains/','/solutions/','/solutions/marketing/','/solutions/creators/','/solutions/teams/','/solutions/developers/','/developers/','/pricing/','/security/','/about/','/contact/','/legal/privacy/','/legal/terms/','/legal/acceptable-use/'];

test('final homepage uses exact-head product UI composition and frozen shell',async({page})=>{await page.goto('/');await expect(page.locator('.gj-website-shell')).toBeVisible();await expect(page.getByRole('heading',{name:'Create. Control. Understand. Operate.',level:1})).toBeVisible();await expect(page.locator('[data-product-source="workspace-exact-head"]')).toBeVisible();for(const label of['Destination','Domain','Code','Title'])await expect(page.getByText(label,{exact:true}).first()).toBeVisible();await expect(page.getByText('Advanced settings',{exact:true})).toBeVisible();await expect(page.getByText('QR live preview',{exact:true})).toBeVisible();await expect(page.getByText('Export CSV',{exact:true})).toBeVisible();await expect(page.getByText('Destination Risk',{exact:true})).toBeVisible();const width=page.viewportSize()?.width??1440;const header=await page.locator('.gj-website-header').boundingBox();expect(Math.abs((header?.height??0)-(width<=767?60:64))).toBeLessThanOrEqual(1);await page.evaluate(()=>scrollTo(0,100));await expect(page.locator('.gj-website-header')).toHaveAttribute('data-sticky','true');const dims=await page.evaluate(()=>({s:document.documentElement.scrollWidth,c:document.documentElement.clientWidth}));expect(dims.s).toBeLessThanOrEqual(dims.c+1);});

test('static marketing IA and SEO are prerendered',async({page})=>{for(const route of staticRoutes){const response=await page.goto(route);expect(response?.ok(),route).toBeTruthy();await expect(page.locator('h1')).toBeVisible();await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',new RegExp(route.replaceAll('/','\\/')));await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content',/.+/);await expect(page.locator('script[type="application/ld+json"]')).toHaveCount(1);}});

test('pricing never invents a static amount',async({page})=>{await page.goto('/pricing/');await expect(page.locator('[data-pricing-source="server"]')).toBeVisible();await expect(page.getByText('No duplicated static price table.')).toBeVisible();await expect(page.getByRole('link',{name:'Open Workspace Billing'})).toHaveAttribute('href','/app/billing');});

test('reduced motion disables continuous homepage animation',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');for(const selector of['.ambient-halo','.product-float','.product-float-delayed','.jet-path span']){await expect.poll(()=>page.locator(selector).first().evaluate(el=>getComputedStyle(el).animationName)).toBe('none');}});
