import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { AdminFXPayload } from "@gojet/api-client";
import { Alert, Badge, Button, EmptyState, ErrorState, Field, Input, Page, PageHeader, Select, Spinner, Textarea } from "@gojet/ui";
import { adminDate, adminError, commerceClient } from "../commerce";

function FXEditor({ data }: { data: AdminFXPayload }) {
  const queryClient = useQueryClient();
  const [currency, setCurrency] = useState(data.settlement_currency || "USD");
  const [provider, setProvider] = useState<"ecb" | "manual">(data.provider || "ecb");
  const [markup, setMarkup] = useState(String(data.markup_bps));
  const [cacheHours, setCacheHours] = useState(String(data.cache_hours));
  const [manualRates, setManualRates] = useState(JSON.stringify(data.manual_rates ?? {}, null, 2));
  const [reason, setReason] = useState("");
  const [parseError, setParseError] = useState("");
  const mutation = useMutation({ mutationFn: async () => {
    let rates: Record<string,string> = {};
    try { rates = JSON.parse(manualRates) as Record<string,string>; setParseError(""); }
    catch { setParseError("Manual rates must be valid JSON."); throw new Error("Manual rates must be valid JSON."); }
    return commerceClient.updateFX({ settlement_currency: currency.trim().toUpperCase(), provider, markup_bps: Number(markup), cache_hours: Number(cacheHours), manual_rates: rates, reason: reason.trim() });
  }, onSuccess: async () => { setReason(""); await queryClient.invalidateQueries({ queryKey: ["admin-fx"] }); } });
  return <section className="commerce-fx-editor"><div className="commerce-section-head"><div><span>FX CONTROL</span><h2>Provider & settlement policy</h2><p>Manual override requires an operator reason. Saving invalidates the FX cache and writes an admin audit record.</p></div><Badge tone={provider === "manual" ? "warning" : "success"}>{provider}</Badge></div><div className="commerce-form-grid"><Field label="Settlement currency" htmlFor="fx-currency"><Input id="fx-currency" maxLength={3} value={currency} onChange={(event) => setCurrency(event.target.value)} /></Field><Field label="Provider" htmlFor="fx-provider"><Select id="fx-provider" value={provider} onChange={(event) => setProvider(event.target.value as "ecb" | "manual")}><option value="ecb">ECB</option><option value="manual">Manual</option></Select></Field><Field label="Markup · basis points" htmlFor="fx-markup"><Input id="fx-markup" type="number" min="-1000" max="5000" value={markup} onChange={(event) => setMarkup(event.target.value)} /></Field><Field label="Cache hours" htmlFor="fx-cache"><Input id="fx-cache" type="number" min="1" max="168" value={cacheHours} onChange={(event) => setCacheHours(event.target.value)} /></Field></div><Field label="Manual USD rates · JSON" htmlFor="fx-rates" help='Keys use USD/XXX, for example {"USD/SGD":"1.34"}.' error={parseError || undefined}><Textarea id="fx-rates" rows={7} value={manualRates} onChange={(event) => setManualRates(event.target.value)} /></Field><Field label="Change reason" htmlFor="fx-reason" required help="1–500 characters; stored in the audit log."><Textarea id="fx-reason" rows={3} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)} /></Field>{mutation.isError && !parseError ? <Alert tone="danger" title="FX update failed">{adminError(mutation.error)}</Alert> : null}<Button type="button" loading={mutation.isPending} disabled={!reason.trim()} onClick={() => mutation.mutate()}>Save audited FX override</Button></section>;
}

export default function FXPage() {
  const fx = useQuery({ queryKey: ["admin-fx"], queryFn: () => commerceClient.adminFX() });
  return <Page className="commerce-page" data-p13-admin-fx><PageHeader title="FX" description="Settlement currency, rate provider, markup, cache, manual override and invoice FX history." />{fx.isPending ? <div className="commerce-centered"><Spinner label="Loading FX" /></div> : fx.isError ? <ErrorState title="Unable to load FX" description={adminError(fx.error)} action={<Button type="button" onClick={() => fx.refetch()}>Retry</Button>} /> : fx.data ? <div className="commerce-stack"><FXEditor data={fx.data} /><section className="commerce-section"><div className="commerce-section-head"><div><span>RATE CACHE</span><h2>Current cached rates</h2><p>Rates show provider observation and expiry. Saving FX configuration clears this cache.</p></div></div>{fx.data.rates.length ? <div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Pair</th><th>Rate</th><th>Provider</th><th>Observed</th><th>Expires</th></tr></thead><tbody>{fx.data.rates.map((rate) => <tr key={`${rate.base_currency}-${rate.quote_currency}-${rate.observed_at}`}><td>{rate.base_currency}/{rate.quote_currency}</td><td className="commerce-mono">{rate.rate}</td><td>{rate.provider}</td><td>{adminDate(rate.observed_at)}</td><td>{adminDate(rate.expires_at)}</td></tr>)}</tbody></table></div> : <EmptyState title="No cached rates" description="Rates are populated when a conversion is requested." />}</section><section className="commerce-section"><div className="commerce-section-head"><div><span>FX HISTORY</span><h2>Invoice snapshots</h2><p>Historical invoices preserve the exact rate, provider, markup and quoted time used for settlement.</p></div></div>{fx.data.history.length ? <div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Invoice</th><th>Pair</th><th>Rate</th><th>Provider</th><th>Markup</th><th>Quoted</th></tr></thead><tbody>{fx.data.history.map((item) => <tr key={`${item.invoice_number}-${item.created_at}`}><td>{item.invoice_number}</td><td>{item.source_currency}/{item.currency}</td><td className="commerce-mono">{item.rate}</td><td>{item.provider}</td><td>{item.markup_bps} bps</td><td>{adminDate(item.quoted_at)}</td></tr>)}</tbody></table></div> : <EmptyState title="No FX history" description="Invoice FX snapshots appear when cross-currency invoices are created." />}</section></div> : null}</Page>;
}
