import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Badge, Button, EmptyState, ErrorState, Field, Page, PageHeader, Select, Spinner } from "@gojet/ui";
import { SideSheet } from "@gojet/ui/overlays";
import { adminDate, adminError, adminMoney, commerceClient } from "../commerce";

function PaymentDetail({ paymentId }: { paymentId: number }) {
  const detail = useQuery({ queryKey: ["admin-payment", paymentId], queryFn: () => commerceClient.adminPayment(paymentId) });
  if (detail.isPending) return <div className="commerce-centered"><Spinner label="Loading payment detail" /></div>;
  if (detail.isError) return <ErrorState title="Unable to load payment detail" description={adminError(detail.error)} />;
  const data = detail.data;
  return <div className="commerce-payment-detail"><Alert tone="info" title="Sensitive callback payload is redacted">The API exposes hashes, references and processing outcomes only. Raw provider payload and secrets are never rendered in Admin UI.</Alert><dl className="commerce-detail-list"><div><dt>Provider order</dt><dd>{data.payment.provider_order_id || "—"}</dd></div><div><dt>Merchant order</dt><dd>{data.payment.merchant_order_no}</dd></div><div><dt>Owner</dt><dd>{data.payment.owner_email || "—"}</dd></div><div><dt>Failure reason</dt><dd>{data.payment.failure_reason || "—"}</dd></div></dl><section><h3>Callback timeline</h3>{data.callbacks.length ? <div className="commerce-timeline">{data.callbacks.map((callback) => <article key={callback.id}><span className="commerce-timeline-dot" aria-hidden="true" /><div><div className="commerce-timeline-head"><strong>{callback.provider} · {callback.outcome}</strong><Badge tone={callback.outcome === "accepted" ? "success" : "danger"}>HTTP {callback.response_status}</Badge></div><p>{adminDate(callback.created_at)} · {callback.remote_ip}</p><dl><div><dt>Request ID</dt><dd>{callback.request_id || "—"}</dd></div><div><dt>Provider ref</dt><dd>{callback.provider_reference || "—"}</dd></div><div><dt>Payload SHA-256</dt><dd className="commerce-mono">{callback.payload_sha256}</dd></div></dl></div></article>)}</div> : <EmptyState title="No callbacks" description="No callback observer events are attached to this transaction yet." />}</section></div>;
}

export default function PaymentsPage() {
  const [status, setStatus] = useState("");
  const [provider, setProvider] = useState("");
  const payments = useQuery({ queryKey: ["admin-payments", status, provider], queryFn: () => commerceClient.adminPayments(status, provider) });
  const data = payments.data?.data ?? [];
  return <Page className="commerce-page" data-p13-admin-payments>
    <PageHeader title="Payments" description="Provider transactions, real server state and redacted callback evidence." actions={<div className="commerce-filter-row"><Field label="Status" htmlFor="payment-status"><Select id="payment-status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All</option><option value="created">Created</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="closed">Closed</option></Select></Field><Field label="Provider" htmlFor="payment-provider"><Select id="payment-provider" value={provider} onChange={(event) => setProvider(event.target.value)}><option value="">All</option><option value="stripe">Stripe</option><option value="paypal">PayPal</option><option value="alipay">Alipay</option><option value="wechat">WeChat Pay</option></Select></Field></div>} />
    {payments.isPending ? <div className="commerce-centered"><Spinner label="Loading payments" /></div> : payments.isError ? <ErrorState title="Unable to load payments" description={adminError(payments.error)} action={<Button type="button" onClick={() => payments.refetch()}>Retry</Button>} /> : data.length ? <div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Order</th><th>User / workspace</th><th>Amount</th><th>Channel</th><th>Provider ref</th><th>Status</th><th>Updated</th><th>Detail</th></tr></thead><tbody>{data.map((payment) => <tr key={payment.id}><td><strong>{payment.merchant_order_no}</strong><small>Invoice #{payment.invoice_id}</small></td><td>{payment.owner_email || "—"}<small>Workspace #{payment.workspace_id}</small></td><td>{adminMoney(payment.amount_cents, payment.currency)}</td><td>{payment.provider}</td><td className="commerce-mono">{payment.provider_order_id || "—"}</td><td><Badge tone={payment.status === "paid" ? "success" : payment.status === "failed" ? "danger" : payment.status === "pending" ? "warning" : "neutral"}>{payment.status}</Badge></td><td>{adminDate(payment.updated_at)}</td><td><SideSheet triggerLabel="View" title={`Payment ${payment.merchant_order_no}`} description="Transaction state and callback processing evidence."><PaymentDetail paymentId={payment.id} /></SideSheet></td></tr>)}</tbody></table></div> : <EmptyState title="No payments" description="No payment transactions match the current filters." />}
  </Page>;
}
