#!/usr/bin/env bash
set -euo pipefail

SOURCE=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
TARGET=${1:-}
SERVICES=(log-receiver redirect-engine platform-api analytics-worker analytics-reconciler mail-worker file-worker operations-monitor)

[[ $(id -u) -eq 0 ]] || { echo '请使用 sudo/root 执行升级。' >&2; exit 1; }
if [[ -z "$TARGET" ]]; then
  if [[ -f "$SOURCE/deploy/native/installed.lock" ]]; then
    TARGET=$SOURCE
  else
    echo "用法：sudo ./upgrade-native.sh /www/wwwroot/你的站点目录" >&2
    exit 1
  fi
fi
TARGET=$(readlink -f "$TARGET")
[[ -d "$TARGET" && -f "$TARGET/deploy/native/installed.lock" ]] || { echo '目标目录不是已安装的 GoJet Native 实例。' >&2; exit 1; }
[[ -f "$TARGET/deploy/native/gojet.env" ]] || { echo '缺少 deploy/native/gojet.env。' >&2; exit 1; }
[[ -x "$SOURCE/bin/platform-api" && -f "$SOURCE/public/admin/index.html" ]] || { echo '升级包不完整。' >&2; exit 1; }

ENV_FILE="$TARGET/deploy/native/gojet.env"
[[ $(stat -c '%u' "$ENV_FILE") -eq 0 ]] || { echo 'gojet.env 必须由 root 所有。' >&2; exit 1; }
mode=$(stat -c '%a' "$ENV_FILE")
[[ "$mode" == "600" || "$mode" == "400" ]] || { echo 'gojet.env 权限必须为 600/400。' >&2; exit 1; }
# gojet.env is generated by the root installer and is not writable by the web user.
# shellcheck disable=SC1090
source "$ENV_FILE"

mysql_bin=$(command -v mysql 2>/dev/null || true)
[[ -n "$mysql_bin" ]] || [[ ! -x /www/server/mysql/bin/mysql ]] || mysql_bin=/www/server/mysql/bin/mysql
[[ -n "$mysql_bin" && -x "$mysql_bin" ]] || { echo '未找到 MySQL 客户端。' >&2; exit 1; }
for tool in systemctl curl cp mv mkdir date; do command -v "$tool" >/dev/null 2>&1 || { echo "缺少命令：$tool" >&2; exit 1; }; done

MYSQL_HOST=${MYSQL_HOST:-127.0.0.1}
MYSQL_PORT=${MYSQL_PORT:-3306}
: "${MYSQL_DATABASE:?MYSQL_DATABASE missing}"
: "${MYSQL_USER:?MYSQL_USER missing}"
: "${MYSQL_PASSWORD:?MYSQL_PASSWORD missing}"
mysql_exec(){ MYSQL_PWD="$MYSQL_PASSWORD" "$mysql_bin" -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" "$MYSQL_DATABASE" "$@"; }

stamp=$(date -u +%Y%m%dT%H%M%SZ)
BACKUP="$TARGET/backups/native-upgrade-$stamp"
mkdir -p "$BACKUP"
cp -a "$TARGET/bin" "$BACKUP/bin"
cp -a "$TARGET/public/admin" "$BACKUP/admin"
[[ ! -f "$TARGET/VERSION" ]] || cp -a "$TARGET/VERSION" "$BACKUP/VERSION"

rollback(){
  local rc=$?
  set +e
  echo '升级失败，正在恢复升级前程序文件…' >&2
  rm -rf "$TARGET/bin" "$TARGET/public/admin"
  cp -a "$BACKUP/bin" "$TARGET/bin"
  cp -a "$BACKUP/admin" "$TARGET/public/admin"
  if [[ -f "$BACKUP/VERSION" ]]; then cp -a "$BACKUP/VERSION" "$TARGET/VERSION"; fi
  for service in "${SERVICES[@]}"; do systemctl restart "gojet@$service.service" >/dev/null 2>&1 || true; done
  echo "已回滚程序文件。备份目录：$BACKUP" >&2
  exit "$rc"
}
trap rollback ERR

echo '[1/5] 验证数据库并执行缺失迁移…'
mysql_exec -e 'SELECT 1' >/dev/null
mysql_exec -e "CREATE TABLE IF NOT EXISTS schema_migrations(name VARCHAR(255) PRIMARY KEY,applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)" >/dev/null
for migration in "$SOURCE"/database/migrations/*.sql; do
  name=$(basename "$migration")
  applied=$(mysql_exec -N -s -e "SELECT COUNT(*) FROM schema_migrations WHERE name='$name'")
  [[ "$applied" == "0" ]] || continue
  if [[ "$name" == "026_admin_step_up_session.sql" ]]; then
    column_exists=$(mysql_exec -N -s -e "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='administrator_sessions' AND COLUMN_NAME='step_up_until'")
    if [[ "$column_exists" != "0" ]]; then
      mysql_exec -e "INSERT INTO schema_migrations(name) VALUES('$name')" >/dev/null
      continue
    fi
  fi
  mysql_exec < "$migration"
  mysql_exec -e "INSERT INTO schema_migrations(name) VALUES('$name')" >/dev/null
done
mkdir -p "$TARGET/database/migrations"
cp -a "$SOURCE/database/migrations/." "$TARGET/database/migrations/"

echo '[2/5] 更新 GoJet 服务程序…'
for binary in "$SOURCE"/bin/*; do
  name=$(basename "$binary")
  install -m 0755 "$binary" "$TARGET/bin/.${name}.new"
  mv -f "$TARGET/bin/.${name}.new" "$TARGET/bin/$name"
done

echo '[3/5] 更新管理员前端…'
rm -rf "$TARGET/public/admin.new"
cp -a "$SOURCE/public/admin" "$TARGET/public/admin.new"
rm -rf "$TARGET/public/admin"
mv "$TARGET/public/admin.new" "$TARGET/public/admin"
if [[ -d "$TARGET/frontend/admin-console" && -d "$SOURCE/frontend/admin-console" ]]; then
  rm -rf "$TARGET/frontend/admin-console"
  cp -a "$SOURCE/frontend/admin-console" "$TARGET/frontend/admin-console"
fi
cp -a "$SOURCE/VERSION" "$TARGET/VERSION"

echo '[4/5] 重启 8 个 GoJet 服务…'
for service in "${SERVICES[@]}"; do
  systemctl restart "gojet@$service.service"
done

for _ in {1..30}; do
  all_active=1
  for service in "${SERVICES[@]}"; do
    systemctl is-active --quiet "gojet@$service.service" || all_active=0
  done
  if [[ "$all_active" -eq 1 ]] && curl -fsS http://127.0.0.1:18080/health >/dev/null 2>&1 && curl -fsS http://127.0.0.1:18090/health >/dev/null 2>&1 && curl -fsS http://127.0.0.1:18092/health >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
for service in "${SERVICES[@]}"; do systemctl is-active --quiet "gojet@$service.service"; done
curl -fsS http://127.0.0.1:18080/health >/dev/null
curl -fsS http://127.0.0.1:18090/health >/dev/null
curl -fsS http://127.0.0.1:18092/health >/dev/null

echo '[5/5] 升级完成。'
trap - ERR
printf 'GoJet Native 升级成功：%s\n备份：%s\n' "$(cat "$TARGET/VERSION")" "$BACKUP"
