(()=>{
'use strict';
const state={token:localStorage.getItem('gojet_token')||'',workspace:0,links:[],resourceBios:[]};window.state=state;
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];Object.assign(window,{$,$$});
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function number(value){return Number(value||0).toLocaleString('zh-CN')}
function date(value){if(!value)return'—';const parsed=new Date(value);return Number.isNaN(parsed.valueOf())?String(value):parsed.toLocaleString('zh-CN',{hour12:false})}
function fileSize(value){const bytes=Number(value||0);if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(bytes<10240?1:0)} KB`;if(bytes<1073741824)return`${(bytes/1048576).toFixed(bytes<10485760?1:0)} MB`;return`${(bytes/1073741824).toFixed(1)} GB`}
Object.assign(window,{escapeHTML,number,date,fileSize});
async function api(path,options={}){const headers={...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;if(options.body!==undefined&&!(options.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});if(response.status===401){localStorage.removeItem('gojet_token');state.token='';const redirect=location.pathname+location.search+location.hash;location.replace(`/login?redirect=${encodeURIComponent(redirect)}`);throw new Error('登录状态已失效，请重新登录')}const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||body.message||`请求失败 (${response.status})`);return body}window.api=api;
function trendBars(points){const values=(points||[]).map(item=>Number(item.clicks??item.Clicks??0)),max=Math.max(1,...values);if(!values.length)return'<div class="empty"><b>还没有趋势数据</b><span>产生访问后，这里会显示最近 30 天的变化。</span></div>';return`<div class="trendBars">${values.map((value,index)=>`<i title="${escapeHTML(points[index]?.date??points[index]?.Date??'')} · ${number(value)} 次访问" style="height:${Math.max(value?5:2,Math.round(value/max*100))}%"></i>`).join('')}</div>`}
function usageLine(label,used,limit,formatter=number){const current=Number(used||0),cap=Number(limit||0),percent=cap>0?Math.min(100,Math.round(current/cap*100)):0;return`<div class="usageLine"><span><b>${escapeHTML(label)}</b><em>${formatter(current)}${cap>0?` / ${formatter(cap)}`:' / 不限'}</em></span><i><em style="width:${percent}%"></em></i></div>`}
function recentRows(items){if(!Array.isArray(items)||!items.length)return'<div class="empty"><b>还没有最近活动</b><span>创建和访问短链接后，这里会出现最新记录。</span></div>';return items.slice(0,6).map(item=>{const code=item.code??item.Code??'',title=item.title??item.Title??item.destination??item.Destination??'未命名链接',clicks=item.clicks??item.Clicks??0;return`<div class="recentRow"><a class="short" href="/app/links">/${escapeHTML(code)}</a><span>${escapeHTML(title)}</span><small>${number(clicks)} 次访问</small></div>`}).join('')}
async function renderOverview(){const content=$('.content');if(!content||!state.workspace)return;content.innerHTML='<div class="productLoading">正在加载工作区总览…</div>';try{const data=await api(`/api/workspaces/${state.workspace}/overview`),usage=data.usage||{};content.innerHTML=`<div class="title"><div><small>工作区总览</small><h1>今天的 GoJet</h1><p>查看访问表现、活跃链接和当前套餐用量。</p></div><button class="primary" id="overviewCreate">新建短链接</button></div><div class="metrics"><article><span>今日访问</span><strong>${number(data.today_clicks)}</strong><small>今天累计</small></article><article><span>本月访问</span><strong>${number(data.month_clicks)}</strong><small>本月累计</small></article><article><span>本月独立访客</span><strong>${number(data.unique_visitors)}</strong><small>按访客去重</small></article><article><span>活跃链接</span><strong>${number(data.active_links)}</strong><small>${escapeHTML(usage.plan_name||'当前套餐')}</small></article></div><div class="overviewGrid"><section class="overviewPanel trendPanel"><h2>最近 30 天访问趋势</h2>${trendBars(data.trend||[])}</section><section class="overviewPanel"><h2>资源用量</h2>${usageLine('短链接',usage.links,usage.link_limit)}${usageLine('二维码',usage.qr_codes,usage.qr_limit)}${usageLine('团队成员',usage.members,usage.member_limit)}${usageLine('文件空间',usage.file_bytes,usage.file_storage_bytes,fileSize)}</section></div><section class="overviewPanel"><h2>最近活动</h2>${recentRows(data.recent||[])}</section>`;$('#overviewCreate')?.addEventListener('click',()=>window.GoJetRouter?.show('links'))}catch(error){content.innerHTML=`<div class="productError">${escapeHTML(error.message)}</div>`}}window.renderOverview=renderOverview;
function selectedWorkspace(items){const remembered=Number(localStorage.getItem('gojet_workspace')||0);return items.some(item=>Number(item.id)===remembered)?remembered:Number(items[0]?.id||0)}
function populateWorkspace(items){const select=$('#workspace');select.innerHTML=items.map(item=>`<option value="${Number(item.id)}">${escapeHTML(item.name)}</option>`).join('');state.workspace=selectedWorkspace(items);if(state.workspace){select.value=String(state.workspace);localStorage.setItem('gojet_workspace',String(state.workspace))}}
function bindShell(){
  $('#workspace')?.addEventListener('change',event=>{state.workspace=Number(event.target.value||0);localStorage.setItem('gojet_workspace',String(state.workspace));if(window.GoJetRouter)window.GoJetRouter.showCurrent();else renderOverview()});
  const search=$('#globalSearch');search?.addEventListener('keydown',event=>{if(event.key!=='Enter')return;const query=search.value.trim();if(!query)return;history.pushState({view:'links'},'',`/app/links?q=${encodeURIComponent(query)}`);window.GoJetRouter?.show('links',false)});
}
async function bootstrap(){if(!state.token)return;try{const [user,workspaceResult]=await Promise.all([api('/api/me'),api('/api/workspaces')]),workspaces=workspaceResult.data||[];populateWorkspace(workspaces);$('#userName').textContent=user.display_name||user.email||'我的账户';$('#userEmail').textContent=user.email||'';$('#shell').classList.remove('hidden');bindShell();if(state.workspace)await renderOverview();else $('.content').innerHTML='<div class="productEmpty"><h3>还没有工作区</h3><p>创建工作区后即可开始使用 GoJet。</p></div>';window.dispatchEvent(new CustomEvent('gojet:workspace-ready',{detail:{workspace:state.workspace,user}}))}catch(error){if(state.token&&$('.content'))$('.content').innerHTML=`<div class="productError">${escapeHTML(error.message)}</div>`}}
bootstrap();
})();