const state={token:localStorage.getItem('gojet_token'),workspace:0,offset:0,limit:25,total:0,links:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const data=response.status===204?null:await response.json().catch(()=>({error:'服务器返回了无效响应'}));if(!response.ok)throw new Error(data?.error||`请求失败 (${response.status})`);return data}
function showApp(user){$('#auth').classList.add('hidden');$('#shell').classList.remove('hidden');$('#userName').textContent=user.display_name;$('#userEmail').textContent=user.email}
async function bootstrap(){if(!state.token)return;try{showApp(await api('/api/me'));const result=await api('/api/workspaces');$('#workspace').innerHTML=result.data.map(w=>`<option value="${w.id}">${escapeHTML(w.name)} · ${roleName(w.role)}</option>`).join('');if(result.data.length){state.workspace=result.data[0].id;await loadLinks()}}catch(e){localStorage.removeItem('gojet_token');state.token=null}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify(body)});state.token=result.token;localStorage.setItem('gojet_token',state.token);showApp(result.user);await bootstrap()}catch(err){$('#authError').textContent=err.message}});
$('#workspace').addEventListener('change',e=>{state.workspace=Number(e.target.value);state.offset=0;loadLinks()});$('#status').addEventListener('change',()=>{state.offset=0;loadLinks()});$('#globalSearch').addEventListener('input',debounce(()=>{state.offset=0;loadLinks()},350));$('#refresh').onclick=loadLinks;
async function loadLinks(){const q=new URLSearchParams({limit:state.limit,offset:state.offset,search:$('#globalSearch').value,status:$('#status').value});try{const result=await api(`/api/workspaces/${state.workspace}/links?${q}`);state.links=result.data;state.total=result.total;renderLinks()}catch(e){$('#links').innerHTML=`<tr><td colspan="8" class="error">${escapeHTML(e.message)}</td></tr>`}}
function renderLinks(){let clicks=0,visitors=0,active=0;$('#links').innerHTML=state.links.map(l=>{clicks+=l.Clicks||0;visitors+=l.Visitors||0;if(l.Status==='active')active++;return `<tr><td><input class="rowCheck" type="checkbox" value="${l.ID}"></td><td><span class="short">/${escapeHTML(l.Code)}</span><small>${escapeHTML(l.Title||'未命名链接')}</small></td><td><span class="destination" title="${escapeHTML(l.Destination)}">${escapeHTML(l.Destination)}</span></td><td>${number(l.Clicks)}</td><td>${number(l.Visitors)}</td><td>${date(l.CreatedAt)}</td><td><span class="badge ${l.Status}">${statusName(l.Status)}</span></td><td><button onclick="analytics(${l.ID},'${escapeHTML(l.Code)}')">分析</button></td></tr>`}).join('');$('#empty').classList.toggle('hidden',state.links.length>0);$('#totalClicks').textContent=number(clicks);$('#totalVisitors').textContent=number(visitors);$('#activeLinks').textContent=number(active);$('#usage').textContent=`${state.total} / —`;$('#resultCount').textContent=`共 ${state.total} 条`;$('#page').textContent=`${Math.floor(state.offset/state.limit)+1} / ${Math.max(1,Math.ceil(state.total/state.limit))}`;$('#prev').disabled=state.offset===0;$('#next').disabled=state.offset+state.limit>=state.total}
$('#createButton').onclick=()=>$('#drawer').classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=()=>$('#drawer').classList.add('hidden'));$('#createForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const body={destination:f.destination,code:f.code,title:f.title,redirect_status:Number(f.redirect_status),one_time:f.one_time==='on',expires_at:f.expires_at||null,max_clicks:f.max_clicks?Number(f.max_clicks):null,UTM:{source:f.utm_source,medium:f.utm_medium,campaign:f.utm_campaign,content:f.utm_content}};try{await api(`/api/workspaces/${state.workspace}/links`,{method:'POST',body:JSON.stringify(body)});e.target.reset();$('#drawer').classList.add('hidden');await loadLinks()}catch(err){$('#createError').textContent=err.message}});
async function bulk(status){const ids=$$('.rowCheck:checked').map(x=>Number(x.value));if(!ids.length)return alert('请先选择链接');await api(`/api/workspaces/${state.workspace}/links/bulk-status`,{method:'PATCH',body:JSON.stringify({ids,status})});loadLinks()}$('#enable').onclick=()=>bulk('active');$('#pause').onclick=()=>bulk('paused');$('#checkAll').onchange=e=>$$('.rowCheck').forEach(x=>x.checked=e.target.checked);$('#prev').onclick=()=>{state.offset=Math.max(0,state.offset-state.limit);loadLinks()};$('#next').onclick=()=>{state.offset+=state.limit;loadLinks()};
async function analytics(id,code){$('#analyticsModal').classList.remove('hidden');$('#analyticsTitle').textContent=`/${code} 数据分析`;$('#analyticsBody').innerHTML='正在读取真实访问事件…';try{const d=await api(`/api/workspaces/${state.workspace}/links/${id}/analytics`);const source=d.Sources||d.sources||[];$('#analyticsBody').innerHTML=`<div class="cards"><article>累计点击<strong>${number(d.Clicks||d.clicks)}</strong></article><article>独立访客<strong>${number(d.UniqueVisitors||d.unique_visitors)}</strong></article><article>机器人访问<strong>${number(d.BotVisits||d.bot_visits)}</strong></article></div><section><h3>访问来源</h3><div class="bars">${bars(source)}</div></section><section><h3>设备</h3><div class="bars">${bars(d.Devices||d.devices||[])}</div></section><section><h3>浏览器</h3><div class="bars">${bars(d.Browsers||d.browsers||[])}</div></section><section><h3>最近访问事件</h3>${events(d.Recent||d.recent||[])}</section>`}catch(e){$('#analyticsBody').innerHTML=`<div class="error">${escapeHTML(e.message)}</div>`}}window.analytics=analytics;$$('[data-close-analytics]').forEach(b=>b.onclick=()=>$('#analyticsModal').classList.add('hidden'));
function bars(items){const max=Math.max(1,...items.map(x=>x.Count||x.count));return items.length?items.map(x=>`<div class="bar"><span>${escapeHTML(x.Name||x.name)}</span><i style="width:${(x.Count||x.count)/max*100}%"></i><b>${number(x.Count||x.count)}</b></div>`).join(''):'<p>暂无数据</p>'}function events(items){return items.length?`<table><thead><tr><th>时间</th><th>来源</th><th>国家</th><th>设备</th><th>浏览器</th><th>类型</th></tr></thead><tbody>${items.map(x=>`<tr><td>${date(x.timestamp)}</td><td>${escapeHTML(x.source)}</td><td>${escapeHTML(x.country||'—')}</td><td>${escapeHTML(x.device)}</td><td>${escapeHTML(x.browser)}</td><td>${x.is_bot?'机器人':'访客'}</td></tr>`).join('')}</tbody></table>`:'<p>暂无访问事件</p>'}
function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function number(v=0){return Number(v||0).toLocaleString('zh-CN')}function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.valueOf())?v:d.toLocaleString('zh-CN')}function statusName(v){return({active:'启用',paused:'暂停',expired:'已过期'})[v]||v}function roleName(v){return({owner:'所有者',admin:'管理员',editor:'编辑者',analyst:'分析员',viewer:'只读成员'})[v]||v}function debounce(fn,ms){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms)}}
bootstrap();
