(()=>{
const BQ=s=>document.querySelector(s),BQA=s=>[...document.querySelectorAll(s)],BE=v=>escapeHTML(v??'');let billingData=null,paymentPoll=null;
const statusName={active:'使用中',past_due:'待处理',cancelled:'已取消',pending:'待支付',paid:'已支付',void:'已作废',overdue:'已逾期'};
const typeName={purchase:'购买套餐',upgrade:'变更套餐',renewal:'续费'};
const providerName={alipay:'支付宝',wechat:'微信支付',epay:'易支付兼容协议',paypal:'PayPal',stripe:'Stripe'};
function money(cents,currency='CNY'){try{return new Intl.NumberFormat('zh-CN',{style:'currency',currency:currency||'CNY'}).format(Number(cents||0)/100)}catch{return `${currency} ${(Number(cents||0)/100).toFixed(2)}`}}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.valueOf())?String(v):d.toLocaleString('zh-CN',{hour12:false})}
function modal(title,body){const layer=document.createElement('div');layer.className='productModalLayer';layer.innerHTML=`<div class="productModal billingDialog"><div class="productModalHead"><h2>${BE(title)}</h2><button type="button" data-close>×</button></div><div class="billingDialogBody">${body}</div></div>`;document.body.appendChild(layer);const close=()=>{clearInterval(paymentPoll);paymentPoll=null;layer.remove()};layer.querySelector('[data-close]').onclick=close;return{layer,close}}
async function render(){clearInterval(paymentPoll);const c=BQ('.content');c.innerHTML=`<div class="productPageHead"><div><h1>套餐与账单</h1><p>查看当前套餐、用量和账单，在线支付完成后会自动更新订阅状态。</p></div><button id="billingRefresh">刷新</button></div><div id="billingWorkspace" class="productLoading">正在加载账单…</div>`;BQ('#billingRefresh').onclick=render;await load()}
async function load(){try{billingData=await api(`/api/workspaces/${state.workspace}/billing`);const d=billingData,sub=d.subscription||{},plans=d.plans||[],invoices=d.invoices||[];BQ('#billingWorkspace').innerHTML=`${paymentNotice()}<section class="subscriptionSummary billingSummary"><div><small>当前套餐</small><h2>${BE(sub.plan_name||'基础套餐')}</h2><p>${sub.period_ends_at?'当前周期至 '+fmtDate(sub.period_ends_at):'当前套餐长期有效'}</p></div><span class="productStatus">${BE(statusName[sub.status]||sub.status||'使用中')}</span>${sub.plan_code&&sub.plan_code!=='starter'?`<button id="billingCancellation">${sub.cancel_at_period_end?'继续订阅':'到期后取消'}</button>`:''}</section>${sub.cancel_at_period_end?'<div class="notice">当前套餐将在本周期结束后停止续订。你可以在到期前恢复续订。</div>':''}<section class="billingSection"><div class="billingSectionHead"><div><h2>选择套餐</h2><p>变更套餐会先生成账单，支付完成后自动生效。</p></div></div><div class="planGrid billingPlans">${plans.map(p=>planCard(p,sub)).join('')}</div></section><section class="billingSection"><div class="billingSectionHead"><div><h2>账单记录</h2><p>所有金额、状态与付款结果均以账单记录为准。</p></div></div>${invoices.length?`<div class="billingInvoiceList">${invoices.map(invoiceCard).join('')}</div>`:'<div class="billingEmpty">还没有账单。</div>'}</section>`;wire(sub,invoices)}catch(err){BQ('#billingWorkspace').innerHTML=`<div class="productError">${BE(err.message)}</div>`}}
function paymentNotice(){const p=new URLSearchParams(location.search).get('payment');if(p==='success'||p==='return')return '<div class="productSuccess billingNotice">付款页面已经返回，正在以支付渠道通知为准确认账单状态。若状态尚未更新，请稍后刷新。</div>';if(p==='cancelled')return '<div class="notice billingNotice">本次付款已取消，账单仍然保留，可以稍后重新支付。</div>';if(p==='failed')return '<div class="productError billingNotice">付款结果未能确认，请不要重复付款；先刷新账单状态，如仍有问题请联系管理员。</div>';return''}
function planCard(p,sub){const current=p.code===sub.plan_code,starter=p.code==='starter';return `<article class="planCard ${current?'current':''}"><small>${current?'当前套餐':'可选套餐'}</small><h3>${BE(p.name)}</h3><strong>${money(p.monthly_price_cents,p.currency)}<i>/月</i></strong><p>${BE(p.description||'')}</p><ul>${(p.features||[]).map(f=>`<li>${BE(f)}</li>`).join('')}</ul>${current&&starter?'<button disabled>当前套餐</button>':`<button data-plan="${BE(p.code)}" data-type="${current?'renewal':starter?'purchase':'upgrade'}">${current?'续费':'选择套餐'}</button>`}</article>`}
function invoiceCard(i){const payable=['pending','overdue'].includes(i.status)&&Number(i.amount_cents)>0;return `<article class="invoiceCard"><div class="invoiceMain"><div class="invoiceTitle"><b>${BE(i.invoice_number)}</b><span class="productStatus">${BE(statusName[i.status]||i.status)}</span></div><div class="invoiceMeta"><span>${BE(i.plan_name)}</span><span>${BE(typeName[i.invoice_type]||i.invoice_type)}</span><span>开具于 ${fmtDate(i.created_at)}</span>${i.due_at?`<span>支付期限 ${fmtDate(i.due_at)}</span>`:''}</div></div><strong class="invoiceAmount">${money(i.amount_cents,i.currency)}</strong><div class="invoiceActions">${payable?`<button class="primary" data-pay-invoice="${Number(i.id)}">立即支付</button>`:''}<button data-download-invoice="${Number(i.id)}" data-invoice-number="${BE(i.invoice_number)}">下载账单</button></div></article>`}
function wire(sub,invoices){if(BQ('#billingCancellation'))BQ('#billingCancellation').onclick=()=>toggleCancellation(!sub.cancel_at_period_end);BQA('[data-plan]').forEach(b=>b.onclick=()=>requestInvoice(b.dataset.plan,b.dataset.type));BQA('[data-pay-invoice]').forEach(b=>b.onclick=()=>choosePayment(Number(b.dataset.payInvoice)));BQA('[data-download-invoice]').forEach(b=>b.onclick=()=>downloadPDF(Number(b.dataset.downloadInvoice),b.dataset.invoiceNumber))}
async function requestInvoice(planCode,type){const title=type==='renewal'?'确认续费':'确认选择套餐',d=modal(title,`<form id="invoiceRequestForm"><p>确认后会生成一张待支付账单。套餐会在账单支付成功后生效。</p><div data-error></div><div class="productModalFoot"><button type="button" data-cancel>取消</button><button class="primary">生成账单</button></div></form>`);d.layer.querySelector('[data-cancel]').onclick=d.close;d.layer.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await api(`/api/workspaces/${state.workspace}/billing/invoices`,{method:'POST',body:JSON.stringify({plan_code:planCode,type})});d.close();await load()}catch(err){d.layer.querySelector('[data-error]').innerHTML=`<div class="productError">${BE(err.message)}</div>`}}}
async function choosePayment(invoiceID){const d=modal('选择支付方式','<div id="paymentMethods" class="productLoading">正在读取可用支付方式…</div>');try{const methods=(await api(`/api/workspaces/${state.workspace}/billing/payment-methods`)).data||[];const host=d.layer.querySelector('#paymentMethods');host.innerHTML=methods.length?`<div class="paymentMethodList">${methods.map(m=>`<button data-provider="${BE(m.code)}"><span class="paymentMark">${paymentMark(m.code)}</span><span><b>${BE(m.name||providerName[m.code])}</b><small>${m.mode==='qr'?'扫码完成付款':'进入付款页面完成支付'}</small></span><i>›</i></button>`).join('')}</div>`:'<div class="billingEmpty">当前没有可用的在线支付方式，请联系管理员。</div>';host.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>startPayment(invoiceID,b.dataset.provider,d))}catch(err){d.layer.querySelector('#paymentMethods').innerHTML=`<div class="productError">${BE(err.message)}</div>`}}
function paymentMark(code){return({alipay:'支',wechat:'微',epay:'易',paypal:'P',stripe:'S'})[code]||'付'}
async function startPayment(invoiceID,provider,d){const host=d.layer.querySelector('#paymentMethods');host.innerHTML='<div class="productLoading">正在创建支付订单…</div>';try{const checkout=await api(`/api/workspaces/${state.workspace}/billing/invoices/${invoiceID}/pay`,{method:'POST',body:JSON.stringify({provider})});if(checkout.mode==='qr'&&checkout.transaction_id){host.innerHTML=`<div class="qrPayment"><h3>${BE(checkout.provider_name||providerName[provider])}</h3><p>请使用对应应用扫描二维码完成付款。</p><div class="paymentQR"><span>正在生成二维码…</span></div><b>等待支付确认</b><small>付款完成后本页会自动更新账单状态。</small></div>`;await loadPaymentQR(checkout.transaction_id,host.querySelector('.paymentQR'));beginPaymentPoll(invoiceID,d)}else if(checkout.redirect_url){location.assign(checkout.redirect_url)}else{throw new Error('支付渠道没有返回可用的付款入口')}}catch(err){host.innerHTML=`<div class="productError">${BE(err.message)}</div>`}}
async function loadPaymentQR(transactionID,host){const response=await fetch(`/api/workspaces/${state.workspace}/billing/payments/${transactionID}/qr.png`,{headers:{Authorization:`Bearer ${state.token}`}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'无法加载支付二维码');const blob=await response.blob(),url=URL.createObjectURL(blob),img=new Image();img.alt='微信支付二维码';img.onload=()=>URL.revokeObjectURL(url);img.src=url;host.innerHTML='';host.appendChild(img)}
function beginPaymentPoll(invoiceID,d){clearInterval(paymentPoll);let count=0;paymentPoll=setInterval(async()=>{if(++count>60){clearInterval(paymentPoll);paymentPoll=null;return}try{const fresh=await api(`/api/workspaces/${state.workspace}/billing`),invoice=(fresh.invoices||[]).find(x=>Number(x.id)===Number(invoiceID));if(invoice?.status==='paid'){clearInterval(paymentPoll);paymentPoll=null;d.close();await load()}}catch{}},3000)}
async function downloadPDF(invoiceID,number){try{const response=await fetch(`/api/workspaces/${state.workspace}/billing/invoices/${invoiceID}/pdf`,{headers:{Authorization:`Bearer ${state.token}`}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'无法下载账单');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`GoJet-${number||'账单'}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(err){modal('下载失败',`<div class="productError">${BE(err.message)}</div>`)}}
async function toggleCancellation(cancel){const d=modal(cancel?'到期后取消':'继续订阅',`<form><p>${cancel?'当前周期结束前仍可继续使用，周期结束后不再续订。':'恢复后会保留当前订阅，并可继续正常续费。'}</p><div data-error></div><div class="productModalFoot"><button type="button" data-cancel>取消</button><button class="primary">确认</button></div></form>`);d.layer.querySelector('[data-cancel]').onclick=d.close;d.layer.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await api(`/api/workspaces/${state.workspace}/billing/cancellation`,{method:'PATCH',body:JSON.stringify({cancel})});d.close();await load()}catch(err){d.layer.querySelector('[data-error]').innerHTML=`<div class="productError">${BE(err.message)}</div>`}}}
window.GoJetPages=window.GoJetPages||{};window.GoJetPages.billing=render;
})();