(()=>{
const DQ=s=>document.querySelector(s),DE=v=>escapeHTML(v??'');let domainsCache=[];
function dnsCard(record){if(!record)return'';return `<div class="dnsRecordCard"><div><small>记录类型</small><b>${DE(record.type)}</b></div><div><small>主机记录</small><code>${DE(record.name)}</code><button onclick="gojetCopy('${String(record.name).replace(/'/g,"\\'")}',this)">复制</button></div><div><small>记录值</small><code>${DE(record.value)}</code><button onclick="gojetCopy('${String(record.value).replace(/'/g,"\\'")}',this)">复制</button></div><p>在域名的 DNS 管理中添加这条 TXT 记录，等待解析生效后再点击“立即验证”。如果重新生成验证记录，旧记录会立即失效。</p></div>`}
function status(v){return v==='active'?'<span class="domainDot ok"></span>正常':v==='pending'?'<span class="domainDot pending"></span>等待验证':'<span class="domainDot bad"></span>异常'}
async function render(){const c=DQ('.content');c.innerHTML=`<div class="productPageHead"><div><h1>自定义域名</h1><p>验证域名所有权并确认 HTTPS 可用后，就可以使用自己的域名创建短链接。</p></div><button class="primary productPrimary" onclick="openDomainCreator()">添加域名</button></div><div id="domainCreatePanel"></div><div id="domainHardeningList" class="productLoading">正在加载域名…</div>`;await load()}
async function load(){try{domainsCache=(await api(`/api/workspaces/${state.workspace}/domains`)).data||[];DQ('#domainHardeningList').innerHTML=domainsCache.length?`<div class="domainStack">${domainsCache.map(x=>{const id=Number(x.ID??x.id),host=x.Hostname??x.hostname,s=x.Status??x.status,h=x.HTTPSStatus??x.https_status,err=x.last_error??x.LastError??'';return `<article class="domainCard"><div class="domainHost"><div class="domainIcon">⌁</div><div><h2>${DE(host)}</h2><div class="domainStates"><span>域名解析 ${status(s)}</span><span>HTTPS ${status(h)}</span></div></div></div><div class="domainInfo"><div><small>最后检查</small><b>${x.last_checked_at??x.LastCheckedAt?date(x.last_checked_at??x.LastCheckedAt):'尚未检查'}</b></div><div><small>可用于短链接</small><b>${s==='active'&&h==='active'?'可以':'暂不可用'}</b></div></div>${err?`<div class="domainError">${DE(err)}</div>`:''}<div class="resourceActions"><button onclick="verifyDomainHardening(${id})">立即验证</button>${s!=='active'||h!=='active'?`<button onclick="rotateDomainHardening(${id})">重新生成验证记录</button>`:''}${s==='active'&&h==='active'?`<button onclick="gojetCopy('${String('https://'+host).replace(/'/g,"\\'")}',this)">复制域名</button>`:''}</div></article>`}).join('')}</div>`:`<div class="productEmpty"><div class="emptyIcon">⌁</div><h3>还没有自定义域名</h3><p>添加域名后，按照提示完成所有权验证和 HTTPS 检查，即可用于短链接。</p><button class="primary" onclick="openDomainCreator()">添加域名</button></div>`}catch(e){DQ('#domainHardeningList').innerHTML=`<div class="productError">${DE(e.message)}</div>`}}
window.openDomainCreator=()=>{DQ('#domainCreatePanel').innerHTML=`<section class="domainCreator"><div class="composerTop"><div><span class="eyebrow">添加域名</span><h2>添加自定义域名</h2></div><button onclick="document.querySelector('#domainCreatePanel').innerHTML=''">关闭</button></div><form id="domainCreatorForm"><label>域名<input name="hostname" placeholder="go.example.com" autocomplete="off" required></label><p>只填写域名，不要包含 https://、路径或 IP 地址。建议使用专门用于短链接的子域名。</p><div id="domainCreatorError"></div><button class="primary productPrimary">生成验证记录</button></form></section>`;DQ('#domainCreatorForm').onsubmit=async e=>{e.preventDefault();const hostname=new FormData(e.currentTarget).get('hostname').trim();try{const d=await api(`/api/workspaces/${state.workspace}/domains`,{method:'POST',body:JSON.stringify({hostname})});DQ('#domainCreatePanel').innerHTML=`<section class="domainCreator"><div class="composerTop"><div><span class="eyebrow">域名所有权验证</span><h2>${DE(hostname)}</h2></div></div>${dnsCard(d.dns_record)}<div class="resourceActions"><button class="primary" onclick="verifyDomainHardening(${Number(d.domain?.ID??d.domain?.id)})">我已添加，立即验证</button><button onclick="document.querySelector('#domainCreatePanel').innerHTML=''">稍后处理</button></div></section>`;await load()}catch(err){DQ('#domainCreatorError').innerHTML=`<div class="productError">${DE(err.message)}</div>`}}};
window.rotateDomainHardening=async id=>{try{const d=await api(`/api/workspaces/${state.workspace}/domains/${id}/verify?rotate=1`,{method:'POST',body:'{}'});DQ('#domainCreatePanel').innerHTML=`<section class="domainCreator"><div class="composerTop"><div><span class="eyebrow">新的验证记录</span><h2>${DE(d.domain?.Hostname??d.domain?.hostname)}</h2></div><button onclick="document.querySelector('#domainCreatePanel').innerHTML=''">关闭</button></div>${dnsCard(d.dns_record)}<div class="resourceActions"><button class="primary" onclick="verifyDomainHardening(${id})">立即验证</button></div></section>`;await load()}catch(e){if(window.gojetMessage)await window.gojetMessage('无法生成验证记录',e.message);else alert(e.message)}};
window.verifyDomainHardening=async id=>{try{await api(`/api/workspaces/${state.workspace}/domains/${id}/verify`,{method:'POST',body:'{}'});await load();const x=domainsCache.find(v=>Number(v.ID??v.id)===Number(id));if((x?.Status??x?.status)==='active'&&(x?.HTTPSStatus??x?.https_status)==='active'){if(window.gojetMessage)await window.gojetMessage('验证成功','域名解析和 HTTPS 检查均已通过，现在可以使用这个域名创建短链接。');else alert('验证成功')}}catch(e){await load();if(window.gojetMessage)await window.gojetMessage('验证未通过',e.message);else alert(e.message)}};
window.GoJetPages=window.GoJetPages||{};window.GoJetPages.domains=render;
})();