(()=>{
const LQ=s=>document.querySelector(s),LE=v=>escapeHTML(v??''),LO=()=>location.origin.replace(/\/$/,'');
const publicURL=l=>{const c=l.Code??l.code??'',d=l.Domain??l.domain??'';return d?`https://${d}/${encodeURIComponent(c)}`:`${LO()}/${encodeURIComponent(c)}`};
function linkOverlay(){let layer=LQ('#linkEditorLayer');if(!layer){layer=document.createElement('div');layer.id='linkEditorLayer';layer.className='productModalLayer hidden';layer.innerHTML='<div class="productModal" id="linkEditorModal"></div>';document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target===layer)closeLinkEditor()})}return layer}
window.closeLinkEditor=()=>linkOverlay().classList.add('hidden');
function dtLocal(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.valueOf()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
async function domains(){try{return (await api(`/api/workspaces/${state.workspace}/domains`)).data||[]}catch{return[]}}
async function openEditor(id=0){
 const layer=linkOverlay(),modal=LQ('#linkEditorModal'),ds=await domains();let item={Code:'',Domain:'',Destination:'',Title:'',RedirectStatus:302,Status:'active',OneTime:false};if(id)item=await api(`/api/workspaces/${state.workspace}/links/${id}`);
 const currentDomain=item.Domain??item.domain??'';
 modal.innerHTML=`<div class="productModalHead"><div><span class="eyebrow">${id?'修改链接':'新建链接'}</span><h2>${id?'编辑短链接':'创建短链接'}</h2><p>${id?'保存后，原短网址保持不变并使用新的跳转设置。':'填写目标网址后即可得到一个可以直接复制和分享的短网址。'}</p></div><button type="button" onclick="closeLinkEditor()">×</button></div><form id="linkEditorForm"><div class="productFormGrid"><label class="full">目标网址<input name="destination" type="url" value="${LE(item.Destination??item.destination??'')}" placeholder="https://example.com/page" required></label><label>链接名称<input name="title" value="${LE(item.Title??item.title??'')}" maxlength="255" placeholder="方便自己识别"></label><label>自定义短码<input name="code" value="${LE(item.Code??item.code??'')}" ${id?'readonly':''} placeholder="留空自动生成"></label><label>短链域名<select name="domain"><option value="">默认域名</option>${ds.filter(x=>(x.status==='active'||x.Status==='active')&&(x.https_status==='active'||x.HTTPSStatus==='active')).map(x=>{const h=x.hostname??x.Hostname;return `<option value="${LE(h)}" ${h===currentDomain?'selected':''}>${LE(h)}</option>`}).join('')}</select></label><label>跳转方式<select name="redirect_status">${[302,301,307,308].map(v=>`<option value="${v}" ${Number(item.RedirectStatus??item.redirect_status??302)===v?'selected':''}>${v} · ${v===301||v===308?'永久':'临时'}跳转</option>`).join('')}</select></label><label>链接状态<select name="status"><option value="active" ${(item.Status??item.status)==='active'?'selected':''}>正常使用</option><option value="paused" ${(item.Status??item.status)==='paused'?'selected':''}>暂停使用</option></select></label><label>有效期<input name="expires_at" type="datetime-local" value="${LE(dtLocal(item.ExpiresAt??item.expires_at))}"></label><label>访问次数上限<input name="max_clicks" type="number" min="1" value="${LE(item.MaxClicks??item.max_clicks??'')}" placeholder="不限制"></label><label>访问密码<input name="password" type="password" minlength="6" placeholder="${id?'留空保持现有密码':'可选，至少 6 位'}"></label><label class="productCheck"><input name="one_time" type="checkbox" ${(item.OneTime??item.one_time)?'checked':''}>仅允许访问一次</label>${id?'<label class="productCheck"><input name="clear_password" type="checkbox">清除现有访问密码</label>':''}</div><div id="linkEditorError"></div><div class="productModalFoot"><button type="button" onclick="closeLinkEditor()">取消</button><button class="primary productPrimary">${id?'保存修改':'创建短链接'}</button></div></form>`;
 layer.classList.remove('hidden');
 LQ('#linkEditorForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const expires=f.expires_at?new Date(f.expires_at).toISOString():null;try{let saved;if(id){const next={...item,Destination:f.destination,Title:f.title,Domain:f.domain,RedirectStatus:Number(f.redirect_status),Status:f.status,OneTime:f.one_time==='on',ClearPassword:f.clear_password==='on',ExpiresAt:expires,MaxClicks:f.max_clicks?Number(f.max_clicks):null};if(f.password)next.Password=f.password;saved=await api(`/api/workspaces/${state.workspace}/links/${id}`,{method:'PUT',body:JSON.stringify({link:next,reason:''})})}else{saved=await api(`/api/workspaces/${state.workspace}/links`,{method:'POST',body:JSON.stringify({destination:f.destination,title:f.title,code:f.code,domain:f.domain,redirect_status:Number(f.redirect_status),one_time:f.one_time==='on',expires_at:expires,max_clicks:f.max_clicks?Number(f.max_clicks):null,password:f.password||''})})}const url=publicURL(saved);modal.innerHTML=`<div class="productModalHead"><div><span class="eyebrow">${id?'修改完成':'创建完成'}</span><h2>${id?'短链接已更新':'短链接已经可以分享'}</h2><p>${id?'保存的设置已经生效。':'复制下面的完整短网址即可分享。'}</p></div><button type="button" onclick="closeLinkEditor()">×</button></div><div class="createdLinkResult"><div class="createdLinkURL"><small>短网址</small><a href="${LE(url)}" target="_blank" rel="noopener">${LE(url)}</a></div><div class="resourceActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制短网址</button><a class="button" href="${LE(url)}" target="_blank">打开链接</a><button onclick="closeLinkEditor();gojetOpenQR(${Number(saved.ID??saved.id)})">生成二维码</button></div></div><div class="productModalFoot"><button class="primary productPrimary" onclick="closeLinkEditor();GoJetPages.links()">完成</button></div>`;setTimeout(()=>window.GoJetPages.links(),100)}catch(err){LQ('#linkEditorError').innerHTML=`<div class="productError">${LE(err.message)}</div>`}};
}
window.openLinkEditor=openEditor;
window.editProductLink=id=>openEditor(id);

async function render(){
 const c=LQ('.content');c.innerHTML=`<div class="productPageHead"><div><h1>短链接</h1><p>集中查看和管理短网址，可以直接复制、打开、生成二维码或查看访问分析。</p></div><button class="primary productPrimary" onclick="openLinkEditor()">创建短链接</button></div><div id="lhLinks" class="productLoading">正在加载链接…</div>`;
 try{const result=await api(`/api/workspaces/${state.workspace}/links?limit=100&offset=0`),items=result.data||[];state.links=items;LQ('#lhLinks').innerHTML=items.length?`<div class="resourceStack">${items.map(l=>{const url=publicURL(l),id=Number(l.ID??l.id),title=(l.Title??l.title)||'未命名链接',dest=l.Destination??l.destination??'',status=l.Status??l.status??'',code=l.Code??l.code??'';return `<article class="shareCard"><div class="shareCardMain"><div class="resourceIcon">↗</div><div class="resourceCopy"><div class="resourceTitleRow"><h2>${LE(title)}</h2><span class="productStatus status-${LE(status)}">${status==='active'?'正常使用':status==='paused'?'已暂停':LE(status)}</span></div><div class="shareLine"><div><small>短网址</small><a href="${LE(url)}" target="_blank">${LE(url)}</a></div><div class="shareActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制</button><a class="button" href="${LE(url)}" target="_blank">打开</a></div></div><p class="destinationText">${LE(dest)}</p><div class="miniMeta"><span>${Number(l.Clicks??l.clicks??0).toLocaleString()} 次访问</span><span>${Number(l.Visitors??l.visitors??0).toLocaleString()} 位访客</span><span>${date(l.CreatedAt??l.created_at)}</span></div></div></div><div class="resourceActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制链接</button><a class="button" href="${LE(url)}" target="_blank">打开链接</a><button onclick="gojetOpenQR(${id})">二维码</button><button onclick="gojetOpenAnalytics(${id})">访问分析</button><button onclick="editProductLink(${id})">编辑</button></div></article>`}).join('')}</div>`:`<div class="productEmpty"><div class="emptyIcon">↗</div><h3>还没有短链接</h3><p>创建第一条短链接后，可以在这里复制、打开和管理。</p><button class="primary" onclick="openLinkEditor()">创建第一条链接</button></div>`}catch(err){LQ('#lhLinks').innerHTML=`<div class="productError">${LE(err.message)}</div>`}
}
window.GoJetPages=window.GoJetPages||{};window.GoJetPages.links=render;
})();
