(()=>{
const H=v=>escapeHTML(v??'');
const statusText={open:'待处理',customer_reply:'等待客服回复',staff_reply:'客服已回复',in_progress:'处理中',resolved:'已解决',closed:'已关闭'};
const priorityText={low:'低',normal:'普通',high:'高',urgent:'紧急'};
let activeTicket=null;
let botPolicyPromise=null;
let turnstileScriptPromise=null;
const turnstileWidgets=new Map();
async function botPolicy(){if(!botPolicyPromise)botPolicyPromise=fetch('/api/public/turnstile').then(r=>r.ok?r.json():{enabled:false}).catch(()=>({enabled:false}));return botPolicyPromise}
function loadTurnstile(){if(window.turnstile)return Promise.resolve();if(turnstileScriptPromise)return turnstileScriptPromise;turnstileScriptPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.defer=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error('人机验证组件加载失败'));document.head.appendChild(s)});return turnstileScriptPromise}
async function ensureTurnstile(surface,action,form){const policy=await botPolicy(),enabled=policy.enabled&&policy.surfaces?.[surface];if(!enabled)return null;if(!policy.site_key)throw new Error('人机验证已启用，但 Site Key 尚未配置');await loadTurnstile();let slot=form.querySelector('[data-turnstile-slot]');if(!slot){slot=document.createElement('div');slot.dataset.turnstileSlot='1';slot.style.margin='14px 0';const submit=form.querySelector('button[type="submit"]');form.insertBefore(slot,submit?.parentElement||submit||null)}let id=turnstileWidgets.get(form);if(id===undefined){id=window.turnstile.render(slot,{sitekey:policy.site_key,action,theme:'auto'});turnstileWidgets.set(form,id)}return id}
async function turnstileToken(surface,action,form){const id=await ensureTurnstile(surface,action,form);if(id===null)return'';const token=window.turnstile.getResponse(id);if(!token)throw new Error('请先完成人机验证');return token}
function resetTurnstile(form){const id=turnstileWidgets.get(form);if(id!==undefined&&window.turnstile)window.turnstile.reset(id)}
function ticketStatus(v){return `<span class="state ${H(v)}">${H(statusText[v]||v)}</span>`}
async function renderTickets(){activeTicket=null;const [tickets,depts]=await Promise.all([api('/api/support/tickets'),api('/api/support/departments')]);const content=document.querySelector('.content');content.innerHTML=`<div class="productPageHead"><div><h1>支持工单</h1><p>向 GoJet 支持团队提交问题，并在同一条会话中持续跟进。</p></div><button class="primary" id="newTicket">新建工单</button></div><div class="settingsGrid"><section class="resourceForm" style="grid-column:1/-1"><h3>我的工单</h3><div class="tableWrap"><table><thead><tr><th>工单号</th><th>主题</th><th>部门</th><th>优先级</th><th>状态</th><th>最后回复</th></tr></thead><tbody>${(tickets.data||[]).map(t=>`<tr data-ticket-id="${t.id}" style="cursor:pointer"><td><b>${H(t.ticket_number)}</b></td><td>${H(t.subject)}</td><td>${H(t.department_name)}</td><td>${H(priorityText[t.priority]||t.priority)}</td><td>${ticketStatus(t.status)}</td><td>${new Date(t.last_reply_at).toLocaleString('zh-CN')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty"><b>还没有支持工单</b><span>遇到问题时可以创建工单联系支持团队。</span></div></td></tr>'}</tbody></table></div></section></div>`;content.querySelector('#newTicket').onclick=()=>renderNewTicket(depts.data||[]);content.querySelectorAll('[data-ticket-id]').forEach(row=>row.onclick=()=>renderTicketDetail(Number(row.dataset.ticketId)))}
function renderNewTicket(departments){const content=document.querySelector('.content');content.innerHTML=`<div class="productPageHead"><div><h1>新建支持工单</h1><p>请尽量描述出现问题的操作、时间和预期结果。</p></div><button id="backTickets">返回工单列表</button></div><form id="ticketCreateForm" class="resourceForm"><div class="grid"><label>支持部门<select name="department_id" required>${departments.map(d=>`<option value="${d.id}">${H(d.name)}</option>`).join('')}</select></label><label>优先级<select name="priority"><option value="normal">普通</option><option value="low">低</option><option value="high">高</option><option value="urgent">紧急</option></select></label></div><label>主题<input name="subject" maxlength="220" required placeholder="简要说明需要协助的问题"></label><label>问题描述<textarea name="message" rows="10" maxlength="50000" required placeholder="请写明发生了什么、如何复现，以及你希望获得什么帮助。"></textarea></label><div id="ticketCreateError" class="error"></div><footer><button type="button" id="cancelTicket">取消</button><button class="primary" type="submit">提交工单</button></footer></form>`;content.querySelector('#backTickets').onclick=renderTickets;content.querySelector('#cancelTicket').onclick=renderTickets;const form=content.querySelector('#ticketCreateForm');ensureTurnstile('ticket_create','support_ticket_create',form).catch(err=>content.querySelector('#ticketCreateError').textContent=err.message);form.onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(form));payload.department_id=Number(payload.department_id);try{payload.turnstile_token=await turnstileToken('ticket_create','support_ticket_create',form);const created=await api('/api/support/tickets',{method:'POST',body:JSON.stringify(payload)});await renderTicketDetail(created.id)}catch(err){content.querySelector('#ticketCreateError').textContent=err.message;resetTurnstile(form)}}}
async function renderTicketDetail(id){const d=await api(`/api/support/tickets/${id}`),t=d.ticket;activeTicket=t;const content=document.querySelector('.content');content.innerHTML=`<div class="productPageHead"><div><h1>${H(t.ticket_number)} · ${H(t.subject)}</h1><p>${H(t.department_name)} · ${H(priorityText[t.priority]||t.priority)} · ${H(statusText[t.status]||t.status)}</p></div><div><button id="backTickets">返回列表</button> <button id="toggleTicket">${t.status==='closed'?'重新打开':'关闭工单'}</button></div></div><section class="resourceForm"><h3>工单对话</h3><div id="ticketMessages">${(d.messages||[]).map(m=>`<article class="panel" style="margin:12px 0"><div class="panel-body"><div style="display:flex;justify-content:space-between;gap:12px"><b>${m.author_type==='administrator'?'GoJet 支持':'我'} · ${H(m.author_name)}</b><small>${new Date(m.created_at).toLocaleString('zh-CN')}</small></div><p style="white-space:pre-wrap">${H(m.body)}</p></div></article>`).join('')}</div>${t.status==='closed'?'':`<form id="ticketReplyForm"><label>继续回复<textarea name="message" rows="7" maxlength="50000" required></textarea></label><div id="ticketReplyError" class="error"></div><footer><button class="primary" type="submit">发送回复</button></footer></form>`}</section>`;content.querySelector('#backTickets').onclick=renderTickets;content.querySelector('#toggleTicket').onclick=async()=>{await api(`/api/support/tickets/${id}/state`,{method:'PATCH',body:JSON.stringify({action:t.status==='closed'?'reopen':'close'})});await renderTicketDetail(id)};const form=content.querySelector('#ticketReplyForm');if(form){ensureTurnstile('ticket_reply','support_ticket_reply',form).catch(err=>content.querySelector('#ticketReplyError').textContent=err.message);form.onsubmit=async e=>{e.preventDefault();try{const payload={message:new FormData(form).get('message'),turnstile_token:await turnstileToken('ticket_reply','support_ticket_reply',form)};await api(`/api/support/tickets/${id}/replies`,{method:'POST',body:JSON.stringify(payload)});await renderTicketDetail(id)}catch(err){content.querySelector('#ticketReplyError').textContent=err.message;resetTurnstile(form)}}}}
window.GoJetSupport={renderTickets};
window.GoJetProductHardening=window.GoJetProductHardening||{};
window.GoJetProductHardening.tickets=renderTickets;
})();
