(()=>{
const original=window.renderSettings;if(typeof original!=='function')return;
const h=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const providerNotes={github:'GitHub OAuth Web Application。',google:'Google OAuth / OpenID Connect Web Application。',facebook:'Facebook Login Web OAuth。首次使用若无法取得可验证邮箱，需要先登录现有 GoJet 账户后绑定。',qq:'QQ 互联网站应用 OAuth2.0。QQ 无法提供已验证邮箱时，需要先登录现有账户后绑定。',wechat:'微信开放平台网站应用扫码登录。微信不提供已验证邮箱时，需要先登录现有账户后绑定。',rainbow:'聚合登录适配器。凭据只需要接口地址、APPID 和 APPKEY；客户看到的名称和允许使用的聚合方式由这里统一决定。'};
const credentialLabels={google:['Client ID','Client Secret'],facebook:['App ID','App Secret'],github:['Client ID','Client Secret'],qq:['APP ID','APP Key'],wechat:['AppID','AppSecret'],rainbow:['APPID','APPKEY']};
let socialAuthRenderPromise=null;
window.renderSettings=async function(){const requested=sessionStorage.getItem('gojet_settings_tab');await original();installSocialAuthSettings(requested==='socialauth')};
function installSocialAuthSettings(openRequested){const nav=document.querySelector('.ah-settings-nav'),main=document.querySelector('.ah-settings-main');if(!nav||!main||nav.querySelector('[data-socialauth-tab]'))return;const button=document.createElement('button');button.type='button';button.dataset.ahTab='socialauth';button.dataset.socialauthTab='1';button.innerHTML='<b>客户快捷登录</b><small>仅客户注册与登录使用</small>';const brand=nav.querySelector('[data-ah-tab="brand"]');if(brand)nav.insertBefore(button,brand);else nav.appendChild(button);const pane=document.createElement('section');pane.className='ah-settings-pane hidden';pane.dataset.ahPane='socialauth';pane.dataset.socialauthPane='1';main.appendChild(pane);button.addEventListener('click',()=>openSocialAuthSettings());if(openRequested)void openSocialAuthSettings()}
async function openSocialAuthSettings(){sessionStorage.setItem('gojet_settings_tab','socialauth');document.querySelectorAll('[data-ah-tab]').forEach(el=>el.classList.toggle('active',el.dataset.ahTab==='socialauth'));document.querySelectorAll('[data-ah-pane]').forEach(el=>el.classList.toggle('hidden',el.dataset.ahPane!=='socialauth'));await renderSocialAuthPane()}
function renderSocialAuthPane(){if(socialAuthRenderPromise)return socialAuthRenderPromise;socialAuthRenderPromise=(async()=>{const pane=document.querySelector('[data-socialauth-pane]');if(!pane)return;pane.innerHTML='<div class="socialAuthLoading">正在读取客户快捷登录配置…</div>';try{const [settings,status]=await Promise.all([api('/api/admin/settings'),api('/api/admin/auth/providers')]);const social=settings.socialauth||{},providers=status.providers||[];pane.innerHTML=`<form data-socialauth-form><div class="ah-pane-head"><div><h2>客户快捷登录</h2><p>只配置客户注册、登录与账户绑定使用的第三方身份。<strong>管理员登录始终独立</strong>，不会启用这些入口。</p></div><button class="btn primary" type="submit">保存设置</button></div><div class="socialAuthNotice">先选择需要启用的登录服务，再完成对应开放平台凭据。只有“已启用 + 配置完整”的服务才会出现在客户账户页；敏感密钥保存后不会回显。</div>${providerPicker(providers,social)}<div class="socialAuthProviders">${providers.map(p=>providerCard(p,social)).join('')}</div><div class="socialAuthEmpty" data-socialauth-empty>尚未选择快捷登录方式。</div><div class="ah-save-result" data-socialauth-result></div></form>`;bindProviderPicker(pane);bindCallbackCopy(pane);pane.querySelector('[data-socialauth-form]').addEventListener('submit',saveSocialAuthSettings)}catch(err){pane.innerHTML=`<div class="alert">${h(err.message)}</div>`;if(typeof fail==='function')fail(err.message)}})().finally(()=>{socialAuthRenderPromise=null});return socialAuthRenderPromise}
function providerPicker(providers,social){const selected=providers.filter(p=>Boolean(social[`auth.social.${p.id}.enabled`]));return `<details class="socialAuthPicker" data-socialauth-picker><summary><span><b>启用的快捷登录</b><small data-socialauth-picker-summary>${selected.length?`已选择 ${selected.length} 个服务`:'未选择快捷登录'}</small></span><i aria-hidden="true"></i></summary><div class="socialAuthPickerMenu">${providers.map(p=>{const name=`auth.social.${p.id}.enabled`,checked=Boolean(social[name]);return `<label class="socialAuthPickerOption"><input type="checkbox" name="${h(name)}" data-social-enable="${h(p.id)}" ${checked?'checked':''}><span><b>${h(p.label)}</b><small>${p.configured?'配置已保存':'需要配置应用凭据'}</small></span></label>`}).join('')}</div></details>`}
function providerCard(provider,social){const prefix=`auth.social.${provider.id}.`,secretConfigured=social[prefix+'client_secret']==='********',enabled=Boolean(social[prefix+'enabled']),clientID=social[prefix+'client_id']||'',baseURL=social[prefix+'base_url']||'',labels=credentialLabels[provider.id]||['Client ID','Client Secret'];const config=provider.configured?'<span class="socialAuthBadge ok">配置完整</span>':'<span class="socialAuthBadge muted">配置未完整</span>';const visible=provider.visible?'<span class="socialAuthBadge live">客户前台可用</span>':'<span class="socialAuthBadge muted">客户前台不展示</span>';const rainbowFields=provider.id==='rainbow'?rainbowControls(provider,social,prefix,baseURL):'';const callback=provider.id==='rainbow'?'':callbackInfo(provider);return `<details class="paymentProvider socialAuthProvider${enabled?'':' hidden'}" data-social-provider="${h(provider.id)}" open><summary><div class="paymentProviderHead"><div><h3>${h(provider.id==='rainbow'?(provider.display_name||provider.label):provider.label)}</h3><p>${h(providerNotes[provider.id]||'客户快捷登录提供方')}</p></div><div class="socialAuthBadges">${config}${visible}</div></div></summary><div class="ah-settings-grid socialAuthProviderBody">${rainbowFields}${provider.id!=='rainbow'?'': ''}${field(prefix+'client_id',labels[0],clientID)}${secret(prefix+'client_secret',labels[1],secretConfigured)}${callback}</div></details>`}
function rainbowControls(provider,social,prefix,baseURL){const display=social[prefix+'display_name']||provider.display_name||'聚合登录';const saved=normaliseSelectedTypes(social[prefix+'login_types'],provider.login_types);const available=Array.isArray(provider.available_login_types)?provider.available_login_types:[];return `${field(prefix+'display_name','前台显示名称',display,'text','例如：快捷登录')} ${field(prefix+'base_url','接口地址',baseURL,'url','例如：https://auth.example.com/connect.php')}<div class="full socialAuthMethodSelector"><div class="socialAuthMethodHead"><div><b>允许客户使用的聚合方式</b><small>只勾选你准备开放的方式。前台只展示这里选中的项目，不再显示完整聚合服务列表。</small></div><span data-rainbow-count>${saved.length} 个</span></div><div class="socialAuthMethodGrid">${available.map(item=>`<label class="socialAuthMethod"><input type="checkbox" data-rainbow-type value="${h(item.id)}" ${saved.includes(item.id)?'checked':''}><span>${h(item.label)}</span></label>`).join('')}</div></div>`}
function normaliseSelectedTypes(raw,fallback=[]){let values=[];if(Array.isArray(raw))values=raw;else if(typeof raw==='string'){try{const parsed=JSON.parse(raw);values=Array.isArray(parsed)?parsed:raw.split(',')}catch{values=raw.split(',')}}if(!values.length&&Array.isArray(fallback))values=fallback.map(x=>x.id||x);return [...new Set(values.map(x=>String(x).trim()).filter(Boolean))]}
function callbackInfo(provider){const callback=provider.callback_url||'';if(!callback)return'';return `<div class="full socialAuthCallbackInfo"><div><b>开放平台回调地址</b><small>这个地址不用填回 GoJet，只需要复制到 ${h(provider.label)} 开放平台的回调 / Redirect URI 配置。</small><code>${h(callback)}</code></div><button class="btn" type="button" data-copy-social-callback="${h(callback)}">复制</button></div>`}
function bindProviderPicker(pane){const inputs=[...pane.querySelectorAll('[data-social-enable]')],empty=pane.querySelector('[data-socialauth-empty]'),summary=pane.querySelector('[data-socialauth-picker-summary]');const sync=()=>{let count=0;inputs.forEach(input=>{const card=pane.querySelector(`[data-social-provider="${CSS.escape(input.dataset.socialEnable)}"]`);card?.classList.toggle('hidden',!input.checked);if(input.checked)count++});if(summary)summary.textContent=count?`已选择 ${count} 个服务`:'未选择快捷登录';empty?.classList.toggle('hidden',count>0)};inputs.forEach(input=>input.addEventListener('change',sync));pane.querySelectorAll('[data-rainbow-type]').forEach(input=>input.addEventListener('change',()=>{const count=pane.querySelectorAll('[data-rainbow-type]:checked').length;const badge=pane.querySelector('[data-rainbow-count]');if(badge)badge.textContent=`${count} 个`}));sync()}
function bindCallbackCopy(pane){pane.querySelectorAll('[data-copy-social-callback]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copySocialCallback||'');if(typeof toast==='function')toast('回调地址已复制')}catch(_){if(typeof fail==='function')fail('复制失败，请手动复制回调地址')}}))}
function field(name,label,value,type='text',placeholder=''){return `<label><span>${h(label)}</span><input name="${h(name)}" type="${type}" value="${h(value)}" placeholder="${h(placeholder)}"></label>`}
function secret(name,label,configured){return `<label><span>${h(label)}</span><input name="${h(name)}" type="password" value="" autocomplete="new-password" data-sensitive="1" placeholder="${configured?'已配置，留空保持不变':'请输入密钥'}"></label>`}
async function saveSocialAuthSettings(event){event.preventDefault();const form=event.currentTarget,payload={};form.querySelectorAll('input[name],select[name],textarea[name]').forEach(el=>{if(el.dataset.sensitive==='1'&&!el.value.trim())return;payload[el.name]=el.type==='checkbox'?el.checked:el.value});if(form.querySelector('[data-social-provider="rainbow"]:not(.hidden)')){const selected=[...form.querySelectorAll('[data-rainbow-type]:checked')].map(el=>el.value);if(Boolean(form.querySelector('[data-social-enable="rainbow"]')?.checked)&&!selected.length){const result=form.querySelector('[data-socialauth-result]');if(result){result.textContent='聚合登录至少选择一种客户登录方式';result.className='ah-save-result bad'}if(typeof fail==='function')fail('聚合登录至少选择一种客户登录方式');return}payload['auth.social.rainbow.login_types']=selected}const result=form.querySelector('[data-socialauth-result]');try{await api('/api/admin/settings/socialauth',{method:'PUT',body:JSON.stringify(payload)});if(typeof toast==='function')toast('客户快捷登录设置已保存');if(result){result.textContent='已保存';result.className='ah-save-result ok'}await renderSocialAuthPane()}catch(err){if(result){result.textContent=err.message;result.className='ah-save-result bad'}if(typeof fail==='function')fail(err.message)}}
})();