(()=>{
const original=window.renderSettings;if(typeof original!=='function')return;
const h=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const providerNotes={github:'GitHub OAuth Web Application。',google:'Google OAuth / OpenID Connect Web Application。',facebook:'Facebook Login Web OAuth。首次使用若无法取得可验证邮箱，需要先登录现有 GoJet 账户后绑定。',qq:'QQ 互联网站应用 OAuth2.0。QQ 无法提供已验证邮箱时，需要先登录现有账户后绑定。',wechat:'微信开放平台网站应用扫码登录。微信不提供已验证邮箱时，需要先登录现有账户后绑定。',rainbow:'彩虹聚合登录。AppKey 只由 GoJet 服务端使用，不会进入浏览器授权地址。'};
const rainbowTypes=[['qq','QQ'],['wx','微信'],['alipay','支付宝'],['sina','微博'],['baidu','百度'],['huawei','华为'],['xiaomi','小米'],['douyin','抖音'],['bilibili','哔哩哔哩'],['dingtalk','钉钉']];
let socialAuthRenderPromise=null;
window.renderSettings=async function(){const requested=sessionStorage.getItem('gojet_settings_tab');await original();installSocialAuthSettings(requested==='socialauth')};
function installSocialAuthSettings(openRequested){const nav=document.querySelector('.ah-settings-nav'),main=document.querySelector('.ah-settings-main');if(!nav||!main||nav.querySelector('[data-socialauth-tab]'))return;const button=document.createElement('button');button.type='button';button.dataset.ahTab='socialauth';button.dataset.socialauthTab='1';button.innerHTML='<b>客户快捷登录</b><small>仅客户注册与登录使用</small>';const brand=nav.querySelector('[data-ah-tab="brand"]');if(brand)nav.insertBefore(button,brand);else nav.appendChild(button);const pane=document.createElement('section');pane.className='ah-settings-pane hidden';pane.dataset.ahPane='socialauth';pane.dataset.socialauthPane='1';main.appendChild(pane);button.addEventListener('click',()=>openSocialAuthSettings());if(openRequested)void openSocialAuthSettings()}
async function openSocialAuthSettings(){sessionStorage.setItem('gojet_settings_tab','socialauth');document.querySelectorAll('[data-ah-tab]').forEach(el=>el.classList.toggle('active',el.dataset.ahTab==='socialauth'));document.querySelectorAll('[data-ah-pane]').forEach(el=>el.classList.toggle('hidden',el.dataset.ahPane!=='socialauth'));await renderSocialAuthPane()}
function renderSocialAuthPane(){if(socialAuthRenderPromise)return socialAuthRenderPromise;socialAuthRenderPromise=(async()=>{const pane=document.querySelector('[data-socialauth-pane]');if(!pane)return;pane.innerHTML='<div class="socialAuthLoading">正在读取客户快捷登录配置…</div>';try{const [settings,status]=await Promise.all([api('/api/admin/settings'),api('/api/admin/auth/providers')]);const social=settings.socialauth||{},providers=status.providers||[];pane.innerHTML=`<form data-socialauth-form><div class="ah-pane-head"><div><h2>客户快捷登录</h2><p>配置客户注册、登录和账户绑定使用的第三方身份。<strong>管理后台不会使用这些快捷登录方式</strong>，管理员仍使用独立管理员账号与双因素认证。</p></div><button class="btn primary" type="submit">保存设置</button></div><div class="socialAuthNotice">先从下拉菜单选择需要启用的方式，再展开对应配置。只有“已选择 + 配置完整”的方式才会出现在客户登录与注册页面；密钥保存后不会回显。</div>${providerPicker(providers,social)}<div class="socialAuthProviders">${providers.map(p=>providerCard(p,social)).join('')}</div><div class="socialAuthEmpty" data-socialauth-empty>尚未选择快捷登录方式。</div><div class="ah-save-result" data-socialauth-result></div></form>`;bindProviderPicker(pane);pane.querySelector('[data-socialauth-form]').addEventListener('submit',saveSocialAuthSettings)}catch(err){pane.innerHTML=`<div class="alert">${h(err.message)}</div>`;if(typeof fail==='function')fail(err.message)}})().finally(()=>{socialAuthRenderPromise=null});return socialAuthRenderPromise}
function providerPicker(providers,social){const selected=providers.filter(p=>Boolean(social[`auth.social.${p.id}.enabled`]));return `<details class="socialAuthPicker" data-socialauth-picker><summary><span><b>启用的快捷登录</b><small data-socialauth-picker-summary>${selected.length?`已选择 ${selected.length} 个方式`:'未选择快捷登录'}</small></span><i aria-hidden="true"></i></summary><div class="socialAuthPickerMenu">${providers.map(p=>{const name=`auth.social.${p.id}.enabled`,checked=Boolean(social[name]);return `<label class="socialAuthPickerOption"><input type="checkbox" name="${h(name)}" data-social-enable="${h(p.id)}" ${checked?'checked':''}><span><b>${h(p.label)}</b><small>${p.configured?'配置已保存':'需要配置应用凭据'}</small></span></label>`}).join('')}</div></details>`}
function providerCard(provider,social){const prefix=`auth.social.${provider.id}.`,secretConfigured=social[prefix+'client_secret']==='********',enabled=Boolean(social[prefix+'enabled']),clientID=social[prefix+'client_id']||'',baseURL=social[prefix+'base_url']||'https://u.cccyun.cc',loginType=social[prefix+'login_type']||'qq';const config=provider.configured?'<span class="socialAuthBadge ok">配置完整</span>':'<span class="socialAuthBadge muted">配置未完整</span>';const visible=provider.visible?'<span class="socialAuthBadge live">客户前台可用</span>':'<span class="socialAuthBadge muted">客户前台不展示</span>';const extra=provider.id==='rainbow'?field(prefix+'base_url','服务地址',baseURL,'url')+selectField(prefix+'login_type','聚合登录方式',loginType,rainbowTypes):'';return `<details class="paymentProvider socialAuthProvider${enabled?'':' hidden'}" data-social-provider="${h(provider.id)}"><summary><div class="paymentProviderHead"><div><h3>${h(provider.label)}</h3><p>${h(providerNotes[provider.id]||'客户快捷登录提供方')}</p></div><div class="socialAuthBadges">${config}${visible}</div></div></summary><div class="ah-settings-grid socialAuthProviderBody">${field(prefix+'client_id','客户端编号 / App ID',clientID)}${secret(prefix+'client_secret','客户端密钥 / App Secret',secretConfigured)}${extra}<label class="full"><span>客户授权回调地址</span><input data-social-callback="${h(provider.id)}" value="${h(provider.callback_url||'')}" readonly><small class="settingHelp">将此地址配置到对应第三方开放平台。该地址只服务于客户快捷登录与账户绑定。</small></label></div></details>`}
function bindProviderPicker(pane){const inputs=[...pane.querySelectorAll('[data-social-enable]')],empty=pane.querySelector('[data-socialauth-empty]'),summary=pane.querySelector('[data-socialauth-picker-summary]');const sync=()=>{let count=0;inputs.forEach(input=>{const card=pane.querySelector(`[data-social-provider="${CSS.escape(input.dataset.socialEnable)}"]`);card?.classList.toggle('hidden',!input.checked);if(input.checked)count++});if(summary)summary.textContent=count?`已选择 ${count} 个方式`:'未选择快捷登录';empty?.classList.toggle('hidden',count>0)};inputs.forEach(input=>input.addEventListener('change',sync));sync()}
function field(name,label,value,type='text'){return `<label><span>${h(label)}</span><input name="${h(name)}" type="${type}" value="${h(value)}"></label>`}
function secret(name,label,configured){return `<label><span>${h(label)}</span><input name="${h(name)}" type="password" value="" autocomplete="new-password" data-sensitive="1" placeholder="${configured?'已配置，留空保持不变':'请输入密钥'}"></label>`}
function selectField(name,label,value,options){return `<label><span>${h(label)}</span><select name="${h(name)}">${options.map(([id,text])=>`<option value="${h(id)}" ${id===value?'selected':''}>${h(text)}</option>`).join('')}</select></label>`}
async function saveSocialAuthSettings(event){event.preventDefault();const form=event.currentTarget,payload={};form.querySelectorAll('input[name],select[name],textarea[name]').forEach(el=>{if(el.dataset.sensitive==='1'&&!el.value.trim())return;payload[el.name]=el.type==='checkbox'?el.checked:el.value});const result=form.querySelector('[data-socialauth-result]');try{await api('/api/admin/settings/socialauth',{method:'PUT',body:JSON.stringify(payload)});if(typeof toast==='function')toast('客户快捷登录设置已保存');if(result){result.textContent='已保存';result.className='ah-save-result ok'}await renderSocialAuthPane()}catch(err){if(result){result.textContent=err.message;result.className='ah-save-result bad'}if(typeof fail==='function')fail(err.message)}}
})();
