(()=>{
const nav=document.querySelector('#nav');
if(!nav)return;
const mailButton=nav.querySelector('[data-view="mail"]');
function addNav(view,permission,label){if(nav.querySelector(`[data-view="${view}"]`))return;const b=document.createElement('button');b.dataset.view=view;b.dataset.permission=permission;b.textContent=label;nav.insertBefore(b,mailButton||null)}
addNav('tickets','tickets.manage','客户工单');
addNav('botprotection','settings.manage','人机验证');
titles.tickets='客户工单';titles.botprotection='人机验证';permissionNames['tickets.manage']='工单管理';
const oldGeneric=renderGeneric;
renderGeneric=async function(view){if(view==='tickets')return renderSupportQueue();if(view==='botprotection')return renderBotProtection();return oldGeneric(view)};

const statusLabel={open:'待处理',customer_reply:'客户已回复',staff_reply:'客服已回复',in_progress:'处理中',resolved:'已解决',closed:'已关闭'};
const priorityLabel={low:'低',normal:'普通',high:'高',urgent:'紧急'};
function ticketState(v){return `<span class="state ${esc(v)}">${esc(statusLabel[v]||v)}</span>`}
async function renderSupportQueue(){
 const params=new URLSearchParams();const d=await api('/api/admin/support/tickets?'+params);
 const rows=(d.data||[]).map(t=>`<tr><td><b>${esc(t.ticket_number)}</b><br><small>${dt(t.created_at)}</small></td><td>${esc(t.subject)}<br><small>${esc(t.user_email||'')}</small></td><td>${esc(t.department_name)}</td><td>${esc(priorityLabel[t.priority]||t.priority)}</td><td>${ticketState(t.status)}</td><td>${dt(t.last_reply_at)}<br><small>${t.last_reply_by==='customer'?'客户':'客服'}</small></td><td><button class="btn small" data-ticket-open="${t.id}">查看</button></td></tr>`).join('');
 document.querySelector('#content').innerHTML=pageHead('客户工单','按最新回复、优先级和状态处理客户请求。WHMCS 风格的会话、内部备注与状态流转都在这里完成。','<button class="btn" id="ticketRefresh">刷新</button>')+`<div class="panel"><div class="toolbar"><input id="ticketSearch" placeholder="工单号、主题或客户邮箱"><select id="ticketStatus"><option value="">全部状态</option><option value="customer_reply">客户已回复</option><option value="open">待处理</option><option value="in_progress">处理中</option><option value="staff_reply">客服已回复</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><button class="btn" id="ticketFilter">筛选</button></div><div class="table-wrap"><table><thead><tr><th>工单</th><th>主题 / 客户</th><th>部门</th><th>优先级</th><th>状态</th><th>最后回复</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="7"><div class="empty">当前没有工单</div></td></tr>'}</tbody></table></div></div>`;
 document.querySelector('#ticketRefresh').onclick=renderSupportQueue;document.querySelector('#ticketFilter').onclick=async()=>{const q=new URLSearchParams({search:document.querySelector('#ticketSearch').value,status:document.querySelector('#ticketStatus').value});const next=await api('/api/admin/support/tickets?'+q);const body=(next.data||[]).map(t=>`<tr><td><b>${esc(t.ticket_number)}</b></td><td>${esc(t.subject)}<br><small>${esc(t.user_email||'')}</small></td><td>${esc(t.department_name)}</td><td>${esc(priorityLabel[t.priority]||t.priority)}</td><td>${ticketState(t.status)}</td><td>${dt(t.last_reply_at)}</td><td><button class="btn small" data-ticket-open="${t.id}">查看</button></td></tr>`).join('');document.querySelector('#content tbody').innerHTML=body||'<tr><td colspan="7"><div class="empty">没有符合条件的工单</div></td></tr>'}
}
document.querySelector('#content').addEventListener('click',e=>{const b=e.target.closest('[data-ticket-open]');if(b)openSupportTicket(Number(b.dataset.ticketOpen))});
async function openSupportTicket(id){try{const d=await api(`/api/admin/support/tickets/${id}`),t=d.ticket;const messages=(d.messages||[]).map(m=>`<article class="panel" style="margin:12px 0"><div class="panel-body"><div style="display:flex;justify-content:space-between;gap:12px"><b>${m.internal?'内部备注 · ':''}${esc(m.author_name)}</b><small>${dt(m.created_at)}</small></div><p style="white-space:pre-wrap">${esc(m.body)}</p></div></article>`).join('');openModal(`<div class="modal-head"><div><h2>${esc(t.ticket_number)} · ${esc(t.subject)}</h2><p>${esc(t.user_email)} · ${esc(t.department_name)} · ${esc(priorityLabel[t.priority]||t.priority)}</p></div><button class="btn" data-modal-close>关闭</button></div><div class="modal-body"><div class="toolbar"><select id="supportStatus"><option value="open">待处理</option><option value="customer_reply">客户已回复</option><option value="staff_reply">客服已回复</option><option value="in_progress">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><select id="supportPriority"><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option></select><button class="btn" id="supportUpdate">更新工单</button></div><div>${messages||'<div class="empty">暂无消息</div>'}</div><form id="supportReply"><label><span>回复内容</span><textarea name="message" rows="7" required maxlength="50000"></textarea></label><label class="check"><input name="internal" type="checkbox"> 仅管理员可见的内部备注</label><div class="modal-foot"><button class="btn blue">发送</button></div></form></div>`);document.querySelector('#supportStatus').value=t.status;document.querySelector('#supportPriority').value=t.priority;document.querySelector('#supportUpdate').onclick=async()=>{await api(`/api/admin/support/tickets/${id}`,{method:'PATCH',body:JSON.stringify({status:document.querySelector('#supportStatus').value,priority:document.querySelector('#supportPriority').value})});toast('工单状态已更新');openSupportTicket(id)};document.querySelector('#supportReply').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,body={message:new FormData(f).get('message'),internal:f.elements.internal.checked};await api(`/api/admin/support/tickets/${id}/replies`,{method:'POST',body:JSON.stringify(body)});toast(body.internal?'内部备注已保存':'回复已发送');openSupportTicket(id)}}catch(err){fail(err.message)}}

async function renderBotProtection(){const d=await api('/api/admin/bot-protection');const enabled=Boolean(d['turnstile.enabled']);const hostnames=Array.isArray(d['turnstile.allowed_hostnames'])?d['turnstile.allowed_hostnames'].join('\n'):(d['turnstile.allowed_hostnames']||'');document.querySelector('#content').innerHTML=pageHead('人机验证','统一控制 Cloudflare Turnstile。Secret Key 永远不会回传到浏览器，留空保存会保留现有密钥。')+`<form id="botProtectionForm" class="panel"><div class="panel-body form-grid"><label class="check full"><input name="turnstile.enabled" type="checkbox" ${enabled?'checked':''}> 启用 Turnstile 全局保护</label><label><span>Site Key</span><input name="turnstile.site_key" value="${esc(d['turnstile.site_key']||'')}"></label><label><span>Secret Key</span><input name="turnstile.secret" type="password" value="" autocomplete="new-password" placeholder="${d['turnstile.secret_configured']?'已配置，留空保持不变':'请输入 Secret Key'}"></label><label class="full"><span>允许的 Hostname（每行一个）</span><textarea name="turnstile.allowed_hostnames" rows="4">${esc(hostnames)}</textarea></label><label class="check full"><input name="turnstile.fail_open" type="checkbox" ${d['turnstile.fail_open']?'checked':''}> Siteverify 网络故障时临时放行（默认建议关闭）</label><h3 class="full">保护场景</h3>${[['registration','注册'],['login','登录'],['forgot_password','忘记密码'],['reset_password','重置密码'],['ticket_create','创建工单'],['ticket_reply','工单回复'],['abuse_report','滥用举报']].map(([k,l])=>`<label class="check"><input name="turnstile.${k}" type="checkbox" ${d[`turnstile.${k}`]!==false?'checked':''}> ${l}</label>`).join('')}<div class="full"><button class="btn blue">保存人机验证设置</button></div></div></form>`;document.querySelector('#botProtectionForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,payload={};for(const el of f.elements){if(!el.name)continue;payload[el.name]=el.type==='checkbox'?el.checked:el.value}if(!payload['turnstile.secret'])delete payload['turnstile.secret'];await api('/api/admin/bot-protection',{method:'PUT',body:JSON.stringify(payload)});toast('人机验证设置已保存');renderBotProtection()}}
})();
