(()=>{
const nav=document.querySelector('#nav');
if(!nav)return;
const billingButton=nav.querySelector('[data-view="billing"]');
function addNav(view,permission,label){if(nav.querySelector(`[data-view="${view}"]`))return;const b=document.createElement('button');b.dataset.view=view;b.dataset.permission=permission;b.textContent=label;nav.insertBefore(b,billingButton||null)}
addNav('tickets','tickets.manage','客户工单');
titles.tickets='客户工单';permissionNames['tickets.manage']='工单管理';
const oldGeneric=renderGeneric;renderGeneric=async function(view){if(view==='tickets')return renderSupportQueue();return oldGeneric(view)};
const statusLabel={open:'待处理',customer_reply:'客户已回复',staff_reply:'客服已回复',in_progress:'处理中',resolved:'已解决',closed:'已关闭'};
const priorityLabel={low:'低',normal:'普通',high:'高',urgent:'紧急'};
function ticketState(v){return `<span class="state ${esc(v)}">${esc(statusLabel[v]||v)}</span>`}
function customerIP(message,index){if(message.author_type!=='customer'||!message.ip_address)return'';return `<div class="ticketMessageMeta"><span>${index===0?'工单 IP':'回复 IP'}</span><code>${esc(message.ip_address)}</code></div>`}
function supportMessages(items){return (items||[]).map((m,index)=>`<article class="adminTicketMessage ${m.internal?'internal':m.author_type==='customer'?'customer':'staff'}"><div class="adminTicketMessageHead"><b>${m.internal?'内部备注 · ':''}${esc(m.author_name||(m.author_type==='customer'?'客户':'GoJet 支持团队'))}</b><small>${dt(m.created_at)}</small></div><div class="adminTicketMessageBody">${esc(m.body)}</div>${customerIP(m,index)}</article>`).join('')||'<div class="empty">暂无消息</div>'}
async function renderSupportQueue(){
 const d=await api('/api/admin/support/tickets');
 const rows=(d.data||[]).map(t=>`<tr><td><b>${esc(t.ticket_number)}</b><br><small>${dt(t.created_at)}</small></td><td><b>${esc(t.subject)}</b><br><small>${esc(t.user_email||'')}</small></td><td>${esc(t.department_name)}</td><td>${esc(priorityLabel[t.priority]||t.priority)}</td><td>${ticketState(t.status)}</td><td>${dt(t.last_reply_at)}<br><small>${t.last_reply_by==='customer'?'客户':'客服'}</small></td><td><button class="btn small" data-ticket-open="${t.id}">处理</button></td></tr>`).join('');
 document.querySelector('#content').innerHTML=pageHead('客户工单','集中处理客户咨询、回复与内部备注。','<button class="btn" id="ticketRefresh">刷新</button>')+`<div class="panel"><div class="toolbar"><input id="ticketSearch" placeholder="工单号、主题或客户邮箱"><select id="ticketStatus"><option value="">全部状态</option><option value="customer_reply">客户已回复</option><option value="open">待处理</option><option value="in_progress">处理中</option><option value="staff_reply">客服已回复</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><button class="btn" id="ticketFilter">筛选</button></div><div class="table-wrap"><table><thead><tr><th>工单</th><th>主题 / 客户</th><th>部门</th><th>优先级</th><th>状态</th><th>最后回复</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="7"><div class="empty">当前没有工单</div></td></tr>'}</tbody></table></div></div>`;
 document.querySelector('#ticketRefresh').onclick=renderSupportQueue;
 document.querySelector('#ticketFilter').onclick=async()=>{const q=new URLSearchParams({search:document.querySelector('#ticketSearch').value,status:document.querySelector('#ticketStatus').value}),next=await api('/api/admin/support/tickets?'+q);document.querySelector('#content tbody').innerHTML=(next.data||[]).map(t=>`<tr><td><b>${esc(t.ticket_number)}</b></td><td><b>${esc(t.subject)}</b><br><small>${esc(t.user_email||'')}</small></td><td>${esc(t.department_name)}</td><td>${esc(priorityLabel[t.priority]||t.priority)}</td><td>${ticketState(t.status)}</td><td>${dt(t.last_reply_at)}</td><td><button class="btn small" data-ticket-open="${t.id}">处理</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">没有符合条件的工单</div></td></tr>'}
}
document.querySelector('#content').addEventListener('click',e=>{const b=e.target.closest('[data-ticket-open]');if(b)openSupportTicket(Number(b.dataset.ticketOpen))});
async function openSupportTicket(id){
 try{
  const d=await api(`/api/admin/support/tickets/${id}`),t=d.ticket;
  document.querySelector('#content').innerHTML=`<div class="adminWorkflowHead"><div><button type="button" class="adminWorkflowBack" id="supportBack">← 返回客户工单</button><span class="eyebrow">SUPPORT TICKET</span><h2>${esc(t.ticket_number)} · ${esc(t.subject)}</h2><div class="adminTicketStatusLine">${ticketState(t.status)}<span>${esc(t.department_name)}</span><span>${esc(priorityLabel[t.priority]||t.priority)}优先级</span></div></div></div><div class="adminTicketPage"><main><section class="adminTicketThread"><div class="adminTicketTimeline">${supportMessages(d.messages)}</div></section>${t.status==='closed'?'<div class="info" style="margin-top:14px">该工单已关闭。如需继续处理，请先在右侧将状态调整为待处理或处理中。</div>':`<form id="supportReply" class="adminTicketReply"><label><span>回复客户</span><textarea name="message" rows="7" required maxlength="50000" placeholder="输入回复内容"></textarea></label><div class="adminTicketReplyFooter"><label class="adminTicketInternal"><input name="internal" type="checkbox"><span>保存为内部备注<br><small>仅管理员可见，不会发送给客户。</small></span></label><button class="btn blue">发送回复</button></div></form>`}</main><aside class="adminTicketSide"><section class="adminTicketMeta"><h3>工单信息</h3><dl><div><dt>工单号</dt><dd>${esc(t.ticket_number)}</dd></div><div><dt>客户</dt><dd>${esc(t.user_email)}</dd></div><div><dt>部门</dt><dd>${esc(t.department_name)}</dd></div><div><dt>创建时间</dt><dd>${dt(t.created_at)}</dd></div><div><dt>最后回复</dt><dd>${dt(t.last_reply_at)}</dd></div></dl></section><section class="adminTicketControls"><h3>处理设置</h3><label><span>状态</span><select id="supportStatus"><option value="open">待处理</option><option value="customer_reply">客户已回复</option><option value="staff_reply">客服已回复</option><option value="in_progress">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><label><span>优先级</span><select id="supportPriority"><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option></select></label><button class="btn blue" id="supportUpdate">保存处理设置</button></section></aside></div>`;
  document.querySelector('#supportBack').onclick=renderSupportQueue;
  document.querySelector('#supportStatus').value=t.status;document.querySelector('#supportPriority').value=t.priority;
  document.querySelector('#supportUpdate').onclick=async()=>{try{await api(`/api/admin/support/tickets/${id}`,{method:'PATCH',body:JSON.stringify({status:document.querySelector('#supportStatus').value,priority:document.querySelector('#supportPriority').value})});toast('工单处理设置已保存');await openSupportTicket(id)}catch(err){fail(err.message)}};
  const reply=document.querySelector('#supportReply');if(reply)reply.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,body={message:new FormData(f).get('message'),internal:f.elements.internal.checked};try{await api(`/api/admin/support/tickets/${id}/replies`,{method:'POST',body:JSON.stringify(body)});toast(body.internal?'内部备注已保存':'回复已发送');await openSupportTicket(id)}catch(err){fail(err.message)}}
 }catch(err){fail(err.message)}
}

async function renderBotProtectionSettings(target=null,options={}){
 const embedded=Boolean(options.embedded||target),root=target||document.querySelector('#content');if(!root)return;root.innerHTML='<div class="panel"><div class="empty">正在加载人机验证设置…</div></div>';
 const d=await api('/api/admin/bot-protection'),enabled=Boolean(d['turnstile.enabled']),hostnames=Array.isArray(d['turnstile.allowed_hostnames'])?d['turnstile.allowed_hostnames'].join('\n'):(d['turnstile.allowed_hostnames']||'');
 const heading=embedded?`<div class="ah-pane-head"><div><h2>人机验证</h2><p>统一控制 Cloudflare Turnstile 的站点密钥和保护范围。</p></div></div>`:pageHead('人机验证','统一控制 Cloudflare Turnstile 的站点密钥和保护范围。');
 root.innerHTML=heading+`<form id="botProtectionForm" class="panel"><div class="panel-body form-grid"><label class="check full"><input name="turnstile.enabled" type="checkbox" ${enabled?'checked':''}> 启用 Turnstile</label><label><span>Site Key</span><input name="turnstile.site_key" value="${esc(d['turnstile.site_key']||'')}"></label><label><span>Secret Key</span><input name="turnstile.secret" type="password" value="" autocomplete="new-password" placeholder="${d['turnstile.secret_configured']?'已配置，留空保持不变':'请输入 Secret Key'}"></label><label class="full"><span>允许的 Hostname（每行一个）</span><textarea name="turnstile.allowed_hostnames" rows="4">${esc(hostnames)}</textarea></label><label class="check full"><input name="turnstile.fail_open" type="checkbox" ${d['turnstile.fail_open']?'checked':''}> 验证服务暂时不可达时允许继续</label><h3 class="full">保护场景</h3>${[['registration','注册'],['login','登录'],['forgot_password','忘记密码'],['reset_password','重置密码'],['ticket_create','创建工单'],['ticket_reply','工单回复'],['abuse_report','滥用举报']].map(([k,l])=>`<label class="check"><input name="turnstile.${k}" type="checkbox" ${d[`turnstile.${k}`]!==false?'checked':''}> ${l}</label>`).join('')}<div class="full"><button class="btn blue">保存人机验证设置</button></div></div></form>`;
 const form=root.querySelector('#botProtectionForm');if(form)form.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,payload={};for(const el of f.elements){if(!el.name)continue;payload[el.name]=el.type==='checkbox'?el.checked:el.value}if(!payload['turnstile.secret'])delete payload['turnstile.secret'];try{await api('/api/admin/bot-protection',{method:'PUT',body:JSON.stringify(payload)});toast('人机验证设置已保存');await renderBotProtectionSettings(root,{embedded})}catch(err){fail(err.message)}}
}
window.renderBotProtectionSettings=renderBotProtectionSettings;
})();