const {test,expect}=require('@playwright/test');
const base=process.env.GOJET_SURFACE_BASE||'http://127.0.0.1:4180';

async function noOverflow(page){const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(size.scroll).toBeLessThanOrEqual(size.client+2)}

test.describe('simplified account entry surface',()=>{
  for(const [path,title] of [['/login','登录 GoJet'],['/register','创建 GoJet 账户'],['/forgotpassword','找回密码'],['/resetpassword?token=surface-test','设置新密码'],['/verifyemail?token=surface-test','验证邮箱']]){
    test(`${path} stays focused and compact`,async({page})=>{await page.goto(base+path);await expect(page.locator('.auth-brand')).toHaveText('GoJet.');await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.locator('.auth-panel')).toBeVisible();const width=await page.locator('.auth-panel').evaluate(node=>node.getBoundingClientRect().width);expect(width).toBeLessThanOrEqual(410);await noOverflow(page)})
  }
  test('login preserves password and email-code modes without layout duplication',async({page})=>{await page.route('**/api/public/account-policy',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({email_code_login_available:true})}));await page.route('**/api/public/auth/providers',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({providers:[]})}));await page.goto(base+'/login');const tabs=page.locator('.auth-mode-tabs');await expect(tabs).toBeVisible();await expect(tabs.getByRole('button')).toHaveCount(2);await tabs.getByRole('button',{name:'验证码登录'}).click();await expect(page.locator('#loginEmailCodeField')).toBeVisible();await expect(page.locator('input[name="password"]')).toBeHidden();await expect(page.getByRole('button',{name:'使用验证码登录'})).toBeVisible();await noOverflow(page)});
  test('registration can expose configured social adapters without hiding email registration',async({page})=>{await page.route('**/api/public/auth/providers',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({providers:[{id:'google',label:'Google'},{id:'github',label:'GitHub'}]})}));await page.route('**/api/public/settings',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({registration:{enabled:true}})}));await page.goto(base+'/register');await expect(page.locator('.social-provider')).toHaveText(['继续使用 Google','继续使用 GitHub']);await expect(page.locator('#registerForm input[name="email"]')).toBeVisible();await expect(page.locator('#registerForm input[name="password"]')).toBeVisible();await noOverflow(page)});
});
