server {
    listen 18088;
    server_name _;
    root __GOJET_ROOT__/installer;
    index index.php;
    access_log off;
    location = / { try_files /index.php =404; }
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:__PHP_FPM_SOCKET__;
    }
    location / { return 404; }
}
