<x-layouts.app title="链接管理" :eyebrow="$workspace->name">
  <div class="links-page" x-data="{ createOpen: {{ $errors->any()?'true':'false' }}, selected: [], filtersOpen:false, importOpen:false, toggleAll(event){ this.selected = event.target.checked ? Array.from(document.querySelectorAll('[data-link-checkbox]')).map(el=>Number(el.value)) : []; } }">
    <section class="page-header-pro">
      <div><span>链接工作台</span><h1>链接管理</h1><p>创建、组织、筛选、批量处理并分析当前工作区的全部链接资产。</p></div>
      <div><button class="btn-secondary" @click="importOpen=true">⇧ 导入 CSV</button><a class="btn-secondary" href="{{ route('links.export.all',request()->query()) }}">⇩ 导出</a><button id="create" class="btn-primary" @click="createOpen=true">＋ 创建链接</button></div>
    </section>

    <section class="link-summary-strip">
      <article><span>全部链接</span><strong>{{ number_format($totals['all']) }}</strong></article><article><span>运行中</span><strong>{{ number_format($totals['active']) }}</strong></article><article><span>已归档</span><strong>{{ number_format($totals['archived']) }}</strong></article><article><span>回收站</span><strong>{{ number_format($totals['trash']) }}</strong></article><article class="accent"><span>累计点击</span><strong>{{ number_format($totals['clicks']) }}</strong></article>
    </section>

    <section class="links-workspace-card">
      <div class="link-view-tabs">@foreach(['active'=>'运行中','all'=>'全部','archived'=>'已归档','trash'=>'回收站'] as $key=>$label)<a href="{{ route('links.index',array_merge(request()->except('page','view'),['view'=>$key])) }}" class="{{ $view===$key?'active':'' }}">{{ $label }} <span>{{ number_format($key==='active'?$totals['active']:($key==='archived'?$totals['archived']:($key==='trash'?$totals['trash']:$totals['all']))) }}</span></a>@endforeach</div>

      <form class="link-filter-bar" method="get" action="{{ route('links.index') }}">
        <input type="hidden" name="view" value="{{ $view }}">
        <div class="search-field"><span>⌕</span><input name="q" value="{{ request('q') }}" placeholder="搜索标题、短码、目标网址或备注"></div>
        <select name="status"><option value="">全部状态</option><option value="active" @selected(request('status')==='active')>运行中</option><option value="disabled" @selected(request('status')==='disabled')>已停用</option></select>
        <select name="domain_id"><option value="">全部域名</option>@foreach($domains as $domain)<option value="{{ $domain->id }}" @selected((string)request('domain_id')===(string)$domain->id)>{{ $domain->hostname }}</option>@endforeach</select>
        <select name="campaign_id"><option value="">全部活动</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}" @selected((string)request('campaign_id')===(string)$campaign->id)>{{ $campaign->name }}</option>@endforeach</select>
        <button class="filter-submit">筛选</button><a href="{{ route('links.index',['view'=>$view]) }}">重置</a><button type="button" class="filter-more" @click="filtersOpen=!filtersOpen">更多 ⌄</button>
        <div x-cloak x-show="filtersOpen" class="advanced-filters"><label>文件夹<select name="folder_id"><option value="">全部</option>@foreach($folders as $folder)<option value="{{ $folder->id }}" @selected((string)request('folder_id')===(string)$folder->id)>{{ $folder->name }}</option>@endforeach</select></label><label>标签<select name="tag_id"><option value="">全部</option>@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected((string)request('tag_id')===(string)$tag->id)>{{ $tag->name }}</option>@endforeach</select></label><label>健康状态<select name="health"><option value="">全部</option><option value="healthy" @selected(request('health')==='healthy')>正常</option><option value="warning" @selected(request('health')==='warning')>警告</option><option value="failed" @selected(request('health')==='failed')>失败</option></select></label><label>排序<select name="sort"><option value="created_at" @selected($sort==='created_at')>创建时间</option><option value="updated_at" @selected($sort==='updated_at')>更新时间</option><option value="clicks_count" @selected($sort==='clicks_count')>点击量</option><option value="title" @selected($sort==='title')>标题</option></select></label><label>方向<select name="direction"><option value="desc" @selected($direction==='desc')>降序</option><option value="asc" @selected($direction==='asc')>升序</option></select></label></div>
      </form>

      <form method="post" action="{{ route('links.bulk') }}">@csrf
        <div x-cloak x-show="selected.length" class="bulk-toolbar"><strong x-text="`已选择 ${selected.length} 条链接`"></strong><select name="action" required><option value="">选择批量操作</option><option value="activate">启用</option><option value="disable">停用</option><option value="archive">归档</option><option value="unarchive">取消归档</option><option value="trash">移入回收站</option><option value="restore">恢复</option><option value="delete_forever">永久删除</option><option value="move_campaign">移动到活动</option><option value="move_folder">移动到文件夹</option><option value="tag_add">添加标签</option><option value="tag_remove">移除标签</option></select><select name="campaign_id"><option value="">选择活动</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select><select name="folder_id"><option value="">选择文件夹</option>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->name }}</option>@endforeach</select><select name="tag_id"><option value="">选择标签</option>@foreach($tags as $tag)<option value="{{ $tag->id }}">{{ $tag->name }}</option>@endforeach</select><button>执行</button><button type="button" @click="selected=[]">取消</button></div>

        <div class="links-table-wrap"><table class="links-table"><thead><tr><th class="checkbox-col"><input type="checkbox" @change="toggleAll($event)"></th><th>链接</th><th>分类</th><th>状态</th><th>健康</th><th>点击</th><th>更新时间</th><th></th></tr></thead><tbody>
          @forelse($links as $link)
            <tr>
              <td><input data-link-checkbox type="checkbox" name="ids[]" value="{{ $link->id }}" x-model.number="selected"></td>
              <td><div class="link-main-cell"><div class="link-favicon">{{ mb_strtoupper(mb_substr($link->title ?: $link->slug,0,1)) }}</div><div><a href="{{ route('links.show',$link) }}">{{ $link->title ?: '未命名链接' }}</a><div class="short-url-row"><button type="button" x-data="clipboard" @click="copy('https://{{ $link->host }}/{{ $link->slug }}')">https://{{ $link->host }}/{{ $link->slug }} <span>⧉</span></button><small title="{{ $link->target_url }}">→ {{ Str::limit($link->target_url,62) }}</small></div></div></div></td>
              <td><div class="classification-cell">@if($link->campaign)<span class="category-pill">{{ $link->campaign->name }}</span>@endif @if($link->folder)<span class="folder-pill">▱ {{ $link->folder->name }}</span>@endif<div>@foreach($link->tags->take(3) as $tag)<i style="--tag:{{ $tag->color ?: '#94a3b8' }}">{{ $tag->name }}</i>@endforeach</div></div></td>
              <td><span class="{{ $link->trashed()?'badge-danger':($link->archived_at?'badge-neutral':($link->status==='active'?'badge-success':'badge-warning')) }}">{{ $link->trashed()?'回收站':($link->archived_at?'已归档':($link->status==='active'?'运行中':'已停用')) }}</span>@if($link->expires_at)<small class="status-note">到期 {{ $link->expires_at->format('Y-m-d') }}</small>@endif</td>
              <td><span class="health-state {{ $link->health_status ?: 'unknown' }}"><i></i>{{ match($link->health_status){'healthy'=>'正常','warning'=>'警告','failed'=>'失败',default=>'未检测'} }}</span>@if($link->health_http_status)<small class="status-note">HTTP {{ $link->health_http_status }}</small>@endif</td>
              <td><strong class="click-number">{{ number_format($link->clicks_count) }}</strong><small class="status-note">总访问</small></td>
              <td><strong>{{ $link->updated_at->diffForHumans() }}</strong><small class="status-note">{{ $link->updated_at->format('Y-m-d H:i') }}</small></td>
              <td><div class="row-menu" x-data="{open:false}"><button type="button" @click="open=!open">•••</button><div x-cloak x-show="open" @click.outside="open=false"><a href="{{ route('links.show',$link) }}">查看与分析</a>@unless($link->trashed())<a href="{{ route('links.routing',$link) }}">智能路由</a><form method="post" action="{{ route('links.duplicate',$link) }}">@csrf<button>复制链接</button></form>@if($link->archived_at)<form method="post" action="{{ route('links.unarchive',$link) }}">@csrf<button>取消归档</button></form>@else<form method="post" action="{{ route('links.archive',$link) }}">@csrf<button>归档</button></form>@endif<form method="post" action="{{ route('links.destroy',$link) }}" onsubmit="return confirm('确定移入回收站？')">@csrf @method('delete')<button class="danger">移入回收站</button></form>@else<form method="post" action="{{ route('links.restore',$link->id) }}">@csrf<button>恢复链接</button></form>@endunless</div></div></td>
            </tr>
          @empty<tr><td colspan="8"><div class="table-empty"><span>↗</span><h3>没有找到链接</h3><p>调整筛选条件，或创建当前工作区的第一条链接。</p><button type="button" class="btn-primary" @click="createOpen=true">＋ 创建链接</button></div></td></tr>@endforelse
        </tbody></table></div>
      </form>
      <div class="table-footer"><span>共 {{ number_format($links->total()) }} 条记录</span>{{ $links->links() }}</div>
    </section>

    <div x-cloak x-show="createOpen" class="drawer-overlay" role="dialog" aria-modal="true">
      <div class="drawer-backdrop" @click="createOpen=false"></div>
      <aside class="create-link-drawer" x-transition:enter="transition duration-200" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0">
        <div class="drawer-head"><div><span>新建资产</span><h2>创建链接</h2><p>基础信息始终可见，高级控制按任务分组。</p></div><button type="button" @click="createOpen=false">×</button></div>
        <form method="post" action="{{ route('links.store') }}" class="drawer-form">@csrf
          <section><h3><span>01</span>目标与短地址</h3><label><span>目标网址 *</span><input class="input" type="url" name="target_url" value="{{ old('target_url') }}" placeholder="https://example.com/campaign" required></label><div class="form-grid two"><label><span>品牌域名</span><select class="input" name="domain_id"><option value="">{{ config('gojet.default_host') }}</option>@foreach($domains as $domain)<option value="{{ $domain->id }}" @selected(old('domain_id')==$domain->id)>{{ $domain->hostname }}</option>@endforeach</select></label><label><span>自定义短码</span><input class="input" name="slug" value="{{ old('slug') }}" placeholder="自动生成"></label></div><label><span>内部标题</span><input class="input" name="title" value="{{ old('title') }}" placeholder="例如：2026 夏季发布活动"></label><label><span>公开描述</span><textarea class="input" rows="3" name="description">{{ old('description') }}</textarea></label></section>
          <section><h3><span>02</span>组织与协作</h3><div class="form-grid two"><label><span>活动</span><select class="input" name="campaign_id"><option value="">不加入活动</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select></label><label><span>文件夹</span><select class="input" name="folder_id"><option value="">根目录</option>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->name }}</option>@endforeach</select></label></div><label><span>标签</span><div class="drawer-tag-grid">@foreach($tags as $tag)<label><input type="checkbox" name="tag_ids[]" value="{{ $tag->id }}"><i style="background:{{ $tag->color ?: '#94a3b8' }}"></i>{{ $tag->name }}</label>@endforeach</div></label><label><span>新标签</span><input class="input" name="new_tags" placeholder="marketing, launch"></label><label><span>团队备注</span><textarea class="input" rows="3" name="notes"></textarea></label></section>
          <section><h3><span>03</span>访问控制</h3><div class="form-grid two"><label><span>跳转状态码</span><select class="input" name="redirect_type">@foreach([302,307,301,308] as $code)<option value="{{ $code }}" @selected($code===config('gojet.default_redirect_type'))>HTTP {{ $code }}</option>@endforeach</select></label><label><span>最大点击量</span><input class="input" type="number" min="1" name="max_clicks" placeholder="不限"></label><label><span>开始时间</span><input class="input" type="datetime-local" name="starts_at"></label><label><span>到期时间</span><input class="input" type="datetime-local" name="expires_at"></label></div><label><span>访问密码</span><input class="input" type="password" name="password" minlength="8" autocomplete="new-password" placeholder="留空表示公开访问"></label></section>
          <section><h3><span>04</span>UTM 与二维码</h3><div class="form-grid two">@foreach(['source'=>'来源','medium'=>'媒介','campaign'=>'活动','content'=>'内容','term'=>'关键词'] as $key=>$label)<label><span>UTM {{ $label }}</span><input class="input" name="utm_{{ $key }}"></label>@endforeach</div><div class="form-grid three"><label><span>二维码前景色</span><input class="input color-input" type="color" name="qr_dark" value="#0f172a"></label><label><span>二维码背景色</span><input class="input color-input" type="color" name="qr_light" value="#ffffff"></label><label><span>纠错级别</span><select class="input" name="qr_level"><option>M</option><option>L</option><option>Q</option><option>H</option></select></label></div></section>
          <div class="drawer-actions"><button type="button" class="btn-secondary" @click="createOpen=false">取消</button><button class="btn-primary">创建链接 →</button></div>
        </form>
      </aside>
    </div>

    <div x-cloak x-show="importOpen" class="modal-overlay" @click.self="importOpen=false"><div class="import-modal"><div><span>批量导入</span><h2>从 CSV 导入链接</h2><p>支持目标网址、短码、标题、状态和组织字段。导入失败的行会返回明确错误。</p></div><form method="post" enctype="multipart/form-data" action="{{ route('links.import') }}">@csrf<label class="csv-drop"><input type="file" name="file" accept=".csv,text/csv" required><span>⇧</span><strong>选择 CSV 文件</strong><small>最大 10 MB</small></label><div><button type="button" class="btn-secondary" @click="importOpen=false">取消</button><button class="btn-primary">开始导入</button></div></form></div></div>
  </div>
</x-layouts.app>
