<x-layouts.app :title="__('v3.organization.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="page-kicker">{{ $workspace->name }}</p><h1 class="page-title mt-1">{{ __('v3.organization.title') }}</h1><p class="page-description">{{ __('v3.organization.subtitle') }}</p></div><a class="btn-secondary" href="{{ route('links.index') }}">← {{ __('v3.nav.links') }}</a></div>

    <div class="mt-8 grid gap-6 xl:grid-cols-3">
      <section class="panel">
        <h2 class="text-lg font-bold text-slate-950">{{ __('v3.organization.campaigns') }}</h2>
        <form class="mt-5 space-y-3 rounded-2xl bg-slate-50 p-4" method="post" action="{{ route('campaigns.store') }}">@csrf
          <div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" required></div>
          <div><label class="label">{{ __('v3.common.description') }}</label><textarea class="input min-h-20" name="description"></textarea></div>
          <div class="grid grid-cols-2 gap-3"><div><label class="label">{{ __('v3.organization.color') }}</label><input class="input h-11" type="color" name="color" value="#6366f1"></div><div><label class="label">{{ __('v3.links.starts_at') }}</label><input class="input" type="datetime-local" name="starts_at"></div></div>
          <button class="btn-brand w-full" type="submit">＋ {{ __('v3.organization.new_campaign') }}</button>
        </form>
        <div class="mt-5 space-y-3">@forelse($campaigns as $campaign)<details class="rounded-2xl border border-slate-200 bg-white p-4"><summary class="cursor-pointer list-none"><div class="flex items-center justify-between gap-3"><div class="min-w-0"><div class="flex items-center gap-2"><span class="h-3 w-3 rounded-full" style="background:{{ $campaign->color ?: '#94a3b8' }}"></span><strong class="truncate">{{ $campaign->name }}</strong></div><p class="mt-1 text-xs text-slate-400">{{ __('v3.organization.links_count',['count'=>$campaign->links_count]) }}</p></div><span class="badge-neutral">{{ $campaign->status }}</span></div></summary><form class="mt-4 space-y-3 border-t border-slate-100 pt-4" method="post" action="{{ route('campaigns.update',$campaign) }}">@csrf @method('patch')<input class="input" name="name" value="{{ $campaign->name }}" required><textarea class="input min-h-20" name="description">{{ $campaign->description }}</textarea><div class="grid grid-cols-2 gap-3"><input class="input h-11" type="color" name="color" value="{{ $campaign->color ?: '#6366f1' }}"><select class="input" name="status">@foreach(['active','paused','completed'] as $status)<option value="{{ $status }}" @selected($campaign->status===$status)>{{ $status }}</option>@endforeach</select></div><div class="flex gap-2"><button class="btn-primary flex-1">{{ __('v3.common.save') }}</button><button class="btn-danger" type="submit" formmethod="post" formaction="{{ route('campaigns.destroy',$campaign) }}" onclick="event.preventDefault(); if(confirm(@js(__('v3.common.confirm_delete')))){ let f=document.createElement('form'); f.method='POST'; f.action=this.formAction; f.innerHTML=`@csrf @method('delete')`; document.body.appendChild(f); f.submit(); }">{{ __('v3.common.delete') }}</button></div></form></details>@empty<div class="empty-state !py-10">{{ __('v3.organization.empty_campaigns') }}</div>@endforelse</div>
      </section>

      <section class="panel">
        <h2 class="text-lg font-bold text-slate-950">{{ __('v3.organization.folders') }}</h2>
        <form class="mt-5 space-y-3 rounded-2xl bg-slate-50 p-4" method="post" action="{{ route('folders.store') }}">@csrf
          <div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" required></div><div><label class="label">{{ __('v3.organization.parent_folder') }}</label><select class="input" name="parent_id"><option value="">{{ __('v3.common.none') }}</option>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->name }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.common.description') }}</label><textarea class="input min-h-20" name="description"></textarea></div><div><label class="label">{{ __('v3.organization.color') }}</label><input class="input h-11" type="color" name="color" value="#06b6d4"></div><button class="btn-brand w-full">＋ {{ __('v3.organization.new_folder') }}</button>
        </form>
        <div class="mt-5 space-y-3">@forelse($folders as $folder)<details class="rounded-2xl border border-slate-200 bg-white p-4"><summary class="cursor-pointer list-none"><div class="flex items-center justify-between"><div><strong>{{ $folder->name }}</strong><p class="mt-1 text-xs text-slate-400">{{ __('v3.organization.links_count',['count'=>$folder->links_count]) }}</p></div><span class="h-3 w-3 rounded-full" style="background:{{ $folder->color ?: '#94a3b8' }}"></span></div></summary><form class="mt-4 space-y-3 border-t border-slate-100 pt-4" method="post" action="{{ route('folders.update',$folder) }}">@csrf @method('patch')<input class="input" name="name" value="{{ $folder->name }}" required><select class="input" name="parent_id"><option value="">{{ __('v3.common.none') }}</option>@foreach($folders->where('id','!=',$folder->id) as $parent)<option value="{{ $parent->id }}" @selected($folder->parent_id===$parent->id)>{{ $parent->name }}</option>@endforeach</select><textarea class="input min-h-20" name="description">{{ $folder->description }}</textarea><input class="input h-11" type="color" name="color" value="{{ $folder->color ?: '#06b6d4' }}"><div class="flex gap-2"><button class="btn-primary flex-1">{{ __('v3.common.save') }}</button></div></form><form class="mt-2" method="post" action="{{ route('folders.destroy',$folder) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger w-full">{{ __('v3.common.delete') }}</button></form></details>@empty<div class="empty-state !py-10">{{ __('v3.organization.empty_folders') }}</div>@endforelse</div>
      </section>

      <section class="panel">
        <h2 class="text-lg font-bold text-slate-950">{{ __('v3.organization.tags') }}</h2>
        <form class="mt-5 space-y-3 rounded-2xl bg-slate-50 p-4" method="post" action="{{ route('tags.store') }}">@csrf<div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" required></div><div><label class="label">{{ __('v3.organization.color') }}</label><input class="input h-11" type="color" name="color" value="#10b981"></div><button class="btn-brand w-full">＋ {{ __('v3.organization.new_tag') }}</button></form>
        <div class="mt-5 space-y-3">@forelse($tags as $tag)<div class="rounded-2xl border border-slate-200 bg-white p-4"><form class="grid grid-cols-[1fr_70px_auto] gap-2" method="post" action="{{ route('tags.update',$tag) }}">@csrf @method('patch')<input class="input" name="name" value="{{ $tag->name }}" required><input class="input h-11" type="color" name="color" value="{{ $tag->color ?: '#10b981' }}"><button class="btn-primary">{{ __('v3.common.save') }}</button></form><div class="mt-3 flex items-center justify-between"><span class="text-xs text-slate-400">{{ __('v3.organization.links_count',['count'=>$tag->links_count]) }}</span><form method="post" action="{{ route('tags.destroy',$tag) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="text-xs font-bold text-rose-600">{{ __('v3.common.delete') }}</button></form></div></div>@empty<div class="empty-state !py-10">{{ __('v3.organization.empty_tags') }}</div>@endforelse</div>
      </section>
    </div>
  </section>
</x-layouts.app>
