<x-layouts.app :title="__('v3.routing.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><a class="text-sm font-semibold text-slate-500 hover:text-slate-950" href="{{ route('links.show',$link) }}">← {{ $link->title ?: $link->slug }}</a><p class="page-kicker mt-5">{{ __('v3.links.routing') }}</p><h1 class="page-title mt-1">{{ __('v3.routing.title') }}</h1><p class="page-description">{{ __('v3.routing.subtitle') }}</p></div><a class="btn-secondary" href="{{ route('links.index') }}">{{ __('v3.nav.links') }}</a></div>

    @if(session('routing_simulation'))<div class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><strong>{{ __('v3.routing.matched') }}：</strong>{{ session('routing_simulation.name') }} · {{ session('routing_simulation.url') }} @if(session('routing_simulation.rule'))· Rule #{{ session('routing_simulation.rule') }}@endif</div>@endif

    <div class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(380px,.65fr)]">
      <div class="space-y-6">
        <section class="panel">
          <div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-950">{{ __('v3.routing.destinations') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('v3.routing.subtitle') }}</p></div><span class="badge-neutral">{{ $link->destinations->count() }}</span></div>
          <form class="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[1fr_1.5fr_120px]" method="post" action="{{ route('links.destinations.store',$link) }}">@csrf<div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" placeholder="Variant A"></div><div><label class="label">{{ __('v3.links.target_url') }}</label><input class="input" type="url" name="target_url" required></div><div><label class="label">{{ __('v3.routing.weight') }}</label><input class="input" type="number" name="weight" value="100" min="0" max="10000"></div><label class="flex items-center gap-2 text-sm font-semibold md:col-span-2"><input type="checkbox" name="is_fallback" value="1">{{ __('v3.routing.fallback') }}</label><button class="btn-brand md:col-start-3">＋ {{ __('v3.routing.new_destination') }}</button></form>
          <div class="mt-5 space-y-3">@forelse($link->destinations as $destination)<details class="rounded-2xl border border-slate-200 bg-white p-4"><summary class="cursor-pointer list-none"><div class="flex flex-wrap items-center justify-between gap-3"><div><strong>{{ $destination->name ?: '#'.$destination->id }}</strong><p class="mt-1 max-w-2xl truncate text-sm text-slate-500">{{ $destination->target_url }}</p></div><div class="flex gap-2"><span class="badge-neutral">{{ __('v3.routing.weight') }} {{ $destination->weight }}</span>@if($destination->is_fallback)<span class="badge-info">{{ __('v3.routing.fallback') }}</span>@endif<span class="{{ $destination->is_active ? 'badge-success':'badge-danger' }}">{{ $destination->is_active ? __('v3.common.active'):__('v3.common.disabled') }}</span></div></div></summary><form class="mt-4 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-2" method="post" action="{{ route('links.destinations.update',[$link,$destination]) }}">@csrf @method('patch')<div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" value="{{ $destination->name }}"></div><div><label class="label">{{ __('v3.routing.weight') }}</label><input class="input" type="number" name="weight" value="{{ $destination->weight }}" min="0"></div><div class="md:col-span-2"><label class="label">{{ __('v3.links.target_url') }}</label><input class="input" type="url" name="target_url" value="{{ $destination->target_url }}" required></div><input type="hidden" name="position" value="{{ $destination->position }}"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_fallback" value="1" @checked($destination->is_fallback)>{{ __('v3.routing.fallback') }}</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($destination->is_active)>{{ __('v3.routing.enabled') }}</label><button class="btn-primary">{{ __('v3.common.save') }}</button></form><form class="mt-2" method="post" action="{{ route('links.destinations.destroy',[$link,$destination]) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger w-full">{{ __('v3.common.delete') }}</button></form></details>@empty<div class="empty-state !py-12">{{ __('v3.routing.no_destinations') }}</div>@endforelse</div>
        </section>

        <section class="panel">
          <div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-950">{{ __('v3.routing.rules') }}</h2><p class="mt-1 text-sm text-slate-500">country / region / city / device / platform / browser / language / referrer / query / schedule</p></div><span class="badge-neutral">{{ $link->routingRules->count() }}</span></div>
          @if($link->destinations->isNotEmpty())<form class="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-2" method="post" action="{{ route('links.rules.store',$link) }}">@csrf<div><label class="label">{{ __('v3.routing.destinations') }}</label><select class="input" name="destination_id" required>@foreach($link->destinations as $destination)<option value="{{ $destination->id }}">{{ $destination->name ?: '#'.$destination->id }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.routing.type') }}</label><select class="input" name="type">@foreach(['country','region','city','device','platform','browser','language','referrer','query','schedule'] as $type)<option value="{{ $type }}">{{ $type }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.routing.operator') }}</label><select class="input" name="operator">@foreach(['in','not_in','equals','contains','exists','missing'] as $operator)<option value="{{ $operator }}">{{ $operator }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.routing.priority') }}</label><input class="input" type="number" name="priority" value="100" min="1"></div><div class="md:col-span-2"><label class="label">{{ __('v3.routing.values') }}</label><textarea class="input min-h-28 font-mono text-sm" name="values" placeholder="US, SG, JP&#10;or {&quot;key&quot;:&quot;source&quot;,&quot;values&quot;:[&quot;newsletter&quot;]}" required></textarea></div><button class="btn-brand md:col-span-2">＋ {{ __('v3.routing.new_rule') }}</button></form>@endif
          <div class="mt-5 space-y-3">@forelse($link->routingRules as $rule)<details class="rounded-2xl border border-slate-200 bg-white p-4"><summary class="cursor-pointer list-none"><div class="flex flex-wrap items-center justify-between gap-3"><div><strong>#{{ $rule->priority }} · {{ $rule->type }} {{ $rule->operator }}</strong><p class="mt-1 text-sm text-slate-500">→ {{ $rule->destination?->name ?: '#'.$rule->destination_id }}</p></div><span class="{{ $rule->is_active ? 'badge-success':'badge-danger' }}">{{ $rule->is_active ? __('v3.common.active'):__('v3.common.disabled') }}</span></div></summary><form class="mt-4 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-2" method="post" action="{{ route('links.rules.update',[$link,$rule]) }}">@csrf @method('patch')<select class="input" name="destination_id">@foreach($link->destinations as $destination)<option value="{{ $destination->id }}" @selected($rule->destination_id===$destination->id)>{{ $destination->name ?: '#'.$destination->id }}</option>@endforeach</select><select class="input" name="type">@foreach(['country','region','city','device','platform','browser','language','referrer','query','schedule'] as $type)<option value="{{ $type }}" @selected($rule->type===$type)>{{ $type }}</option>@endforeach</select><select class="input" name="operator">@foreach(['in','not_in','equals','contains','exists','missing'] as $operator)<option value="{{ $operator }}" @selected($rule->operator===$operator)>{{ $operator }}</option>@endforeach</select><input class="input" type="number" name="priority" value="{{ $rule->priority }}"><textarea class="input min-h-28 font-mono text-sm md:col-span-2" name="values">{{ json_encode($rule->values, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</textarea><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($rule->is_active)>{{ __('v3.routing.enabled') }}</label><button class="btn-primary">{{ __('v3.common.save') }}</button></form><form class="mt-2" method="post" action="{{ route('links.rules.destroy',[$link,$rule]) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger w-full">{{ __('v3.common.delete') }}</button></form></details>@empty<div class="empty-state !py-12">{{ __('v3.routing.no_rules') }}</div>@endforelse</div>
        </section>
      </div>

      <aside class="panel h-fit xl:sticky xl:top-6">
        <h2 class="text-lg font-bold text-slate-950">{{ __('v3.routing.simulator') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('v3.routing.subtitle') }}</p>
        <form class="mt-5 space-y-3" method="post" action="{{ route('links.routing.simulate',$link) }}">@csrf<div class="grid grid-cols-2 gap-3"><input class="input" name="country" maxlength="2" placeholder="Country: SG"><input class="input" name="region" placeholder="Region"><input class="input" name="city" placeholder="City"><select class="input" name="device"><option value="">Device</option><option value="desktop">desktop</option><option value="mobile">mobile</option></select><input class="input" name="platform" placeholder="Platform"><input class="input" name="browser" placeholder="Browser"><input class="input" name="language" placeholder="Language"><input class="input" name="referrer" placeholder="Referrer"></div><div class="grid grid-cols-2 gap-3"><input class="input" name="query_key" placeholder="Query key"><input class="input" name="query_value" placeholder="Query value"></div><button class="btn-brand w-full">{{ __('v3.routing.simulate') }}</button></form>
        <div class="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-600"><strong class="text-slate-900">Rule JSON</strong><pre class="mt-2 overflow-x-auto text-xs">query:
{"key":"source","values":["email"]}

schedule:
{"timezone":"Asia/Shanghai","days":[1,2,3,4,5],"time_start":"09:00","time_end":"18:00"}</pre></div>
      </aside>
    </div>
  </section>
</x-layouts.app>
