import React from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider } from "@tanstack/react-router";
import { LocaleProvider } from "@gojet/ui/locale";
import "@gojet/tokens/css";
import "@gojet/ui/css";
import "@gojet/ui/data.css";
import "@gojet/ui/patterns.css";
import "@gojet/ui/overlays.css";
import "@gojet/ui/shells.css";
import "@gojet/ui/shells-responsive.css";
import "./styles.css";
import "./commerce.css";
import "./trust-safety.css";
import "./p17-admin.css";
import "./admin-auth.css";
import { router } from "./router";

const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 15_000, retry: 1, refetchOnWindowFocus: false } } });
const root = document.getElementById("root");
if (!root) throw new Error("Missing #root");
createRoot(root).render(<React.StrictMode><LocaleProvider><QueryClientProvider client={queryClient}><RouterProvider router={router} /></QueryClientProvider></LocaleProvider></React.StrictMode>);
