import { Suspense, lazy, type ComponentType } from "react";
import { Outlet, createRootRoute, createRoute, createRouter, useRouterState } from "@tanstack/react-router";
import { AdminShell } from "./AdminShell";

const PlansPage = lazy(() => import("./routes/PlansPage"));
const AdminBillingPage = lazy(() => import("./routes/AdminBillingPage"));
const PaymentsPage = lazy(() => import("./routes/PaymentsPage"));
const FXPage = lazy(() => import("./routes/FXPage"));
const TicketsPage = lazy(() => import("./routes/TicketsPage"));
const MailPage = lazy(() => import("./routes/MailPage"));
const MailSettingsPage = lazy(() => import("./routes/MailSettingsPage"));
const TemplatesPage = lazy(() => import("./routes/TemplatesPage"));
const OAuthPage = lazy(() => import("./routes/OAuthPage"));
const core = (name: keyof typeof import("./routes/AdminP17Core")) => lazy(() => import("./routes/AdminP17Core").then((module) => ({ default: module[name] as ComponentType })));
const platform = (name: keyof typeof import("./routes/AdminP17OpsPlatform")) => lazy(() => import("./routes/AdminP17OpsPlatform").then((module) => ({ default: module[name] as ComponentType })));
const AdminOverviewPage = core("AdminOverviewPage"); const AdminUsersPage = core("AdminUsersPage"); const AdminWorkspacesPage = core("AdminWorkspacesPage"); const AdminMembershipsPage = core("AdminMembershipsPage"); const AdminLinksPage = core("AdminLinksPage"); const AdminDomainsPage = core("AdminDomainsPage"); const AdminQRPage = core("AdminQRPage"); const AdminFilesPage = core("AdminFilesPage"); const AdminTextPage = core("AdminTextPage"); const AdminBioPage = core("AdminBioPage"); const AdministratorsPage = core("AdministratorsPage"); const RolesPage = core("RolesPage"); const PermissionsPage = core("PermissionsPage");
const AnnouncementsPage = platform("AnnouncementsPage"); const JobsPage = platform("JobsPage"); const ServicesPage = platform("ServicesPage"); const GeneralSettingsPage = platform("GeneralSettingsPage"); const OfficialDomainsPage = platform("OfficialDomainsPage"); const TurnstilePage = platform("TurnstilePage"); const StoragePage = platform("StoragePage"); const IntegrationsPage = platform("IntegrationsPage");
const DestinationRiskPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.DestinationRiskPage }))); const DestinationRiskDetailPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.DestinationRiskDetailPage }))); const FileSecurityPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.FileSecurityPage }))); const AbuseReportsPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.AbuseReportsPage }))); const SecurityEventsPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.SecurityEventsPage }))); const AuditPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.AuditPage })));

function RootLayout() { const pathname = useRouterState({ select: (state) => state.location.pathname }); return <AdminShell pathname={pathname}><Suspense fallback={<main className="shell-page-proof"><span>GoJet Admin</span><p>正在加载…</p></main>}><Outlet /></Suspense></AdminShell>; }
const rootRoute = createRootRoute({ component: RootLayout });
const route = (path: string, component: ComponentType) => createRoute({ getParentRoute: () => rootRoute, path, component });
const indexRoute = route("/", AdminOverviewPage);
const usersRoute = route("/users", AdminUsersPage); const workspacesRoute = route("/workspaces", AdminWorkspacesPage); const membershipsRoute = route("/memberships", AdminMembershipsPage);
const linksRoute = route("/links", AdminLinksPage); const domainsRoute = route("/domains", AdminDomainsPage); const qrRoute = route("/qr", AdminQRPage); const filesRoute = route("/files", AdminFilesPage); const textRoute = route("/text", AdminTextPage); const bioRoute = route("/bio", AdminBioPage);
const destinationRiskRoute = route("/destination-risk", DestinationRiskPage); const destinationRiskDetailRoute = route("/destination-risk/$riskId", DestinationRiskDetailPage); const fileSecurityRoute = route("/file-security", FileSecurityPage); const abuseRoute = route("/abuse", AbuseReportsPage); const securityEventsRoute = route("/security-events", SecurityEventsPage);
const ticketsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/tickets", component: TicketsPage }); const announcementsRoute = route("/announcements", AnnouncementsPage); const mailRoute = createRoute({ getParentRoute: () => rootRoute, path: "/mail", component: MailPage }); const jobsRoute = route("/jobs", JobsPage); const servicesRoute = route("/services", ServicesPage);
const plansRoute = createRoute({ getParentRoute: () => rootRoute, path: "/plans", component: PlansPage }); const billingRoute = createRoute({ getParentRoute: () => rootRoute, path: "/billing", component: AdminBillingPage }); const paymentsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/payments", component: PaymentsPage }); const fxRoute = createRoute({ getParentRoute: () => rootRoute, path: "/fx", component: FXPage });
const administratorsRoute = route("/administrators", AdministratorsPage); const rolesRoute = route("/roles", RolesPage); const permissionsRoute = route("/permissions", PermissionsPage); const auditRoute = route("/audit", AuditPage);
const generalRoute = route("/general", GeneralSettingsPage); const officialDomainsRoute = route("/official-domains", OfficialDomainsPage); const oauthRoute = createRoute({ getParentRoute: () => rootRoute, path: "/oauth", component: OAuthPage }); const turnstileRoute = route("/turnstile", TurnstilePage); const mailSettingsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/mail-settings", component: MailSettingsPage }); const templatesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/templates", component: TemplatesPage }); const storageRoute = route("/storage", StoragePage); const integrationsRoute = route("/integrations", IntegrationsPage);
const routeTree = rootRoute.addChildren([indexRoute, usersRoute, workspacesRoute, membershipsRoute, linksRoute, domainsRoute, qrRoute, filesRoute, textRoute, bioRoute, destinationRiskRoute, destinationRiskDetailRoute, fileSecurityRoute, abuseRoute, securityEventsRoute, ticketsRoute, announcementsRoute, mailRoute, jobsRoute, servicesRoute, plansRoute, billingRoute, paymentsRoute, fxRoute, administratorsRoute, rolesRoute, permissionsRoute, auditRoute, generalRoute, officialDomainsRoute, oauthRoute, turnstileRoute, mailSettingsRoute, templatesRoute, storageRoute, integrationsRoute]);
export const router = createRouter({ routeTree, basepath: "/admin" });
declare module "@tanstack/react-router" { interface Register { router: typeof router } }
