import { Suspense, lazy, type ComponentType } from "react";
import { Outlet, createRootRoute, createRoute, createRouter, useRouterState } from "@tanstack/react-router";
import { AdminShell } from "./AdminShell";

const AdminOverviewPage = lazy(() => import("./routes/AdminOverviewPage"));
const PlansPage = lazy(() => import("./routes/PlansPage"));
const AdminBillingPage = lazy(() => import("./routes/AdminBillingPage"));
const PaymentsPage = lazy(() => import("./routes/PaymentsPage"));
const FXPage = lazy(() => import("./routes/FXPage"));
const TicketsPage = lazy(() => import("./routes/TicketsPage"));
const MailPage = lazy(() => import("./routes/MailPage"));
const MailSettingsPage = lazy(() => import("./routes/MailSettingsPage"));
const TemplatesPage = lazy(() => import("./routes/TemplatesPage"));
const OAuthPage = lazy(() => import("./routes/OAuthPage"));
const core = (name: keyof typeof import("./routes/AdminP17Core")) => lazy(() => import("./routes/AdminP17Core").then((module) => ({ default: module[name] as ComponentType })));
const platform = (name: keyof typeof import("./routes/AdminP17OpsPlatform")) => lazy(() => import("./routes/AdminP17OpsPlatform").then((module) => ({ default: module[name] as ComponentType })));
const AdminUsersPage = core("AdminUsersPage");
const AdminWorkspacesPage = core("AdminWorkspacesPage");
const AdminMembershipsPage = core("AdminMembershipsPage");
const AdminLinksPage = core("AdminLinksPage");
const AdminDomainsPage = core("AdminDomainsPage");
const AdminQRPage = core("AdminQRPage");
const AdminFilesPage = core("AdminFilesPage");
const AdminTextPage = core("AdminTextPage");
const AdminBioPage = core("AdminBioPage");
const AdministratorsPage = core("AdministratorsPage");
const RolesPage = core("RolesPage");
const PermissionsPage = core("PermissionsPage");
const AnnouncementsPage = platform("AnnouncementsPage");
const JobsPage = platform("JobsPage");
const ServicesPage = platform("ServicesPage");
const GeneralSettingsPage = platform("GeneralSettingsPage");
const OfficialDomainsPage = platform("OfficialDomainsPage");
const TurnstilePage = platform("TurnstilePage");
const StoragePage = platform("StoragePage");
const IntegrationsPage = platform("IntegrationsPage");
const DestinationRiskPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.DestinationRiskPage })));
const DestinationRiskDetailPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.DestinationRiskDetailPage })));
const FileSecurityPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.FileSecurityPage })));
const AbuseReportsPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.AbuseReportsPage })));
const SecurityEventsPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.SecurityEventsPage })));
const AuditPage = lazy(() => import("./routes/TrustSafetyPages").then((module) => ({ default: module.AuditPage })));

function RootLayout() {
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  return <AdminShell pathname={pathname}><Suspense fallback={<main className="shell-page-proof"><span>GoJet Admin</span><p>正在加载…</p></main>}><Outlet /></Suspense></AdminShell>;
}

const rootRoute = createRootRoute({ component: RootLayout });
const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: "/", component: AdminOverviewPage });
const usersRoute = createRoute({ getParentRoute: () => rootRoute, path: "/users", component: AdminUsersPage });
const workspacesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/workspaces", component: AdminWorkspacesPage });
const membershipsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/memberships", component: AdminMembershipsPage });
const linksRoute = createRoute({ getParentRoute: () => rootRoute, path: "/links", component: AdminLinksPage });
const domainsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/domains", component: AdminDomainsPage });
const qrRoute = createRoute({ getParentRoute: () => rootRoute, path: "/qr", component: AdminQRPage });
const filesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/files", component: AdminFilesPage });
const textRoute = createRoute({ getParentRoute: () => rootRoute, path: "/text", component: AdminTextPage });
const bioRoute = createRoute({ getParentRoute: () => rootRoute, path: "/bio", component: AdminBioPage });
const destinationRiskRoute = createRoute({ getParentRoute: () => rootRoute, path: "/destination-risk", component: DestinationRiskPage });
const destinationRiskDetailRoute = createRoute({ getParentRoute: () => rootRoute, path: "/destination-risk/$riskId", component: DestinationRiskDetailPage });
const fileSecurityRoute = createRoute({ getParentRoute: () => rootRoute, path: "/file-security", component: FileSecurityPage });
const abuseRoute = createRoute({ getParentRoute: () => rootRoute, path: "/abuse", component: AbuseReportsPage });
const securityEventsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/security-events", component: SecurityEventsPage });
const ticketsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/tickets", component: TicketsPage });
const announcementsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/announcements", component: AnnouncementsPage });
const mailRoute = createRoute({ getParentRoute: () => rootRoute, path: "/mail", component: MailPage });
const jobsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/jobs", component: JobsPage });
const servicesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/services", component: ServicesPage });
const plansRoute = createRoute({ getParentRoute: () => rootRoute, path: "/plans", component: PlansPage });
const billingRoute = createRoute({ getParentRoute: () => rootRoute, path: "/billing", component: AdminBillingPage });
const paymentsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/payments", component: PaymentsPage });
const fxRoute = createRoute({ getParentRoute: () => rootRoute, path: "/fx", component: FXPage });
const administratorsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/administrators", component: AdministratorsPage });
const rolesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/roles", component: RolesPage });
const permissionsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/permissions", component: PermissionsPage });
const auditRoute = createRoute({ getParentRoute: () => rootRoute, path: "/audit", component: AuditPage });
const generalRoute = createRoute({ getParentRoute: () => rootRoute, path: "/general", component: GeneralSettingsPage });
const officialDomainsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/official-domains", component: OfficialDomainsPage });
const oauthRoute = createRoute({ getParentRoute: () => rootRoute, path: "/oauth", component: OAuthPage });
const turnstileRoute = createRoute({ getParentRoute: () => rootRoute, path: "/turnstile", component: TurnstilePage });
const mailSettingsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/mail-settings", component: MailSettingsPage });
const templatesRoute = createRoute({ getParentRoute: () => rootRoute, path: "/templates", component: TemplatesPage });
const storageRoute = createRoute({ getParentRoute: () => rootRoute, path: "/storage", component: StoragePage });
const integrationsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/integrations", component: IntegrationsPage });
const routeTree = rootRoute.addChildren([indexRoute, usersRoute, workspacesRoute, membershipsRoute, linksRoute, domainsRoute, qrRoute, filesRoute, textRoute, bioRoute, destinationRiskRoute, destinationRiskDetailRoute, fileSecurityRoute, abuseRoute, securityEventsRoute, ticketsRoute, announcementsRoute, mailRoute, jobsRoute, servicesRoute, plansRoute, billingRoute, paymentsRoute, fxRoute, administratorsRoute, rolesRoute, permissionsRoute, auditRoute, generalRoute, officialDomainsRoute, oauthRoute, turnstileRoute, mailSettingsRoute, templatesRoute, storageRoute, integrationsRoute]);
export const router = createRouter({ routeTree, basepath: "/admin" });

declare module "@tanstack/react-router" { interface Register { router: typeof router } }
