import { useId, useMemo, useState, type ChangeEvent, type HTMLAttributes, type ReactNode } from "react";
import { Dialog as BaseDialog } from "@base-ui/react/dialog";
import { ChevronLeft, ChevronRight, Search, X, type LucideIcon } from "@gojet/icons";
import { Button, IconButton, Input } from "./index";
import { useLocale } from "./locale";

export function RadioGroup({ name, label, value, onChange, options }: { name: string; label: string; value?: string; onChange?: (value: string) => void; options: Array<{ value: string; label: string; description?: string }> }) { return <fieldset className="gj-radio-group"><legend className="gj-label">{label}</legend>{options.map((option) => <label className="gj-radio-option" key={option.value}><input type="radio" name={name} value={option.value} checked={value === option.value} onChange={() => onChange?.(option.value)} /><span><strong>{option.label}</strong>{option.description ? <small>{option.description}</small> : null}</span></label>)}</fieldset>; }
export function Slider({ label, value, min = 0, max = 100, step = 1, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; onChange?: (value: number) => void }) { return <label className="gj-field"><span className="gj-label">{label}</span><div className="gj-slider-row"><input className="gj-slider" type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange?.(Number(event.target.value))} /><output>{value}</output></div></label>; }
export function DatePicker({ id, label, value, onChange }: { id: string; label: string; value?: string; onChange?: (value: string) => void }) { return <label className="gj-field" htmlFor={id}><span className="gj-label">{label}</span><input className="gj-input" id={id} type="date" value={value} onChange={(e) => onChange?.(e.target.value)} /></label>; }
export function DateTime({ id, label, value, onChange }: { id: string; label: string; value?: string; onChange?: (value: string) => void }) { return <label className="gj-field" htmlFor={id}><span className="gj-label">{label}</span><input className="gj-input" id={id} type="datetime-local" value={value} onChange={(e) => onChange?.(e.target.value)} /></label>; }

export function OtpInput({ id, label, value = "", onChange }: { id: string; label?: string; value?: string; onChange?: (value: string) => void }) {
  const { text } = useLocale();
  const handle = (event: ChangeEvent<HTMLInputElement>) => onChange?.(event.target.value.replace(/\D/g, "").slice(0, 6));
  return <label className="gj-field" htmlFor={id}><span className="gj-label">{label ?? text("Verification code", "验证码")}</span><input className="gj-input gj-otp" id={id} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={value} onChange={handle} placeholder="000000" /></label>;
}
export function Combobox({ id, label, value, onChange, options }: { id: string; label: string; value?: string; onChange?: (value: string) => void; options: string[] }) { const listId = `${id}-options`; return <label className="gj-field" htmlFor={id}><span className="gj-label">{label}</span><input className="gj-input" id={id} list={listId} value={value} onChange={(e) => onChange?.(e.target.value)} /><datalist id={listId}>{options.map((option) => <option value={option} key={option} />)}</datalist></label>; }
export function Progress({ value, label }: { value: number; label: string }) { const safe = Math.min(100, Math.max(0, value)); return <div className="gj-progress-wrap"><div className="gj-progress-label"><span>{label}</span><span>{safe}%</span></div><div className="gj-progress" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe}><span style={{ width: `${safe}%` }} /></div></div>; }
export function InlineMessage({ tone = "info", children }: { tone?: "info" | "success" | "warning" | "danger"; children: ReactNode }) { return <p className="gj-inline-message" data-tone={tone}>{children}</p>; }
export function Avatar({ name, src, size = 32 }: { name: string; src?: string; size?: number }) { const initials = name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase() ?? "").join(""); return <span className="gj-avatar" style={{ width: size, height: size }} aria-label={name}>{src ? <img src={src} alt="" /> : initials}</span>; }

export function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange?: (page: number) => void }) { const { text } = useLocale(); return <nav className="gj-pagination" aria-label={text("Pagination", "分页")}><IconButton label={text("Previous page", "上一页")} disabled={page <= 1} onClick={() => onChange?.(page - 1)}><ChevronLeft size={16} /></IconButton><span>{text(`Page ${page} of ${pages}`, `第 ${page} / ${pages} 页`)}</span><IconButton label={text("Next page", "下一页")} disabled={page >= pages} onClick={() => onChange?.(page + 1)}><ChevronRight size={16} /></IconButton></nav>; }
export function FilterBar({ search, onSearch, children, actions }: { search?: string; onSearch?: (value: string) => void; children?: ReactNode; actions?: ReactNode }) { const { text } = useLocale(); return <div className="gj-filter-bar"><label className="gj-filter-search"><Search size={16} aria-hidden="true" /><input value={search} onChange={(e) => onSearch?.(e.target.value)} placeholder={text("Search", "搜索")} aria-label={text("Search", "搜索")} /></label><div className="gj-filter-controls">{children}</div>{actions ? <div className="gj-filter-actions">{actions}</div> : null}</div>; }
export function BulkActionBar({ selected, children, onClear }: { selected: number; children: ReactNode; onClear?: () => void }) { const { text } = useLocale(); if (selected <= 0) return null; return <div className="gj-bulk-bar" role="region" aria-label={text("Bulk actions", "批量操作")}><strong>{text(`${selected} selected`, `已选择 ${selected} 项`)}</strong><div>{children}</div><IconButton label={text("Clear selection", "清除选择")} onClick={onClear}><X size={16} /></IconButton></div>; }
export function Metric({ label, value, change, icon: Icon }: { label: string; value: ReactNode; change?: string; icon?: LucideIcon }) { return <div className="gj-metric">{Icon ? <Icon size={18} aria-hidden="true" /> : null}<span>{label}</span><strong>{value}</strong>{change ? <small>{change}</small> : null}</div>; }
export function Sparkline({ values, label }: { values: number[]; label?: string }) { const { text } = useLocale(); const points = useMemo(() => { if (!values.length) return ""; const min = Math.min(...values), max = Math.max(...values), spread = Math.max(1, max - min); return values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 100},${30 - ((value - min) / spread) * 28}`).join(" "); }, [values]); return <svg className="gj-sparkline" viewBox="0 0 100 32" role="img" aria-label={label ?? text("Trend", "趋势")} preserveAspectRatio="none"><polyline points={points} fill="none" vectorEffect="non-scaling-stroke" /></svg>; }
export function ChartFrame({ title, description, actions, children }: { title: string; description?: string; actions?: ReactNode; children: ReactNode }) { return <section className="gj-chart-frame"><header><div><h3>{title}</h3>{description ? <p>{description}</p> : null}</div>{actions}</header><div className="gj-chart-body">{children}</div></section>; }
export function SplitPane({ primary, secondary }: { primary: ReactNode; secondary: ReactNode }) { return <div className="gj-split-pane"><div>{primary}</div><aside>{secondary}</aside></div>; }
export function AppHeader({ context, actions }: { context: ReactNode; actions?: ReactNode }) { return <header className="gj-app-header"><div>{context}</div><div className="gj-app-header-actions">{actions}</div></header>; }
export function Sidebar({ brand, children, footer, collapsed = false }: { brand: ReactNode; children: ReactNode; footer?: ReactNode; collapsed?: boolean }) { return <aside className="gj-sidebar" data-collapsed={collapsed || undefined}><div className="gj-sidebar-brand">{brand}</div><nav className="gj-sidebar-nav">{children}</nav>{footer ? <div className="gj-sidebar-footer">{footer}</div> : null}</aside>; }
export function SidebarItem({ icon: Icon, label, active, onClick }: { icon: LucideIcon; label: string; active?: boolean; onClick?: () => void }) { return <button type="button" className="gj-sidebar-item" data-active={active || undefined} aria-current={active ? "page" : undefined} onClick={onClick}><Icon size={18} strokeWidth={1.75} aria-hidden="true" /><span>{label}</span></button>; }
export function WorkspaceSwitcher({ value, options, onChange }: { value: string; options: Array<{ value: string; label: string }>; onChange?: (value: string) => void }) { const { text } = useLocale(); return <select className="gj-workspace-switcher" value={value} onChange={(e) => onChange?.(e.target.value)} aria-label={text("Switch workspace", "切换工作区")}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>; }
export function Sheet({ triggerLabel, title, description, children }: { triggerLabel: string; title: string; description?: string; children: ReactNode }) { const { text } = useLocale(); return <BaseDialog.Root><BaseDialog.Trigger className="gj-button" data-variant="outline" data-size="md">{triggerLabel}</BaseDialog.Trigger><BaseDialog.Portal><BaseDialog.Backdrop className="gj-dialog-backdrop" /><BaseDialog.Viewport className="gj-sheet-viewport"><BaseDialog.Popup className="gj-sheet"><div className="gj-sheet-head"><div><BaseDialog.Title className="gj-dialog-title">{title}</BaseDialog.Title>{description ? <BaseDialog.Description className="gj-dialog-description">{description}</BaseDialog.Description> : null}</div><BaseDialog.Close render={<IconButton label={text("Close", "关闭")}><X size={16} /></IconButton>} /></div><div className="gj-sheet-body">{children}</div></BaseDialog.Popup></BaseDialog.Viewport></BaseDialog.Portal></BaseDialog.Root>; }
export function Command({ items, onSelect }: { items: Array<{ id: string; label: string; keywords?: string }>; onSelect?: (id: string) => void }) { const { text } = useLocale(); const id = useId(); const [query, setQuery] = useState(""); const filtered = items.filter((item) => `${item.label} ${item.keywords ?? ""}`.toLowerCase().includes(query.toLowerCase())); return <div className="gj-command"><label htmlFor={id}><Search size={16} aria-hidden="true" /><span className="sr-only">{text("Search commands", "搜索命令")}</span></label><Input id={id} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={text("Search commands…", "搜索命令…")} /> <div className="gj-command-list" role="listbox">{filtered.map((item) => <button key={item.id} type="button" role="option" onClick={() => onSelect?.(item.id)}>{item.label}</button>)}</div></div>; }
export function PageTitle({ children }: { children: ReactNode }) { return <h1 className="gj-page-title">{children}</h1>; }
export function PageActions({ children }: { children: ReactNode }) { return <div className="gj-page-actions">{children}</div>; }
export function Surface(props: HTMLAttributes<HTMLDivElement>) { return <div className="gj-surface" {...props} />; }
