import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@gojet/auth";
import { ApiError, DEFAULT_BIO_THEME, createBioClient, resourceAccess, type BioBlock, type BioPageInput, type BioPageRecord, type BioPageStatus, type BioTheme, type WorkspaceSummary } from "@gojet/api-client";
import { Alert, Badge, Button, EmptyState, ErrorState, Field, Input, Page, PageHeader, Select, Spinner, Textarea, useLocale } from "@gojet/ui";
import { AlertDialog, SideSheet } from "@gojet/ui/overlays";
import { errorMessage, formatDate, linksClient, normalizeWorkspaces, requestedWorkspaceId } from "../links/client";

const bioClient = createBioClient(api);
type Copy = (en: string, zh: string) => string;
function useWorkspace() { const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: async () => normalizeWorkspaces((await linksClient.workspaces()) as { data: WorkspaceSummary[] } | WorkspaceSummary[]) }); const requested = requestedWorkspaceId(); return { workspaces, workspace: workspaces.data?.find((item) => item.id === requested) ?? workspaces.data?.[0] }; }
function requestMessage(error: unknown, c: Copy) { if (!(error instanceof ApiError)) return null; const detail = errorMessage(error).toLowerCase(); if (error.status === 403 || /forbidden|无权|permission/.test(detail)) return [c("Permission denied", "没有操作权限"), c("Your current workspace role cannot perform this profile-page action.", "你当前的工作区角色无权执行该个人主页操作。")]; if (error.status === 429) return [c("Too many requests", "操作过于频繁"), c("Wait a moment and try again.", "请求过于频繁，请稍后再试。")]; if (error.status === 402 || error.status === 409 || (error.status === 422 && /(quota|limit|额度|套餐)/.test(detail))) return [c("Profile-page allowance reached", "个人主页额度不足"), c("This workspace has reached its current profile-page allowance.", "当前工作区的个人主页额度不足。")]; if (error.status === 503) return [c("Profile-page service unavailable", "个人主页服务暂时不可用"), c("The service cannot complete this request right now.", "个人主页服务当前无法完成请求，请稍后重试。")]; return null; }
function statusLabel(status: BioPageStatus, c: Copy) { return ({ draft: c("Draft", "草稿"), published: c("Published", "已发布"), paused: c("Paused", "已暂停") } as Record<BioPageStatus,string>)[status]; }
function statusTone(status: BioPageStatus): "success"|"warning"|"neutral" { return status === "published" ? "success" : status === "paused" ? "warning" : "neutral"; }
function themeValue(theme: BioTheme, key: keyof BioTheme, fallback: string) { return theme[key] || fallback; }

function BioForm({ workspaceId, page, onDone, c }: { workspaceId: number; page?: BioPageRecord; onDone: () => void; c: Copy }) {
  const editing = Boolean(page); const initialTheme = useMemo(() => page?.theme ?? DEFAULT_BIO_THEME, [page]); const [slug, setSlug] = useState(page?.slug ?? ""); const [title, setTitle] = useState(page?.title ?? ""); const [bio, setBio] = useState(page?.bio ?? ""); const [status, setStatus] = useState<BioPageStatus>(page?.status ?? "draft"); const [primary, setPrimary] = useState(themeValue(initialTheme, "Primary", DEFAULT_BIO_THEME.Primary)); const [background, setBackground] = useState(themeValue(initialTheme, "Background", DEFAULT_BIO_THEME.Background)); const [ink, setInk] = useState(themeValue(initialTheme, "Ink", DEFAULT_BIO_THEME.Ink ?? "#14231d")); const [surface, setSurface] = useState(themeValue(initialTheme, "Surface", DEFAULT_BIO_THEME.Surface ?? "#ffffff")); const [blocks, setBlocks] = useState<BioBlock[]>(page?.blocks?.length ? page.blocks : [{ Label: "", URL: "" }]);
  const input = (): BioPageInput => ({ ...(editing ? {} : slug.trim() ? { slug: slug.trim() } : {}), title: title.trim(), bio: bio.trim(), status, theme: { Primary: primary, Background: background, Ink: ink, Surface: surface }, blocks: blocks.map((item) => ({ Label: item.Label.trim(), URL: item.URL.trim() })).filter((item) => item.Label && item.URL) });
  const mutation = useMutation({ mutationFn: () => editing ? bioClient.update(workspaceId, page!.id, input()) : bioClient.create(workspaceId, input()), onSuccess: onDone }); const message = requestMessage(mutation.error, c); const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim()) mutation.mutate(); };
  const setBlock = (index: number, key: keyof BioBlock, value: string) => setBlocks((current) => current.map((item, position) => position === index ? { ...item, [key]: value } : item));
  return <form className="bio-editor-form" onSubmit={submit}>{message ? <Alert tone="danger" title={message[0]}>{message[1]}</Alert> : mutation.isError ? <Alert tone="danger" title={c("Save failed", "保存失败")}>{errorMessage(mutation.error)}</Alert> : null}
    {!editing ? <Field label={c("Public slug", "公开短码")} htmlFor="bio-slug" help={c("Optional. Leave blank to generate one automatically.", "可选；留空时由系统自动生成。")}> <Input id="bio-slug" value={slug} onChange={(event) => setSlug(event.target.value)} maxLength={64}/></Field> : null}
    <Field label={c("Page title", "主页标题")} htmlFor="bio-title" required><Input id="bio-title" value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} required/></Field>
    <Field label={c("Introduction", "简介")} htmlFor="bio-description"><Textarea id="bio-description" rows={4} value={bio} onChange={(event) => setBio(event.target.value)} maxLength={1000}/></Field>
    <Field label={c("Publishing status", "发布状态")} htmlFor="bio-status"><Select id="bio-status" value={status} onChange={(event) => setStatus(event.target.value as BioPageStatus)}><option value="draft">{c("Draft", "草稿")}</option><option value="published">{c("Published", "已发布")}</option><option value="paused">{c("Paused", "已暂停")}</option></Select></Field>
    <fieldset className="commerce-periods"><legend>{c("Appearance", "外观")}</legend><div className="links-form-grid"><Field label={c("Primary color", "主色")} htmlFor="bio-primary"><Input id="bio-primary" type="color" value={primary} onChange={(event) => setPrimary(event.target.value)}/></Field><Field label={c("Background", "背景色")} htmlFor="bio-background"><Input id="bio-background" type="color" value={background} onChange={(event) => setBackground(event.target.value)}/></Field><Field label={c("Text color", "文字颜色")} htmlFor="bio-ink"><Input id="bio-ink" type="color" value={ink} onChange={(event) => setInk(event.target.value)}/></Field><Field label={c("Card color", "卡片颜色")} htmlFor="bio-surface"><Input id="bio-surface" type="color" value={surface} onChange={(event) => setSurface(event.target.value)}/></Field></div></fieldset>
    <fieldset className="commerce-periods"><legend>{c("Links", "主页链接")}</legend><div className="link-rule-list">{blocks.map((block, index) => <div className="link-rule-row" key={index}><Input aria-label={c(`Link ${index + 1} label`, `链接 ${index + 1} 名称`)} value={block.Label} onChange={(event) => setBlock(index, "Label", event.target.value)} placeholder={c("Label", "名称")}/><Input aria-label={c(`Link ${index + 1} URL`, `链接 ${index + 1} 地址`)} type="url" value={block.URL} onChange={(event) => setBlock(index, "URL", event.target.value)} placeholder="https://…"/><Button type="button" size="sm" variant="ghost" onClick={() => setBlocks((current) => current.filter((_, position) => position !== index))}>{c("Remove", "移除")}</Button></div>)}</div><Button type="button" variant="outline" onClick={() => setBlocks((current) => [...current, { Label: "", URL: "" }])}>{c("Add link", "添加链接")}</Button></fieldset>
    <Button type="submit" loading={mutation.isPending}>{editing ? c("Save changes", "保存修改") : c("Create profile page", "创建个人主页")}</Button>
  </form>;
}

export default function BioPageV503() {
  const { locale } = useLocale(); const c: Copy = (en, cn) => locale === "zh-CN" ? cn : en; const { workspaces, workspace } = useWorkspace(); const queryClient = useQueryClient(); const workspaceId = workspace?.id; const list = useQuery({ queryKey: ["bio-pages", workspaceId], queryFn: () => bioClient.list(workspaceId!), enabled: Boolean(workspaceId) }); const remove = useMutation({ mutationFn: (id: number) => bioClient.delete(workspaceId!, id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["bio-pages", workspaceId] }) });
  if (workspaces.isPending) return <Page><div className="workspace-centered"><Spinner label={c("Loading workspace", "正在读取工作区")}/></div></Page>; if (workspaces.isError) return <Page><ErrorState title={c("Unable to load workspace", "无法读取工作区")} description={errorMessage(workspaces.error)}/></Page>; if (!workspace) return <Page><EmptyState title={c("No workspace", "还没有工作区")} description={c("Create or join a workspace before creating public profile pages.", "创建或加入工作区后才能创建公开个人主页。")}/></Page>;
  const access = resourceAccess(workspace.role); const items = list.data?.data ?? []; const refresh = () => queryClient.invalidateQueries({ queryKey: ["bio-pages", workspace.id] });
  return <Page className="bio-page" data-v503-bio><PageHeader title={c("Profile pages", "个人主页")} description={c(`Create and manage public profile pages in ${workspace.name}.`, `在 ${workspace.name} 中创建和管理公开个人主页。`)} actions={access.can_edit ? <SideSheet triggerLabel={c("New profile page", "新建个人主页")} title={c("Create profile page", "创建个人主页")} description={c("Set the public title, appearance and links, then choose when the page should be published.", "设置公开标题、页面外观和链接，然后选择何时发布。")}> <BioForm workspaceId={workspace.id} onDone={refresh} c={c}/></SideSheet> : undefined}/>
    {!access.can_edit ? <Alert tone="warning" title={c("Read-only profile pages", "个人主页只读")}>{c("Your current workspace role can view pages but cannot create, edit or delete them.", "你当前的工作区角色可以查看个人主页，但不能创建、编辑或删除。")}</Alert> : null}{remove.isError ? <Alert tone="danger" title={c("Delete failed", "删除失败")}>{errorMessage(remove.error)}</Alert> : null}
    {list.isPending ? <div className="workspace-centered"><Spinner label={c("Loading profile pages", "正在加载个人主页")}/></div> : list.isError ? <ErrorState title={c("Unable to load profile pages", "无法加载个人主页")} description={errorMessage(list.error)} action={<Button onClick={() => list.refetch()}>{c("Retry", "重试")}</Button>}/> : items.length ? <div className="commerce-plan-grid">{items.map((item) => <article className="commerce-plan-card" key={item.id}><div className="commerce-plan-head"><div><span>/{item.slug}</span><h2>{item.title}</h2></div><Badge tone={statusTone(item.status)}>{statusLabel(item.status, c)}</Badge></div><p>{item.bio || c("No introduction", "暂无简介")}</p><dl className="commerce-plan-meta"><div><dt>{c("Links", "链接")}</dt><dd>{item.blocks.length}</dd></div><div><dt>{c("Views", "访问次数")}</dt><dd>{item.views}</dd></div><div><dt>{c("Created", "创建时间")}</dt><dd>{formatDate(item.created_at)}</dd></div></dl><div className="commerce-actions">{item.status === "published" ? <a className="gj-button" data-variant="outline" data-size="md" href={bioClient.publicUrl(item.slug)} target="_blank" rel="noreferrer">{c("Open page", "打开主页")}</a> : null}{access.can_edit ? <SideSheet triggerLabel={c("Edit", "编辑")} title={c("Edit profile page", "编辑个人主页")} description={c("Update the public content, appearance and publishing state.", "修改公开内容、页面外观和发布状态。")}> <BioForm workspaceId={workspace.id} page={item} onDone={refresh} c={c}/></SideSheet> : null}{access.can_edit ? <AlertDialog triggerLabel={c("Delete", "删除")} title={c("Delete this profile page?", "删除这个个人主页？")} description={c("Its public URL will stop working after deletion.", "删除后，这个公开主页地址将停止访问。") } confirmLabel={c("Delete", "确认删除")} onConfirm={() => remove.mutate(item.id)}/> : null}</div></article>)}</div> : <EmptyState title={c("No profile pages", "还没有个人主页")} description={c("Create a page when you need one stable public profile address for multiple links.", "需要用一个固定公开地址集中展示多个链接时，可以创建第一个个人主页。")}/>} </Page>;
}
