import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@gojet/auth";
import { createWorkspaceClient, type WorkspaceRole, type WorkspaceSummary } from "@gojet/api-client";
import { Alert, Badge, Button, EmptyState, ErrorState, Field, Input, Page, PageHeader, Select, Spinner, useLocale } from "@gojet/ui";
import { AlertDialog, SideSheet } from "@gojet/ui/overlays";
import { errorMessage, formatDate, linksClient, normalizeWorkspaces, requestedWorkspaceId } from "../links/client";

const workspaceClient = createWorkspaceClient(api);
const assignableRoles: Exclude<WorkspaceRole, "owner">[] = ["admin", "editor", "analyst", "viewer"];
type Copy = (en: string, zh: string) => string;
function useWorkspace() { const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: async () => normalizeWorkspaces((await linksClient.workspaces()) as { data: WorkspaceSummary[] } | WorkspaceSummary[]) }); const requested = requestedWorkspaceId(); return { workspaces, workspace: workspaces.data?.find((item) => item.id === requested) ?? workspaces.data?.[0] }; }
function roleLabel(role: WorkspaceRole, c: Copy) { return ({ owner: c("Owner", "所有者"), admin: c("Administrator", "管理员"), editor: c("Editor", "编辑者"), analyst: c("Analyst", "分析员"), viewer: c("Viewer", "查看者") } as Record<WorkspaceRole,string>)[role]; }
function statusLabel(status: string, c: Copy) { const value = status.toLowerCase(); if (value === "active") return c("Active", "正常"); if (value === "pending") return c("Pending", "等待接受"); if (value === "revoked") return c("Revoked", "已撤销"); if (value === "expired") return c("Expired", "已过期"); return status; }

function InviteForm({ workspaceId, onDone, c }: { workspaceId: number; onDone: () => void; c: Copy }) {
  const [email, setEmail] = useState(""); const [role, setRole] = useState<Exclude<WorkspaceRole,"owner">>("viewer"); const mutation = useMutation({ mutationFn: () => workspaceClient.invite(workspaceId, email.trim(), role), onSuccess: () => { setEmail(""); setRole("viewer"); onDone(); } }); const submit = (event: FormEvent) => { event.preventDefault(); if (email.trim()) mutation.mutate(); };
  return <form className="members-invite-form" onSubmit={submit}>{mutation.isError ? <Alert tone="danger" title={c("Invitation failed", "邀请失败")}>{errorMessage(mutation.error)}</Alert> : null}<Field label={c("Email address", "邮箱地址")} htmlFor="member-email" required><Input id="member-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required/></Field><Field label={c("Role", "角色")} htmlFor="member-role"><Select id="member-role" value={role} onChange={(event) => setRole(event.target.value as Exclude<WorkspaceRole,"owner">)}>{assignableRoles.map((item) => <option key={item} value={item}>{roleLabel(item, c)}</option>)}</Select></Field><p className="links-muted">{c("The invited person receives the selected workspace role after accepting the invitation.", "对方接受邀请后，会以所选角色加入当前工作区。")}</p><Button type="submit" loading={mutation.isPending}>{c("Send invitation", "发送邀请")}</Button></form>;
}

export default function MembersPageV503() {
  const { locale } = useLocale(); const c: Copy = (en, cn) => locale === "zh-CN" ? cn : en; const { workspaces, workspace } = useWorkspace(); const queryClient = useQueryClient(); const workspaceId = workspace?.id; const query = useQuery({ queryKey: ["workspace-members", workspaceId], queryFn: () => workspaceClient.members(workspaceId!), enabled: Boolean(workspaceId) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["workspace-members", workspaceId] }); const changeRole = useMutation({ mutationFn: ({ userId, role }: { userId: number; role: Exclude<WorkspaceRole,"owner"> }) => workspaceClient.changeRole(workspaceId!, userId, role), onSuccess: refresh }); const remove = useMutation({ mutationFn: (userId: number) => workspaceClient.removeMember(workspaceId!, userId), onSuccess: refresh }); const resend = useMutation({ mutationFn: (id: number) => workspaceClient.resendInvitation(workspaceId!, id), onSuccess: refresh }); const revoke = useMutation({ mutationFn: (id: number) => workspaceClient.revokeInvitation(workspaceId!, id), onSuccess: refresh });
  if (workspaces.isPending) return <Page><div className="workspace-centered"><Spinner label={c("Loading workspace", "正在读取工作区")}/></div></Page>; if (workspaces.isError) return <Page><ErrorState title={c("Unable to load workspace", "无法读取工作区")} description={errorMessage(workspaces.error)}/></Page>; if (!workspace) return <Page><EmptyState title={c("No workspace", "还没有工作区")} description={c("Create or join a workspace before managing members.", "创建或加入工作区后才能管理成员。")}/></Page>;
  const canManage = workspace.role === "owner" || workspace.role === "admin"; const data = query.data; const error = changeRole.error ?? remove.error ?? resend.error ?? revoke.error;
  return <Page className="members-page" data-v503-members><PageHeader title={c("Members", "成员")} description={c(`Manage people and invitations for ${workspace.name}.`, `管理 ${workspace.name} 的成员与邀请。`)} actions={canManage ? <SideSheet triggerLabel={c("Invite member", "邀请成员")} title={c("Invite member", "邀请成员")} description={c("Invite a person by email and choose the minimum role they need.", "通过邮箱邀请成员，并为其分配完成工作所需的最小权限角色。")}> <InviteForm workspaceId={workspace.id} onDone={refresh} c={c}/></SideSheet> : undefined}/>
    {!canManage ? <Alert tone="warning" title={c("Member management is read-only", "成员管理只读")}>{c("Only workspace owners and administrators can invite members or change roles.", "只有工作区所有者和管理员可以邀请成员或调整角色。")}</Alert> : null}{error ? <Alert tone="danger" title={c("Member action failed", "成员操作失败")}>{errorMessage(error)}</Alert> : null}
    {query.isPending ? <div className="workspace-centered"><Spinner label={c("Loading members", "正在加载成员")}/></div> : query.isError ? <ErrorState title={c("Unable to load members", "无法加载成员")} description={errorMessage(query.error)} action={<Button onClick={() => query.refetch()}>{c("Retry", "重试")}</Button>}/> : data ? <><section className="workspace-section"><div className="workspace-section-head"><div><h2>{c("Current members", "当前成员")}</h2><p>{c("Roles control what each member can view and change in this workspace.", "成员角色决定其在当前工作区可以查看和修改的内容。")}</p></div><Badge tone="neutral">{data.members.length}</Badge></div>{data.members.length ? <div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>{c("Member", "成员")}</th><th>{c("Role", "角色")}</th><th>{c("Status", "状态")}</th><th>{c("Joined", "加入时间")}</th><th>{c("Actions", "操作")}</th></tr></thead><tbody>{data.members.map((member) => <tr key={member.user_id}><td><strong>{member.DisplayName || member.Email}</strong><small>{member.Email}</small></td><td>{canManage && member.Role !== "owner" ? <Select aria-label={c(`Role for ${member.Email}`, `${member.Email} 的角色`)} value={member.Role} onChange={(event) => changeRole.mutate({ userId: member.user_id, role: event.target.value as Exclude<WorkspaceRole,"owner"> })}>{assignableRoles.map((item) => <option key={item} value={item}>{roleLabel(item,c)}</option>)}</Select> : roleLabel(member.Role,c)}</td><td><Badge tone={member.Status === "active" ? "success" : "neutral"}>{statusLabel(member.Status,c)}</Badge></td><td>{formatDate(member.joined_at)}</td><td>{canManage && member.Role !== "owner" ? <AlertDialog triggerLabel={c("Remove", "移除")} title={c("Remove this member?", "移除这个成员？")} description={c("The member will lose access to this workspace.", "该成员将失去当前工作区的访问权限。") } confirmLabel={c("Remove member", "确认移除")} onConfirm={() => remove.mutate(member.user_id)}/> : "—"}</td></tr>)}</tbody></table></div> : <EmptyState title={c("No members", "暂无成员")} description={c("No active workspace members were returned.", "当前没有返回有效的工作区成员。")}/>}</section>
      <section className="workspace-section"><div className="workspace-section-head"><div><h2>{c("Pending invitations", "待处理邀请")}</h2><p>{c("Invitations can be resent or revoked before they are accepted.", "邀请被接受前，可以重新发送或撤销。")}</p></div><Badge tone="neutral">{data.invitations.length}</Badge></div>{data.invitations.length ? <div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>{c("Email", "邮箱")}</th><th>{c("Role", "角色")}</th><th>{c("Status", "状态")}</th><th>{c("Expires", "有效期")}</th><th>{c("Actions", "操作")}</th></tr></thead><tbody>{data.invitations.map((item) => <tr key={item.id}><td>{item.Email}</td><td>{roleLabel(item.Role,c)}</td><td><Badge tone={item.Status === "pending" ? "warning" : "neutral"}>{statusLabel(item.Status,c)}</Badge></td><td>{formatDate(item.ExpiresAt)}</td><td>{canManage ? <div className="workspace-card-actions"><Button size="sm" variant="outline" loading={resend.isPending} onClick={() => resend.mutate(item.id)}>{c("Resend", "重新发送")}</Button><AlertDialog triggerLabel={c("Revoke", "撤销")} title={c("Revoke this invitation?", "撤销这个邀请？")} description={c("The existing invitation link will no longer be accepted.", "现有邀请链接将不再能够使用。") } confirmLabel={c("Revoke invitation", "确认撤销")} onConfirm={() => revoke.mutate(item.id)}/></div> : "—"}</td></tr>)}</tbody></table></div> : <EmptyState title={c("No pending invitations", "没有待处理邀请")} description={c("There are no invitations waiting for acceptance.", "当前没有等待接受的邀请。")}/>}</section></> : null}
  </Page>;
}
