import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@gojet/auth";
import { ApiError, createTextClient, resourceAccess, type TextShareFormat, type TextShareRecord, type TextShareStatus, type WorkspaceSummary } from "@gojet/api-client";
import { Alert, Badge, Button, Checkbox, EmptyState, ErrorState, Field, Input, Page, PageHeader, Select, Spinner, Textarea, useLocale } from "@gojet/ui";
import { AlertDialog, SideSheet } from "@gojet/ui/overlays";
import { errorMessage, formatDate, linksClient, normalizeWorkspaces, requestedWorkspaceId } from "../links/client";

const textClient = createTextClient(api);
type Copy = (en: string, zh: string) => string;
type RequestMessage = [title: string, description: string];
function useWorkspace() { const workspaces = useQuery({ queryKey: ["workspaces"], queryFn: async () => normalizeWorkspaces((await linksClient.workspaces()) as { data: WorkspaceSummary[] } | WorkspaceSummary[]) }); const requested = requestedWorkspaceId(); return { workspaces, workspace: workspaces.data?.find((item) => item.id === requested) ?? workspaces.data?.[0] }; }
function expiryInput(value?: string | null) { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.valueOf())) return ""; const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function requestMessage(error: unknown, c: Copy): RequestMessage | null { if (!(error instanceof ApiError)) return null; const detail = errorMessage(error).toLowerCase(); if (error.status === 403) return [c("Permission denied", "没有操作权限"), c("Your current workspace role cannot perform this text action.", "你当前的工作区角色无权执行该文本操作。")]; if (error.status === 429) return [c("Too many requests", "操作过于频繁"), c("Wait a moment and try again.", "请求过于频繁，请稍后再试。")]; if (error.status === 402 || error.status === 409 || (error.status === 422 && /(quota|limit|额度|套餐)/.test(detail))) return [c("Text sharing allowance reached", "文本分享额度不足"), c("This workspace has reached its current text-sharing allowance.", "当前工作区的文本分享额度不足。")]; if (error.status === 503) return [c("Text sharing unavailable", "文本分享暂时不可用"), c("The text-sharing service cannot complete this request right now.", "文本分享服务当前无法完成请求，请稍后重试。")]; return null; }
function statusLabel(status: TextShareStatus, c: Copy) { return ({ active: c("Active", "正常"), paused: c("Paused", "已暂停"), consumed: c("Consumed", "已使用"), expired: c("Expired", "已过期") } as Record<TextShareStatus,string>)[status]; }
function statusTone(status: TextShareStatus): "success"|"warning"|"neutral" { return status === "active" ? "success" : status === "paused" ? "warning" : "neutral"; }

function TextForm({ workspaceId, item, onDone, c }: { workspaceId: number; item?: TextShareRecord; onDone: () => void; c: Copy }) {
  const editing = Boolean(item); const [slug, setSlug] = useState(item?.slug ?? ""); const [title, setTitle] = useState(item?.title ?? ""); const [content, setContent] = useState(item?.content ?? ""); const [format, setFormat] = useState<TextShareFormat>(item?.format ?? "plain"); const [status, setStatus] = useState<"active"|"paused">(item?.status === "paused" ? "paused" : "active"); const [expiresAt, setExpiresAt] = useState(expiryInput(item?.expires_at)); const [oneTime, setOneTime] = useState(item?.one_time ?? false); const [password, setPassword] = useState("");
  const mutation = useMutation({ mutationFn: async () => { if (editing) { await textClient.update(workspaceId, item!.id, { title: title.trim(), content, format, status, expires_at: expiresAt ? new Date(expiresAt).toISOString() : null, one_time: oneTime, ...(password ? { password } : {}) }); } else { await textClient.create(workspaceId, { ...(slug.trim() ? { slug: slug.trim() } : {}), title: title.trim(), content, format, expires_at: expiresAt ? new Date(expiresAt).toISOString() : null, one_time: oneTime, ...(password ? { password } : {}) }); } }, onSuccess: onDone });
  const message = requestMessage(mutation.error, c); const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim() && content.trim()) mutation.mutate(); };
  useEffect(() => { if (item?.content === undefined && item?.id) { void textClient.get(workspaceId, item.id).then((full) => setContent(full.content ?? "")); } }, [item?.content, item?.id, workspaceId]);
  return <form className="text-share-form" onSubmit={submit}>{message ? <Alert tone="danger" title={message[0]}>{message[1]}</Alert> : mutation.isError ? <Alert tone="danger" title={c("Save failed", "保存失败")}>{errorMessage(mutation.error)}</Alert> : null}
    {!editing ? <Field label={c("Public slug", "公开短码")} htmlFor="text-slug" help={c("Optional. Leave blank to generate one automatically.", "可选；留空时由系统自动生成。")}> <Input id="text-slug" value={slug} onChange={(event) => setSlug(event.target.value)} maxLength={64}/></Field> : null}
    <Field label={c("Title", "标题")} htmlFor="text-title" required><Input id="text-title" value={title} onChange={(event) => setTitle(event.target.value)} maxLength={255} required/></Field>
    <Field label={c("Display format", "展示格式")} htmlFor="text-format"><Select id="text-format" value={format} onChange={(event) => setFormat(event.target.value as TextShareFormat)}><option value="plain">{c("Plain text", "纯文本")}</option><option value="markdown">Markdown</option><option value="code">{c("Code", "代码")}</option></Select></Field>
    <Field label={c("Content", "内容")} htmlFor="text-content" required help={c("The saved content is published through the GoJet text-sharing page.", "保存后的内容会通过 GoJet 文本分享页面对外展示。")}> <Textarea id="text-content" rows={14} value={content} onChange={(event) => setContent(event.target.value)} required/></Field>
    <div className="links-form-grid"><Field label={c("Expiration", "有效期")} htmlFor="text-expiry"><Input id="text-expiry" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)}/></Field>{editing ? <Field label={c("Status", "状态")} htmlFor="text-status"><Select id="text-status" value={status} onChange={(event) => setStatus(event.target.value as "active"|"paused")}><option value="active">{c("Active", "正常")}</option><option value="paused">{c("Paused", "已暂停")}</option></Select></Field> : null}</div>
    <Field label={editing && item?.protected ? c("New password", "新密码") : c("Access password", "访问密码")} htmlFor="text-password" help={editing && item?.protected ? c("Leave blank to keep the existing password unchanged.", "留空可保持当前密码不变。") : c("Optional. Use at least 6 characters when enabled.", "可选；启用时至少设置 6 位密码。")}> <Input id="text-password" type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password"/></Field>
    <Checkbox label={c("One-time access", "一次性访问")} checked={oneTime} onCheckedChange={setOneTime}/><Button type="submit" loading={mutation.isPending}>{editing ? c("Save changes", "保存修改") : c("Create text share", "创建文本分享")}</Button></form>;
}

export default function TextPageV503() {
  const { locale } = useLocale(); const c: Copy = (en, cn) => locale === "zh-CN" ? cn : en; const { workspaces, workspace } = useWorkspace(); const queryClient = useQueryClient(); const workspaceId = workspace?.id; const list = useQuery({ queryKey: ["text-shares", workspaceId], queryFn: () => textClient.list(workspaceId!), enabled: Boolean(workspaceId) }); const remove = useMutation({ mutationFn: (id: number) => textClient.delete(workspaceId!, id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["text-shares", workspaceId] }) });
  if (workspaces.isPending) return <Page><div className="workspace-centered"><Spinner label={c("Loading workspace", "正在读取工作区")}/></div></Page>; if (workspaces.isError) return <Page><ErrorState title={c("Unable to load workspace", "无法读取工作区")} description={errorMessage(workspaces.error)}/></Page>; if (!workspace) return <Page><EmptyState title={c("No workspace", "还没有工作区")} description={c("Create or join a workspace before publishing text.", "创建或加入工作区后才能发布文本。")}/></Page>;
  const access = resourceAccess(workspace.role); const items = list.data?.data ?? []; const refresh = () => queryClient.invalidateQueries({ queryKey: ["text-shares", workspace.id] });
  return <Page className="text-page" data-v503-text><PageHeader title={c("Text sharing", "文本分享")} description={c(`Publish and manage text, Markdown and code pages in ${workspace.name}.`, `在 ${workspace.name} 中发布和管理纯文本、Markdown 与代码分享页面。`)} actions={access.can_edit ? <SideSheet triggerLabel={c("New text share", "新建文本分享")} title={c("Create text share", "创建文本分享")} description={c("Choose the display format and optional access limits, then publish a managed page.", "选择展示格式并按需要设置访问限制，然后发布可持续管理的文本页面。")}> <TextForm workspaceId={workspace.id} onDone={refresh} c={c}/></SideSheet> : undefined}/>
    {!access.can_edit ? <Alert tone="warning" title={c("Read-only text sharing", "文本分享只读")}>{c("Your current workspace role can view text shares but cannot create, edit or delete them.", "你当前的工作区角色可以查看文本分享，但不能创建、编辑或删除。")}</Alert> : null}{remove.isError ? <Alert tone="danger" title={c("Delete failed", "删除失败")}>{errorMessage(remove.error)}</Alert> : null}
    {list.isPending ? <div className="workspace-centered"><Spinner label={c("Loading text shares", "正在加载文本分享")}/></div> : list.isError ? <ErrorState title={c("Unable to load text shares", "无法加载文本分享")} description={errorMessage(list.error)} action={<Button onClick={() => list.refetch()}>{c("Retry", "重试")}</Button>}/> : items.length ? <div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>{c("Title", "标题")}</th><th>{c("Format", "格式")}</th><th>{c("Status", "状态")}</th><th>{c("Views", "访问次数")}</th><th>{c("Access", "访问限制")}</th><th>{c("Created", "创建时间")}</th><th>{c("Actions", "操作")}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>/{item.slug}</small></td><td>{item.format === "plain" ? c("Plain text", "纯文本") : item.format === "code" ? c("Code", "代码") : "Markdown"}</td><td><Badge tone={statusTone(item.status)}>{statusLabel(item.status, c)}</Badge></td><td>{item.views}</td><td>{[item.protected ? c("Password", "密码") : "", item.one_time ? c("One-time", "一次性") : "", item.expires_at ? c("Expires", "有有效期") : ""].filter(Boolean).join(" · ") || c("Open", "公开")}</td><td>{formatDate(item.created_at)}</td><td><div className="workspace-card-actions"><a className="gj-button" data-variant="outline" data-size="sm" href={textClient.publicUrl(item.slug)} target="_blank" rel="noreferrer">{c("Open", "打开")}</a>{access.can_edit ? <SideSheet triggerLabel={c("Edit", "编辑")} title={c("Edit text share", "编辑文本分享")} description={c("Update the content, status and access settings.", "修改内容、状态和访问设置。")}> <TextForm workspaceId={workspace.id} item={item} onDone={refresh} c={c}/></SideSheet> : null}{access.can_edit ? <AlertDialog triggerLabel={c("Delete", "删除")} title={c("Delete this text share?", "删除这个文本分享？")} description={c("Its public URL will stop working after deletion.", "删除后，这个公开文本地址将停止访问。") } confirmLabel={c("Delete", "确认删除")} onConfirm={() => remove.mutate(item.id)}/> : null}</div></td></tr>)}</tbody></table></div> : <EmptyState title={c("No text shares", "还没有文本分享")} description={c("Create the first text page when you need to share notes, Markdown or code.", "需要分享说明、Markdown 或代码时，可以创建第一个文本页面。")}/>} </Page>;
}
