package main

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base32"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const userSessionCookie="gojet_session"
const userCSRFCookie="gojet_csrf"

func sessionToken(r *http.Request)(string,bool){authorization:=strings.TrimSpace(r.Header.Get("Authorization"));if strings.HasPrefix(authorization,"Bearer "){token:=strings.TrimSpace(strings.TrimPrefix(authorization,"Bearer "));if token!=""{return token,false}};cookie,err:=r.Cookie(userSessionCookie);if err==nil&&strings.TrimSpace(cookie.Value)!=""{return strings.TrimSpace(cookie.Value),true};return "",false}
func secureRequest(r *http.Request)bool{if r.TLS!=nil{return true};return strings.EqualFold(strings.TrimSpace(strings.Split(r.Header.Get("X-Forwarded-Proto"),",")[0]),"https")}
func randomHex(n int)(string,error){raw:=make([]byte,n);if _,err:=rand.Read(raw);err!=nil{return "",err};return hex.EncodeToString(raw),nil}
func setCookieExpired(w http.ResponseWriter,r *http.Request,name string,httpOnly bool){http.SetCookie(w,&http.Cookie{Name:name,Value:"",Path:"/",HttpOnly:httpOnly,Secure:secureRequest(r),SameSite:http.SameSiteLaxMode,MaxAge:-1,Expires:time.Unix(1,0)})}
func clearUserAuthCookie(w http.ResponseWriter,r *http.Request){setCookieExpired(w,r,userSessionCookie,true)}
func clearUserSessionCookies(w http.ResponseWriter,r *http.Request){clearUserAuthCookie(w,r);setCookieExpired(w,r,userCSRFCookie,false)}
func (s *server)setUserSessionCookies(w http.ResponseWriter,r *http.Request,token string)string{secure:=secureRequest(r);http.SetCookie(w,&http.Cookie{Name:userSessionCookie,Value:token,Path:"/",HttpOnly:true,Secure:secure,SameSite:http.SameSiteLaxMode,MaxAge:30*24*60*60,Expires:time.Now().Add(30*24*time.Hour)});csrf,_:=randomHex(24);http.SetCookie(w,&http.Cookie{Name:userCSRFCookie,Value:csrf,Path:"/",HttpOnly:false,Secure:secure,SameSite:http.SameSiteLaxMode,MaxAge:30*24*60*60,Expires:time.Now().Add(30*24*time.Hour)});return csrf}
func (s *server)ensureCSRFCookie(w http.ResponseWriter,r *http.Request)string{if cookie,err:=r.Cookie(userCSRFCookie);err==nil&&len(cookie.Value)>=32{return cookie.Value};csrf,_:=randomHex(24);http.SetCookie(w,&http.Cookie{Name:userCSRFCookie,Value:csrf,Path:"/",HttpOnly:false,Secure:secureRequest(r),SameSite:http.SameSiteLaxMode,MaxAge:30*24*60*60,Expires:time.Now().Add(30*24*time.Hour)});return csrf}
func validCookieCSRF(r *http.Request)bool{if r.Method==http.MethodGet||r.Method==http.MethodHead||r.Method==http.MethodOptions{return true};cookie,err:=r.Cookie(userCSRFCookie);if err!=nil{return false};header:=strings.TrimSpace(r.Header.Get("X-CSRF-Token"));return header!=""&&len(header)==len(cookie.Value)&&subtle.ConstantTimeCompare([]byte(header),[]byte(cookie.Value))==1}
func (s *server)sessionSnapshot(w http.ResponseWriter,r *http.Request){csrf:=s.ensureCSRFCookie(w,r);token,_:=sessionToken(r);if token==""{jsonResponse(w,200,map[string]any{"authenticated":false,"csrfToken":csrf});return};user,err:=s.identity.Authenticate(r.Context(),token);if err!=nil{clearUserAuthCookie(w,r);jsonResponse(w,200,map[string]any{"authenticated":false,"csrfToken":csrf});return};jsonResponse(w,200,map[string]any{"authenticated":true,"identity":map[string]any{"id":user.ID,"email":user.Email,"displayName":user.DisplayName,"emailVerified":user.EmailVerified},"csrfToken":csrf})}
func sessionHash(token string)string{sum:=sha256.Sum256([]byte(token));return hex.EncodeToString(sum[:])}
func totpSecretKey(userID int64)string{return fmt.Sprintf("user.security.totp.%d",userID)}
func (s *server)userMFAEnabled(ctx context.Context,userID int64)bool{var enabled bool;if s.db.QueryRowContext(ctx,`SELECT enabled_at IS NOT NULL FROM user_mfa WHERE user_id=?`,userID).Scan(&enabled)!=nil{return false};return enabled}
func (s *server)createMFAChallenge(ctx context.Context,userID int64)(string,error){token,err:=randomHex(32);if err!=nil{return "",err};_,err=s.db.ExecContext(ctx,`INSERT INTO user_mfa_challenges(user_id,challenge_hash,expires_at) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 10 MINUTE))`,userID,sessionHash(token));return token,err}
func generateTOTPSecret()(string,error){raw:=make([]byte,20);if _,err:=rand.Read(raw);err!=nil{return "",err};return base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw),nil}
func totpCode(secret string,at time.Time)(string,error){key,err:=base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(strings.ToUpper(strings.ReplaceAll(strings.TrimSpace(secret)," ","")));if err!=nil{return "",err};counter:=uint64(at.Unix()/30);msg:=make([]byte,8);for i:=7;i>=0;i--{msg[i]=byte(counter);counter>>=8};mac:=hmac.New(sha1.New,key);_,_=mac.Write(msg);sum:=mac.Sum(nil);offset:=sum[len(sum)-1]&15;binary:=uint32(sum[offset]&127)<<24|uint32(sum[offset+1])<<16|uint32(sum[offset+2])<<8|uint32(sum[offset+3]);return fmt.Sprintf("%06d",binary%1000000),nil}
func verifyTOTP(secret,code string,now time.Time)bool{code=strings.TrimSpace(code);if len(code)!=6{return false};for _,delta:=range []int{-1,0,1}{expected,err:=totpCode(secret,now.Add(time.Duration(delta)*30*time.Second));if err==nil&&subtle.ConstantTimeCompare([]byte(expected),[]byte(code))==1{return true}};return false}
func backupHash(code string)string{sum:=sha256.Sum256([]byte(strings.ToUpper(strings.TrimSpace(code))));return hex.EncodeToString(sum[:])}
func generateBackupCodes()(codes []string,hashes []string,err error){for i:=0;i<10;i++{raw:=make([]byte,6);if _,err=rand.Read(raw);err!=nil{return};code:=strings.ToUpper(hex.EncodeToString(raw));codes=append(codes,code);hashes=append(hashes,backupHash(code))};return}
func (s *server)verifyUserMFA(ctx context.Context,userID int64,code string,consumeBackup bool)bool{secret,exists,err:=s.settings.Get(ctx,totpSecretKey(userID));if err!=nil||!exists{return false};if verifyTOTP(secret,code,time.Now().UTC()){return true};hash:=backupHash(code);if consumeBackup{result,err:=s.db.ExecContext(ctx,`UPDATE user_backup_codes SET used_at=UTC_TIMESTAMP() WHERE user_id=? AND code_hash=? AND used_at IS NULL`,userID,hash);if err==nil{n,_:=result.RowsAffected();return n==1};return false};var count int;_ = s.db.QueryRowContext(ctx,`SELECT COUNT(*) FROM user_backup_codes WHERE user_id=? AND code_hash=? AND used_at IS NULL`,userID,hash).Scan(&count);return count==1}
func (s *server)replaceBackupCodes(ctx context.Context,userID int64)([]string,error){codes,hashes,err:=generateBackupCodes();if err!=nil{return nil,err};tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return nil,err};defer tx.Rollback();if _,err=tx.ExecContext(ctx,`DELETE FROM user_backup_codes WHERE user_id=?`,userID);err!=nil{return nil,err};for _,hash:=range hashes{if _,err=tx.ExecContext(ctx,`INSERT INTO user_backup_codes(user_id,code_hash) VALUES(?,?)`,userID,hash);err!=nil{return nil,err}};if err=tx.Commit();err!=nil{return nil,err};return codes,nil}
func (s *server)loginMFA(w http.ResponseWriter,r *http.Request){var input struct{Challenge string `json:"challenge"`;Code string `json:"code"`};if decode(w,r,&input)!=nil{return};hash:=sessionHash(strings.TrimSpace(input.Challenge));tx,err:=s.db.BeginTx(r.Context(),nil);if err!=nil{jsonResponse(w,503,map[string]string{"error":"二次验证暂时不可用"});return};defer tx.Rollback();var id,userID int64;if err=tx.QueryRowContext(r.Context(),`SELECT id,user_id FROM user_mfa_challenges WHERE challenge_hash=? AND consumed_at IS NULL AND expires_at>UTC_TIMESTAMP() FOR UPDATE`,hash).Scan(&id,&userID);err!=nil{jsonResponse(w,422,map[string]string{"error":"二次验证请求无效或已过期"});return};if !s.verifyUserMFA(r.Context(),userID,input.Code,true){jsonResponse(w,401,map[string]string{"error":"验证码或备用恢复码无效"});return};if _,err=tx.ExecContext(r.Context(),`UPDATE user_mfa_challenges SET consumed_at=UTC_TIMESTAMP() WHERE id=?`,id);err!=nil{jsonResponse(w,503,map[string]string{"error":"二次验证暂时不可用"});return};if err=tx.Commit();err!=nil{jsonResponse(w,503,map[string]string{"error":"二次验证暂时不可用"});return};user,token,err:=s.identity.IssueSession(r.Context(),userID,clientIP(r),r.UserAgent());if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法创建登录会话"});return};csrf:=s.setUserSessionCookies(w,r,token);jsonResponse(w,200,map[string]any{"user":user,"csrfToken":csrf})}
func (s *server)mySecurity(w http.ResponseWriter,r *http.Request){u:=currentUser(r);enabled:=s.userMFAEnabled(r.Context(),u.ID);var backups int;_ = s.db.QueryRowContext(r.Context(),`SELECT COUNT(*) FROM user_backup_codes WHERE user_id=? AND used_at IS NULL`,u.ID).Scan(&backups);jsonResponse(w,200,map[string]any{"totp_enabled":enabled,"backup_codes_remaining":backups})}
func (s *server)beginMyTOTP(w http.ResponseWriter,r *http.Request){u:=currentUser(r);if s.userMFAEnabled(r.Context(),u.ID){jsonResponse(w,http.StatusConflict,map[string]string{"error":"两步验证已经启用，请先关闭后再重新设置"});return};secret,err:=generateTOTPSecret();if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法生成验证器密钥"});return};if err=s.settings.Set(r.Context(),totpSecretKey(u.ID),secret,true);err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法保存验证器密钥"});return};if _,err=s.db.ExecContext(r.Context(),`INSERT INTO user_mfa(user_id,enabled_at) VALUES(?,NULL) ON DUPLICATE KEY UPDATE enabled_at=NULL`,u.ID);err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法开始两步验证"});return};issuer:="GoJet";uri:="otpauth://totp/"+url.PathEscape(issuer+":"+u.Email)+"?secret="+url.QueryEscape(secret)+"&issuer="+url.QueryEscape(issuer)+"&algorithm=SHA1&digits=6&period=30";jsonResponse(w,200,map[string]any{"secret":secret,"otpauth_uri":uri})}
func (s *server)enableMyTOTP(w http.ResponseWriter,r *http.Request){var input struct{Code string `json:"code"`};if decode(w,r,&input)!=nil{return};u:=currentUser(r);secret,exists,err:=s.settings.Get(r.Context(),totpSecretKey(u.ID));if err!=nil||!exists||!verifyTOTP(secret,input.Code,time.Now().UTC()){jsonResponse(w,422,map[string]string{"error":"验证器验证码无效"});return};tx,err:=s.db.BeginTx(r.Context(),nil);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法启用两步验证"});return};defer tx.Rollback();result,err:=tx.ExecContext(r.Context(),`UPDATE user_mfa SET enabled_at=UTC_TIMESTAMP() WHERE user_id=? AND enabled_at IS NULL`,u.ID);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法启用两步验证"});return};n,_:=result.RowsAffected();if n!=1{jsonResponse(w,409,map[string]string{"error":"两步验证设置状态已变化，请刷新页面"});return};if err=tx.Commit();err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法启用两步验证"});return};codes,err:=s.replaceBackupCodes(r.Context(),u.ID);if err!=nil{_,_=s.db.ExecContext(r.Context(),`UPDATE user_mfa SET enabled_at=NULL WHERE user_id=?`,u.ID);jsonResponse(w,503,map[string]string{"error":"备用恢复码生成失败，两步验证未完成"});return};jsonResponse(w,200,map[string]any{"enabled":true,"backup_codes":codes})}
func (s *server)regenerateMyBackupCodes(w http.ResponseWriter,r *http.Request){var input struct{Code string `json:"code"`};if decode(w,r,&input)!=nil{return};u:=currentUser(r);secret,exists,err:=s.settings.Get(r.Context(),totpSecretKey(u.ID));if err!=nil||!exists||!verifyTOTP(secret,input.Code,time.Now().UTC()){jsonResponse(w,422,map[string]string{"error":"验证器验证码无效"});return};codes,err:=s.replaceBackupCodes(r.Context(),u.ID);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法更新备用恢复码"});return};jsonResponse(w,200,map[string]any{"backup_codes":codes})}
func (s *server)disableMyTOTP(w http.ResponseWriter,r *http.Request){var input struct{Code string `json:"code"`};if decode(w,r,&input)!=nil{return};u:=currentUser(r);if !s.verifyUserMFA(r.Context(),u.ID,input.Code,true){jsonResponse(w,422,map[string]string{"error":"验证码或备用恢复码无效"});return};tx,err:=s.db.BeginTx(r.Context(),nil);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法关闭两步验证"});return};defer tx.Rollback();if _,err=tx.ExecContext(r.Context(),`DELETE FROM user_backup_codes WHERE user_id=?`,u.ID);err==nil{_,err=tx.ExecContext(r.Context(),`DELETE FROM user_mfa WHERE user_id=?`,u.ID)};if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法关闭两步验证"});return};if err=tx.Commit();err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法关闭两步验证"});return};_,_=s.db.ExecContext(r.Context(),`DELETE FROM system_settings WHERE setting_key=?`,totpSecretKey(u.ID));jsonResponse(w,200,map[string]bool{"disabled":true})}
func (s *server)listMySessions(w http.ResponseWriter,r *http.Request){u:=currentUser(r);token,_:=sessionToken(r);current:=sessionHash(token);rows,err:=s.db.QueryContext(r.Context(),`SELECT id,COALESCE(ip_address,''),COALESCE(user_agent,''),COALESCE(last_seen_at,created_at),expires_at,created_at FROM user_sessions WHERE user_id=? AND revoked_at IS NULL AND expires_at>UTC_TIMESTAMP() ORDER BY created_at DESC`,u.ID);if err!=nil{jsonResponse(w,503,map[string]string{"error":"会话列表暂时不可用"});return};defer rows.Close();items:=[]map[string]any{};for rows.Next(){var id,ip,ua string;var last,expires,created time.Time;if rows.Scan(&id,&ip,&ua,&last,&expires,&created)==nil{items=append(items,map[string]any{"id":id,"ip_address":ip,"user_agent":ua,"last_active_at":last,"expires_at":expires,"created_at":created,"current":id==current})}};jsonResponse(w,200,map[string]any{"data":items})}
func (s *server)revokeMySession(w http.ResponseWriter,r *http.Request){u:=currentUser(r);id:=strings.TrimSpace(r.PathValue("session"));if len(id)!=64{jsonResponse(w,400,map[string]string{"error":"会话编号无效"});return};if _,err:=hex.DecodeString(id);err!=nil{jsonResponse(w,400,map[string]string{"error":"会话编号无效"});return};result,err:=s.db.ExecContext(r.Context(),`UPDATE user_sessions SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP()) WHERE id=? AND user_id=? AND revoked_at IS NULL`,id,u.ID);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法撤销会话"});return};n,_:=result.RowsAffected();if n==0{jsonResponse(w,404,map[string]string{"error":"会话不存在"});return};token,_:=sessionToken(r);if id==sessionHash(token){clearUserSessionCookies(w,r)};w.WriteHeader(204)}
func (s *server)revokeOtherMySessions(w http.ResponseWriter,r *http.Request){u:=currentUser(r);token,_:=sessionToken(r);current:=sessionHash(token);_,err:=s.db.ExecContext(r.Context(),`UPDATE user_sessions SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP()) WHERE user_id=? AND id<>? AND revoked_at IS NULL`,u.ID,current);if err!=nil{jsonResponse(w,503,map[string]string{"error":"暂时无法撤销其他会话"});return};jsonResponse(w,200,map[string]bool{"revoked":true})}
func (s *server)registerP15AccountRoutes(mux *http.ServeMux){mux.HandleFunc("GET /api/session",s.sessionSnapshot);mux.HandleFunc("POST /api/auth/login/2fa",s.loginMFA);mux.HandleFunc("GET /api/me/security",s.user(s.mySecurity));mux.HandleFunc("POST /api/me/totp/setup",s.user(s.beginMyTOTP));mux.HandleFunc("POST /api/me/totp/enable",s.user(s.enableMyTOTP));mux.HandleFunc("POST /api/me/totp/backup-codes",s.user(s.regenerateMyBackupCodes));mux.HandleFunc("DELETE /api/me/totp",s.user(s.disableMyTOTP));mux.HandleFunc("GET /api/me/sessions",s.user(s.listMySessions));mux.HandleFunc("DELETE /api/me/sessions",s.user(s.revokeOtherMySessions));mux.HandleFunc("DELETE /api/me/sessions/{session}",s.user(s.revokeMySession))}
