import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { ABDestination, LinkRecord, LinkWriteInput, RoutingDimension, RoutingRule, UTMValues } from "@gojet/api-client";
import { validateLinkRouting } from "@gojet/api-client";
import { Alert, Button, Checkbox, EmptyState, ErrorState, Field, Input, Select, SettingsSection, Spinner, useLocale } from "@gojet/ui";
import { AlertDialog } from "@gojet/ui/overlays";
import { errorMessage, formatDate, linksClient } from "./client";

type Copy = (en: string, zh: string) => string;
function useCopy(): Copy { const { locale } = useLocale(); return (en, zh) => locale === "zh-CN" ? zh : en; }

export interface EditorProps {
  link: LinkRecord;
  canEdit: boolean;
  save: (patch: Partial<LinkWriteInput>, reason: string) => void;
  pending: boolean;
  mutationError: unknown;
}

function validationMessage(message: string, c: Copy) {
  const table: Record<string, [string, string]> = {
    "路由规则不能超过 20 条": ["Routing rules cannot exceed 20 entries.", "路由规则不能超过 20 条。"],
    "每条路由规则都需要有效维度、匹配值和 HTTP(S) 目标地址": ["Each routing rule needs a valid dimension, match value and HTTP(S) destination.", "每条路由规则都需要有效维度、匹配值和 HTTP(S) 目标地址。"],
    "A/B 测试需要 2 到 10 个目标版本": ["A/B testing requires 2 to 10 destination variants.", "A/B 测试需要 2 到 10 个目标版本。"],
    "A/B 版本需要唯一编号、正权重和 HTTP(S) 目标地址": ["Each A/B variant needs a unique ID, positive weight and HTTP(S) destination.", "A/B 版本需要唯一编号、正权重和 HTTP(S) 目标地址。"],
    "A/B 版本权重总和必须为 100": ["A/B variant weights must total 100.", "A/B 版本权重总和必须为 100。"],
    "UTM 参数名称或长度无效": ["A UTM parameter name or value length is invalid.", "UTM 参数名称或长度无效。"]
  };
  const found = table[message]; return found ? c(found[0], found[1]) : message;
}

export function ReasonV503({ value, onChange, id = "change-reason" }: { value: string; onChange: (value: string) => void; id?: string }) {
  const c = useCopy();
  return <Field label={c("Reason for change", "变更原因")} htmlFor={id} required help={c("The reason is stored with the version history so later changes remain traceable.", "变更原因会与版本历史一并保存，便于后续追溯。")}> <Input id={id} value={value} maxLength={255} onChange={(event) => onChange(event.target.value)} placeholder={c("For example: update campaign destination", "例如：更新推广目标地址")} required /></Field>;
}

export function SummaryCardV503({ label, value }: { label: string; value: string | number }) { return <div className="link-summary-card"><span>{label}</span><strong>{value}</strong></div>; }

export function AnalyticsPanelV503({ workspaceId, linkId, canAnalytics }: { workspaceId: number; linkId: number; canAnalytics: boolean }) {
  const c = useCopy();
  const analytics = useQuery({ queryKey: ["link-analytics", workspaceId, linkId], queryFn: () => linksClient.analytics(workspaceId, linkId), enabled: canAnalytics });
  if (!canAnalytics) return <Alert tone="warning" title={c("Analytics permission required", "需要访问分析权限")}>{c("Your current workspace role cannot view link analytics.", "你当前的工作区角色无权查看短链接访问分析。")}</Alert>;
  if (analytics.isPending) return <div className="links-centered"><Spinner label={c("Loading analytics", "正在加载访问分析")} /></div>;
  if (analytics.isError) return <ErrorState title={c("Unable to load analytics", "无法读取访问分析")} description={errorMessage(analytics.error)} action={<Button type="button" onClick={() => analytics.refetch()}>{c("Retry", "重试")}</Button>} />;
  const data = analytics.data;
  const dimension = (titleEn: string, titleZh: string, values: Array<{ name: string; count: number }>) => <div className="link-dimension"><h3>{c(titleEn, titleZh)}</h3>{values.length ? values.slice(0, 8).map((item) => <div key={item.name}><span>{item.name || c("Unknown", "未知")}</span><strong>{item.count}</strong></div>) : <p>{c("No data", "暂无数据")}</p>}</div>;
  return <div className="link-panel-stack"><div className="link-summary-grid"><SummaryCardV503 label={c("Clicks", "访问次数")} value={data.clicks}/><SummaryCardV503 label={c("Unique visitors", "独立访客")} value={data.unique_visitors}/><SummaryCardV503 label={c("Automated traffic", "自动化流量")} value={data.bot_visits}/></div><div className="link-analytics-grid">{dimension("Sources", "来源", data.sources)}{dimension("Countries / regions", "国家或地区", data.countries)}{dimension("Devices", "设备", data.devices)}{dimension("Browsers", "浏览器", data.browsers)}</div>{data.recent.length ? <div className="link-history-list"><h3>{c("Recent visits", "最近访问")}</h3>{data.recent.slice(0, 20).map((event, index) => <div className="link-history-item" key={index}><code>{String(event.timestamp ?? "")}</code><span>{String(event.source ?? c("Unknown", "未知"))} · {String(event.country ?? "")} · {String(event.device ?? "")}</span></div>)}</div> : <EmptyState title={c("No visit events", "暂无访问记录")} description={c("There are no visits in the selected time range.", "当前时间范围内还没有访问记录。")}/>}</div>;
}

function normalizeRules(value: LinkRecord["routing_rules"]): RoutingRule[] { return (value ?? []).map((raw) => { const source = raw as RoutingRule & { dimension?: RoutingDimension; value?: string; destination?: string }; return { Dimension: source.Dimension ?? source.dimension ?? "country", Value: source.Value ?? source.value ?? "", Destination: source.Destination ?? source.destination ?? "" }; }); }

export function RoutingPanelV503({ link, canEdit, save, pending, mutationError }: EditorProps) {
  const c = useCopy(); const initial = useMemo(() => normalizeRules(link.routing_rules), [link.routing_rules]); const [rules, setRules] = useState<RoutingRule[]>(initial); const [reason, setReason] = useState(""); useEffect(() => setRules(initial), [initial]);
  const updateRule = (index: number, patch: Partial<RoutingRule>) => setRules((current) => current.map((rule, position) => position === index ? { ...rule, ...patch } : rule));
  const errors = validateLinkRouting({ routing_rules: rules });
  return <form className="link-editor" onSubmit={(event) => { event.preventDefault(); if (!errors.length && reason.trim()) save({ routing_rules: rules }, reason); }}><div className="link-editor-head"><div><h3>{c("Routing rules", "跳转规则")}</h3><p>{c("Send matching visits to different destinations by device, country or region, language, or source.", "可按设备、国家或地区、语言或来源，把符合条件的访问跳转到不同目标地址。")}</p></div>{canEdit ? <Button variant="outline" type="button" disabled={rules.length >= 20} onClick={() => setRules((current) => [...current, { Dimension: "country", Value: "", Destination: "" }])}>{c("Add rule", "添加规则")}</Button> : null}</div>{rules.length ? <div className="link-rule-list">{rules.map((rule, index) => <div className="link-rule-row" key={index}><Select aria-label={c(`Rule ${index + 1} dimension`, `规则 ${index + 1} 条件类型`)} value={rule.Dimension} disabled={!canEdit} onChange={(event) => updateRule(index, { Dimension: event.target.value as RoutingDimension })}><option value="device">{c("Device", "设备")}</option><option value="country">{c("Country / region", "国家或地区")}</option><option value="language">{c("Language", "语言")}</option><option value="source">{c("Source", "来源")}</option></Select><Input aria-label={c(`Rule ${index + 1} match value`, `规则 ${index + 1} 匹配值`)} value={rule.Value} disabled={!canEdit} onChange={(event) => updateRule(index, { Value: event.target.value })} placeholder={c("Match value", "匹配值")}/><Input aria-label={c(`Rule ${index + 1} destination`, `规则 ${index + 1} 目标地址`)} type="url" value={rule.Destination} disabled={!canEdit} onChange={(event) => updateRule(index, { Destination: event.target.value })} placeholder="https://…"/>{canEdit ? <Button size="sm" variant="ghost" type="button" onClick={() => setRules((current) => current.filter((_, position) => position !== index))}>{c("Remove", "移除")}</Button> : null}</div>)}</div> : <EmptyState title={c("No routing rules", "暂无跳转规则")} description={c("Visits that do not match a rule continue to the main destination.", "未命中规则的访问会继续跳转到主目标地址。")}/>} {errors.length ? <Alert tone="danger" title={c("Routing rules need attention", "跳转规则需要修正")}>{errors.map((item) => validationMessage(item, c)).join(" ")}</Alert> : null}{mutationError ? <Alert tone="danger" title={c("Unable to save routing rules", "无法保存跳转规则")}>{errorMessage(mutationError)}</Alert> : null}{canEdit ? <><ReasonV503 id="routing-reason" value={reason} onChange={setReason}/><div className="link-editor-actions"><Button type="submit" loading={pending} disabled={!reason.trim() || Boolean(errors.length)}>{c("Save routing rules", "保存跳转规则")}</Button></div></> : null}</form>;
}

function normalizeVariants(value: LinkRecord["ab_destinations"]): ABDestination[] { return (value ?? []).map((raw, index) => { const source = raw as ABDestination & { id?: string; destination?: string; weight?: number }; return { ID: source.ID ?? source.id ?? `v${index + 1}`, Destination: source.Destination ?? source.destination ?? "", Weight: Number(source.Weight ?? source.weight ?? 0) }; }); }

export function ABPanelV503({ link, canEdit, save, pending, mutationError }: EditorProps) {
  const c = useCopy(); const initial = useMemo(() => normalizeVariants(link.ab_destinations), [link.ab_destinations]); const [variants, setVariants] = useState<ABDestination[]>(initial); const [reason, setReason] = useState(""); useEffect(() => setVariants(initial), [initial]);
  const updateVariant = (index: number, patch: Partial<ABDestination>) => setVariants((current) => current.map((variant, position) => position === index ? { ...variant, ...patch } : variant)); const total = variants.reduce((sum, item) => sum + Number(item.Weight || 0), 0); const errors = validateLinkRouting({ ab_destinations: variants });
  return <form className="link-editor" onSubmit={(event) => { event.preventDefault(); if (!errors.length && reason.trim()) save({ ab_destinations: variants }, reason); }}><div className="link-editor-head"><div><h3>{c("A/B testing", "A/B 测试")}</h3><p>{c("Create 2–10 destination variants. Each variant needs a unique ID and the total weight must equal 100.", "创建 2–10 个目标版本。每个版本需要唯一编号，全部权重总和必须等于 100。")}</p></div>{canEdit ? <Button variant="outline" type="button" disabled={variants.length >= 10} onClick={() => setVariants((current) => [...current, { ID: `v${current.length + 1}`, Destination: "", Weight: current.length === 0 ? 50 : 1 }])}>{c("Add variant", "添加版本")}</Button> : null}</div><div className="link-ab-total" data-valid={total === 100 || undefined}>{c("Total weight", "权重总和")}: <strong>{total}%</strong></div>{variants.length ? <div className="link-rule-list">{variants.map((variant, index) => <div className="link-rule-row link-ab-row" key={`${variant.ID}-${index}`}><Input aria-label={c(`Variant ${index + 1} ID`, `版本 ${index + 1} 编号`)} value={variant.ID} disabled={!canEdit} onChange={(event) => updateVariant(index, { ID: event.target.value })} placeholder="v1"/><Input aria-label={c(`Variant ${index + 1} destination`, `版本 ${index + 1} 目标地址`)} type="url" value={variant.Destination} disabled={!canEdit} onChange={(event) => updateVariant(index, { Destination: event.target.value })} placeholder="https://…"/><Input aria-label={c(`Variant ${index + 1} weight`, `版本 ${index + 1} 权重`)} type="number" min={1} max={99} value={variant.Weight} disabled={!canEdit} onChange={(event) => updateVariant(index, { Weight: Number(event.target.value) })}/>{canEdit ? <Button size="sm" variant="ghost" type="button" onClick={() => setVariants((current) => current.filter((_, position) => position !== index))}>{c("Remove", "移除")}</Button> : null}</div>)}</div> : <EmptyState title={c("A/B testing is off", "A/B 测试未启用")} description={c("Add at least two destination variants to enable traffic splitting.", "至少添加两个目标版本后才能启用流量分配。")}/>} {errors.length && variants.length ? <Alert tone="danger" title={c("A/B settings need attention", "A/B 设置需要修正")}>{errors.map((item) => validationMessage(item, c)).join(" ")}</Alert> : null}{mutationError ? <Alert tone="danger" title={c("Unable to save A/B settings", "无法保存 A/B 设置")}>{errorMessage(mutationError)}</Alert> : null}{canEdit ? <><ReasonV503 id="ab-reason" value={reason} onChange={setReason}/><div className="link-editor-actions"><Button type="submit" loading={pending} disabled={!reason.trim() || !variants.length || Boolean(errors.length)}>{c("Save A/B settings", "保存 A/B 设置")}</Button>{variants.length ? <Button variant="outline" type="button" onClick={() => setVariants([])}>{c("Disable A/B testing", "关闭 A/B 测试")}</Button> : null}</div></> : null}</form>;
}

export function UTMPanelV503({ link, canEdit, save, pending, mutationError }: EditorProps) {
  const c = useCopy(); const [values, setValues] = useState<UTMValues>(link.utm ?? {}); const [reason, setReason] = useState(""); useEffect(() => setValues(link.utm ?? {}), [link.utm]);
  const preview = useMemo(() => { try { const url = new URL(link.destination); Object.entries(values).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); else url.searchParams.delete(key); }); return url.toString(); } catch { return link.destination; } }, [link.destination, values]); const set = (key: keyof UTMValues, value: string) => setValues((current) => ({ ...current, [key]: value }));
  return <form className="link-editor" onSubmit={(event) => { event.preventDefault(); if (reason.trim()) save({ utm: values }, reason); }}><h3>{c("UTM parameters", "UTM 参数")}</h3><div className="links-form-grid"><Field label={c("Source", "来源")} htmlFor="utm-source"><Input id="utm-source" disabled={!canEdit} value={values.utm_source ?? ""} onChange={(event) => set("utm_source", event.target.value)} maxLength={255}/></Field><Field label={c("Medium", "媒介")} htmlFor="utm-medium"><Input id="utm-medium" disabled={!canEdit} value={values.utm_medium ?? ""} onChange={(event) => set("utm_medium", event.target.value)} maxLength={255}/></Field><Field label={c("Campaign", "推广活动")} htmlFor="utm-campaign"><Input id="utm-campaign" disabled={!canEdit} value={values.utm_campaign ?? ""} onChange={(event) => set("utm_campaign", event.target.value)} maxLength={255}/></Field><Field label={c("Content", "内容")} htmlFor="utm-content"><Input id="utm-content" disabled={!canEdit} value={values.utm_content ?? ""} onChange={(event) => set("utm_content", event.target.value)} maxLength={255}/></Field><Field label={c("Term", "关键词")} htmlFor="utm-term"><Input id="utm-term" disabled={!canEdit} value={values.utm_term ?? ""} onChange={(event) => set("utm_term", event.target.value)} maxLength={255}/></Field></div><div className="link-preview"><span>{c("Destination preview", "目标地址预览")}</span><code>{preview}</code></div>{mutationError ? <Alert tone="danger" title={c("Unable to save UTM parameters", "无法保存 UTM 参数")}>{errorMessage(mutationError)}</Alert> : null}{canEdit ? <><ReasonV503 id="utm-reason" value={reason} onChange={setReason}/><div className="link-editor-actions"><Button type="submit" loading={pending} disabled={!reason.trim()}>{c("Save UTM parameters", "保存 UTM 参数")}</Button></div></> : null}</form>;
}

export function AccessPanelV503({ link, canEdit, save, pending, mutationError }: EditorProps) {
  const c = useCopy(); const [password, setPassword] = useState(""); const [clearPassword, setClearPassword] = useState(false); const [expiresAt, setExpiresAt] = useState(link.expires_at ? link.expires_at.slice(0, 16) : ""); const [maxClicks, setMaxClicks] = useState(link.max_clicks ? String(link.max_clicks) : ""); const [oneTime, setOneTime] = useState(link.one_time); const [reason, setReason] = useState("");
  useEffect(() => { setExpiresAt(link.expires_at ? link.expires_at.slice(0, 16) : ""); setMaxClicks(link.max_clicks ? String(link.max_clicks) : ""); setOneTime(link.one_time); setPassword(""); setClearPassword(false); }, [link]);
  return <form className="link-editor" onSubmit={(event) => { event.preventDefault(); if (!reason.trim()) return; const patch: Partial<LinkWriteInput> = { one_time: oneTime, expires_at: expiresAt ? new Date(expiresAt).toISOString() : null, max_clicks: maxClicks ? Number(maxClicks) : null }; if (password) patch.password = password; if (clearPassword) patch.clear_password = true; save(patch, reason); }}><SettingsSection title={c("Access controls", "访问控制")} description={c("Set a password, expiration time, click limit or one-time access when the link should not remain openly available.", "需要限制访问时，可以设置密码、有效期、访问次数上限或一次性访问。")}> <div className="links-form-grid"><Field label={c("New password", "新密码")} htmlFor="access-password" help={link.password_protected ? c("A password is currently enabled. Leave this blank to keep it unchanged.", "当前已启用密码；留空可保持不变。") : c("At least 6 characters.", "至少 6 位。")}> <Input id="access-password" type="password" minLength={6} disabled={!canEdit} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password"/></Field><Field label={c("Expiration", "有效期")} htmlFor="access-expiry"><Input id="access-expiry" type="datetime-local" disabled={!canEdit} value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)}/></Field><Field label={c("Maximum clicks", "访问次数上限")} htmlFor="access-max-clicks"><Input id="access-max-clicks" type="number" min={1} disabled={!canEdit} value={maxClicks} onChange={(event) => setMaxClicks(event.target.value)} placeholder={c("Unlimited", "不限制")}/></Field></div><Checkbox label={c("One-time link", "一次性链接")} checked={oneTime} disabled={!canEdit} onCheckedChange={setOneTime}/>{link.password_protected ? <Checkbox label={c("Remove current password", "移除当前密码")} checked={clearPassword} disabled={!canEdit || Boolean(password)} onCheckedChange={setClearPassword}/> : null}</SettingsSection>{mutationError ? <Alert tone="danger" title={c("Unable to save access controls", "无法保存访问控制")}>{errorMessage(mutationError)}</Alert> : null}{canEdit ? <><ReasonV503 id="access-reason" value={reason} onChange={setReason}/><div className="link-editor-actions"><Button type="submit" loading={pending} disabled={!reason.trim()}>{c("Save access controls", "保存访问控制")}</Button></div></> : null}</form>;
}

interface QROptions { format: "png" | "svg" | "pdf"; size: number; foreground?: string; background?: string; download?: boolean; }
export function QRPanelV503({ workspaceId, linkId, short }: { workspaceId: number; linkId: number; short: string }) {
  const c = useCopy(); const [foreground, setForeground] = useState(""); const [background, setBackground] = useState(""); const [size, setSize] = useState(768);
  const options = (format: QROptions["format"], download = false): QROptions => { const value: QROptions = { format, size }; if (foreground.trim()) value.foreground = foreground.trim(); if (background.trim()) value.background = background.trim(); if (download) value.download = true; return value; };
  const preview = linksClient.qrUrl(workspaceId, linkId, options("png"));
  return <div className="link-qr-layout"><div className="link-qr-preview"><img src={preview} alt={c(`QR code for ${short}`, `${short} 的二维码`)}/><code>{short}</code></div><div className="link-editor"><h3>{c("QR appearance and export", "二维码样式与导出")}</h3><div className="links-form-grid"><Field label={c("Foreground", "前景色")} htmlFor="qr-fg" help={c("Leave blank to use the default color, or enter a hexadecimal color value.", "留空使用默认颜色，也可以输入十六进制颜色值。")}> <Input id="qr-fg" value={foreground} onChange={(event) => setForeground(event.target.value)} placeholder={c("Default", "默认")}/></Field><Field label={c("Background", "背景色")} htmlFor="qr-bg" help={c("Leave blank to use the default background.", "留空使用默认背景色。")}> <Input id="qr-bg" value={background} onChange={(event) => setBackground(event.target.value)} placeholder={c("Default", "默认")}/></Field><Field label={c("Size", "尺寸")} htmlFor="qr-size"><Select id="qr-size" value={size} onChange={(event) => setSize(Number(event.target.value))}><option value={512}>512 px</option><option value={768}>768 px</option><option value={1024}>1024 px</option><option value={1600}>1600 px</option></Select></Field></div><div className="link-editor-actions">{(["png", "svg", "pdf"] as const).map((format) => <a key={format} className="gj-button" data-variant="outline" data-size="md" href={linksClient.qrUrl(workspaceId, linkId, options(format, true))}>{c(`Download ${format.toUpperCase()}`, `下载 ${format.toUpperCase()}`)}</a>)}</div><p className="links-muted">{c("The QR code points to this managed short URL, so later destination changes do not require replacing the printed code.", "二维码指向当前可管理的短网址；以后修改目标地址时，不需要更换已经发布或印刷的二维码。")}</p></div></div>;
}

export function SettingsPanelV503({ link, canEdit, save, pending, mutationError, workspaceId, onDeleted }: EditorProps & { workspaceId: number; onDeleted: () => void }) {
  const c = useCopy(); const [destination, setDestination] = useState(link.destination); const [title, setTitle] = useState(link.title); const [status, setStatus] = useState<LinkRecord["status"]>(link.status); const [redirect, setRedirect] = useState<LinkRecord["redirect_status"]>(link.redirect_status); const [reason, setReason] = useState(""); const remove = useMutation({ mutationFn: () => linksClient.bulkDelete(workspaceId, [link.id]), onSuccess: onDeleted }); useEffect(() => { setDestination(link.destination); setTitle(link.title); setStatus(link.status); setRedirect(link.redirect_status); }, [link]);
  return <div className="link-panel-stack" id="settings"><form className="link-editor" onSubmit={(event) => { event.preventDefault(); if (reason.trim()) save({ destination, title, status, redirect_status: redirect }, reason); }}><SettingsSection title={c("Link settings", "短链接设置")} description={c("The public short code and domain stay unchanged. Destination, title, status and redirect type are versioned when saved.", "公开短码和域名保持不变；目标地址、标题、状态和跳转类型保存后会进入版本记录。")}> <Field label={c("Destination", "目标地址")} htmlFor="settings-destination" required><Input id="settings-destination" type="url" disabled={!canEdit} value={destination} onChange={(event) => setDestination(event.target.value)} required/></Field><Field label={c("Title", "标题")} htmlFor="settings-title"><Input id="settings-title" disabled={!canEdit} value={title} onChange={(event) => setTitle(event.target.value)} maxLength={255}/></Field><div className="links-form-grid"><Field label={c("Link state", "链接状态")} htmlFor="settings-status"><Select id="settings-status" disabled={!canEdit} value={status} onChange={(event) => setStatus(event.target.value as LinkRecord["status"])}><option value="active">{c("Active", "活动")}</option><option value="paused">{c("Paused", "已暂停")}</option><option value="expired">{c("Expired", "已过期")}</option></Select></Field><Field label={c("Redirect type", "跳转类型")} htmlFor="settings-redirect"><Select id="settings-redirect" disabled={!canEdit} value={redirect} onChange={(event) => setRedirect(Number(event.target.value) as LinkRecord["redirect_status"])}><option value={301}>{c("301 · Permanent", "301 · 永久跳转")}</option><option value={302}>{c("302 · Temporary", "302 · 临时跳转")}</option><option value={307}>{c("307 · Temporary", "307 · 临时跳转")}</option><option value={308}>{c("308 · Permanent", "308 · 永久跳转")}</option></Select></Field></div></SettingsSection>{mutationError ? <Alert tone="danger" title={c("Unable to save link settings", "无法保存短链接设置")}>{errorMessage(mutationError)}</Alert> : null}{canEdit ? <><ReasonV503 id="settings-reason" value={reason} onChange={setReason}/><div className="link-editor-actions"><Button type="submit" loading={pending} disabled={!reason.trim()}>{c("Save settings", "保存设置")}</Button></div></> : null}</form>{canEdit ? <SettingsSection title={c("Delete link", "删除短链接")} description={c("Deleting the link stops the public short URL. Historical records remain available for audit and recovery controls where supported.", "删除后公开短网址将停止访问；历史记录仍会按系统审计与恢复规则保留。")}> {remove.isError ? <Alert tone="danger" title={c("Delete failed", "删除失败")}>{errorMessage(remove.error)}</Alert> : null}<AlertDialog triggerLabel={c("Delete link", "删除短链接")} title={c("Delete this link?", "确认删除这条短链接？")} description={c("The public short URL will stop working after deletion.", "删除后，这个公开短网址将停止访问。") } confirmLabel={c("Delete link", "确认删除")} onConfirm={() => remove.mutate()}/></SettingsSection> : null}</div>;
}

export function HistoryPanelV503({ workspaceId, linkId, canEdit }: { workspaceId: number; linkId: number; canEdit: boolean }) {
  const c = useCopy(); const queryClient = useQueryClient(); const history = useQuery({ queryKey: ["link-history", workspaceId, linkId], queryFn: () => linksClient.versions(workspaceId, linkId) }); const [reason, setReason] = useState(""); const restore = useMutation({ mutationFn: (revision: number) => linksClient.restore(workspaceId, linkId, revision, reason), onSuccess: async () => { setReason(""); await Promise.all([queryClient.invalidateQueries({ queryKey: ["link", workspaceId, linkId] }), queryClient.invalidateQueries({ queryKey: ["link-history", workspaceId, linkId] })]); } });
  if (history.isPending) return <div className="links-centered"><Spinner label={c("Loading history", "正在加载版本历史")} /></div>;
  if (history.isError) return <ErrorState title={c("Unable to load history", "无法读取版本历史")} description={errorMessage(history.error)} action={<Button type="button" onClick={() => history.refetch()}>{c("Retry", "重试")}</Button>}/>;
  if (!history.data.data.length) return <EmptyState title={c("No version history", "暂无版本历史")} description={c("This link does not have any saved revisions yet.", "当前短链接还没有已保存的版本记录。")}/>;
  return <div className="link-panel-stack">{canEdit ? <ReasonV503 id="restore-reason" value={reason} onChange={setReason}/> : null}{restore.isError ? <Alert tone="danger" title={c("Restore failed", "恢复失败")}>{errorMessage(restore.error)}</Alert> : null}<div className="link-history-list">{history.data.data.map((version) => <article className="link-history-item" key={version.id}><div><strong>{c(`Revision ${version.revision}`, `版本 ${version.revision}`)}</strong><span>{formatDate(version.created_at)} · {c(`operator #${version.created_by}`, `操作人 #${version.created_by}`)}</span></div><p>{version.change_reason}</p><details><summary>{c("Saved snapshot", "保存快照")}</summary><pre>{JSON.stringify(version.snapshot, null, 2)}</pre></details>{canEdit ? <Button size="sm" variant="outline" type="button" disabled={!reason.trim()} loading={restore.isPending} onClick={() => restore.mutate(version.revision)}>{c("Restore this revision", "恢复此版本")}</Button> : null}</article>)}</div></div>;
}
