<x-layouts.app :title="__('v3.files.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10" x-data="{ uploadOpen: false }">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="page-kicker">{{ $workspace->name }}</p><h1 class="page-title mt-1">{{ __('v3.files.title') }}</h1><p class="page-description">{{ __('v3.files.subtitle') }}</p></div><button class="btn-brand" @click="uploadOpen=!uploadOpen">＋ {{ __('v3.files.new') }}</button></div>

    <div x-cloak x-show="uploadOpen" class="panel mt-6" x-transition>
      <div class="flex items-center justify-between"><h2 class="text-xl font-bold">{{ __('v3.files.new') }}</h2><button class="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-xl" @click="uploadOpen=false">×</button></div>
      <form class="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]" method="post" action="{{ route('files.store') }}" enctype="multipart/form-data">@csrf
        <label class="grid min-h-72 cursor-pointer place-items-center rounded-3xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center transition hover:border-cyan-400 hover:bg-cyan-50/40"><div><div class="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-white text-3xl shadow-sm">⇧</div><p class="mt-5 font-bold text-slate-950">{{ __('v3.files.file') }}</p><p class="mt-2 text-sm text-slate-500">{{ __('v3.files.resumable') }} · {{ config('gojet.max_upload_mb') }} MB</p></div><input class="mt-6 block w-full text-sm" type="file" name="file" required></label>
        <div class="space-y-4"><div><label class="label">{{ __('v3.files.visibility') }}</label><select class="input" name="visibility"><option value="unlisted">{{ __('v3.texts.unlisted') }}</option><option value="public">{{ __('v3.texts.public') }}</option><option value="private">{{ __('v3.texts.private') }}</option></select></div><div><label class="label">{{ __('v3.files.password') }}</label><input class="input" type="password" name="password"></div><div><label class="label">{{ __('v3.files.expires_at') }}</label><input class="input" type="datetime-local" name="expires_at"></div><div><label class="label">{{ __('v3.files.max_downloads') }}</label><input class="input" type="number" min="1" name="max_downloads"></div><button class="btn-brand w-full py-3">{{ __('v3.common.upload') }}</button><p class="text-xs leading-5 text-slate-400">{{ __('v3.files.subtitle') }}</p></div>
      </form>
    </div>

    <form class="panel mt-6 flex flex-col gap-3 sm:flex-row" method="get"><input class="input flex-1" name="q" value="{{ request('q') }}" placeholder="{{ __('v3.common.search') }}"><button class="btn-primary">{{ __('v3.common.search') }}</button><a class="btn-secondary" href="{{ route('files.index') }}">{{ __('v3.common.clear') }}</a></form>

    <div class="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div class="hidden grid-cols-[minmax(260px,1fr)_130px_130px_140px_210px] gap-4 border-b border-slate-200 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-slate-400 lg:grid"><span>{{ __('v3.files.file') }}</span><span>{{ __('v3.files.size') }}</span><span>{{ __('v3.files.downloads',['count'=>'']) }}</span><span>{{ __('v3.common.status') }}</span><span>{{ __('v3.common.actions') }}</span></div>
      @forelse($files as $file)<article class="grid gap-4 border-b border-slate-100 p-5 last:border-0 lg:grid-cols-[minmax(260px,1fr)_130px_130px_140px_210px] lg:items-center"><div class="min-w-0"><div class="flex items-center gap-3"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-xl text-indigo-700">⇩</span><div class="min-w-0"><h2 class="truncate font-bold text-slate-950">{{ $file->original_name }}</h2><a class="mt-1 block truncate text-xs font-semibold text-cyan-700" href="{{ route('files.public',$file->slug) }}" target="_blank">{{ route('files.public',$file->slug) }}</a></div></div></div><div class="text-sm font-semibold text-slate-600">{{ Number::fileSize($file->size_bytes) }}</div><div><strong class="text-xl text-slate-950">{{ number_format($file->downloads_count) }}</strong></div><div class="flex flex-wrap gap-2"><span class="badge-neutral">{{ $file->visibility }}</span><span class="{{ $file->scan_status==='blocked' ? 'badge-danger':'badge-info' }}">{{ $file->scan_status }}</span></div><div class="flex flex-wrap gap-2"><a class="btn-secondary !px-3 !py-2" href="{{ route('files.manage',$file) }}">{{ __('v3.common.manage') ?? __('v3.common.edit') }}</a><a class="btn-secondary !px-3 !py-2" href="{{ route('files.download',$file->slug) }}">↓</a><form method="post" action="{{ route('files.destroy',$file) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger !px-3 !py-2">{{ __('v3.common.delete') }}</button></form></div></article>@empty<div class="empty-state m-5">{{ __('v3.files.empty') }}</div>@endforelse
    </div>
    @if($files->hasPages())<div class="mt-6">{{ $files->links() }}</div>@endif
  </section>
</x-layouts.app>
