<x-layouts.app :title="__('v3.webhooks.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10" x-data="{ createOpen:false }">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="page-kicker">{{ $workspace->name }}</p><h1 class="page-title mt-1">{{ __('v3.webhooks.title') }}</h1><p class="page-description">{{ __('v3.webhooks.subtitle') }}</p></div><button class="btn-brand" @click="createOpen=!createOpen">＋ {{ __('v3.webhooks.new') }}</button></div>

    @if(session('webhook_secret'))<div class="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5"><p class="font-bold text-amber-950">{{ __('v3.webhooks.secret_once') }}</p><code class="mt-3 block break-all rounded-xl bg-slate-950 p-4 text-sm text-cyan-300">{{ session('webhook_secret.secret') }}</code></div>@endif

    <form x-cloak x-show="createOpen" x-transition class="panel mt-6 grid gap-4 lg:grid-cols-[240px_1fr]" method="post" action="{{ route('webhooks.store') }}">@csrf<div><label class="label">{{ __('v3.common.name') }}</label><input class="input" name="name" required></div><div><label class="label">{{ __('v3.webhooks.endpoint') }}</label><input class="input" type="url" name="url" required placeholder="https://example.com/webhooks/gojet"></div><div class="lg:col-span-2"><label class="label">{{ __('v3.webhooks.events') }}</label><div class="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['*','link.created','link.updated','link.deleted','link.clicked','text.created','file.created','profile.published','domain.verified','conversion.created'] as $event)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="events[]" value="{{ $event }}" @checked($event==='*')><code>{{ $event }}</code></label>@endforeach</div></div><button class="btn-brand lg:col-span-2">{{ __('v3.common.create') }}</button></form>

    <div class="mt-7 space-y-5">@forelse($webhooks as $webhook)<article class="panel"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-xl font-black text-slate-950">{{ $webhook->name }}</h2><span class="{{ $webhook->is_active ? 'badge-success':'badge-danger' }}">{{ $webhook->is_active ? __('v3.common.active'):__('v3.common.disabled') }}</span></div><p class="mt-2 break-all text-sm font-semibold text-cyan-700">{{ $webhook->url }}</p><div class="mt-3 flex flex-wrap gap-2">@foreach($webhook->events as $event)<span class="badge-neutral"><code>{{ $event }}</code></span>@endforeach</div></div><div class="flex gap-2"><form method="post" action="{{ route('webhooks.test',$webhook) }}">@csrf<button class="btn-secondary">{{ __('v3.webhooks.test') }}</button></form><form method="post" action="{{ route('webhooks.destroy',$webhook) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger">{{ __('v3.common.delete') }}</button></form></div></div>
      <details class="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary class="cursor-pointer list-none font-bold text-slate-800">{{ __('v3.common.edit') }}</summary><form class="mt-4 grid gap-3 lg:grid-cols-2" method="post" action="{{ route('webhooks.update',$webhook) }}">@csrf @method('patch')<input class="input" name="name" value="{{ $webhook->name }}" required><input class="input" type="url" name="url" value="{{ $webhook->url }}" required><div class="grid gap-2 rounded-2xl border border-slate-200 bg-white p-3 lg:col-span-2 sm:grid-cols-2 lg:grid-cols-4">@foreach(['*','link.created','link.updated','link.deleted','link.clicked','text.created','file.created','profile.published','domain.verified','conversion.created'] as $event)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="events[]" value="{{ $event }}" @checked(in_array($event,$webhook->events,true))><code>{{ $event }}</code></label>@endforeach</div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($webhook->is_active)>{{ __('v3.common.active') }}</label><label class="flex items-center gap-2 text-sm text-amber-800"><input type="checkbox" name="rotate_secret" value="1">{{ __('v3.webhooks.rotate') }}</label><button class="btn-primary lg:col-span-2">{{ __('v3.common.save') }}</button></form></details>
      <div class="mt-5"><h3 class="font-bold text-slate-950">{{ __('v3.webhooks.deliveries') }}</h3><div class="mt-3 overflow-hidden rounded-2xl border border-slate-200">@forelse($webhook->deliveries as $delivery)<div class="grid gap-3 border-b border-slate-100 p-4 last:border-0 sm:grid-cols-[1fr_120px_100px_150px] sm:items-center"><div><code class="text-xs font-bold">{{ $delivery->event_name }}</code><p class="mt-1 text-xs text-slate-400">{{ $delivery->event_id }} · {{ $delivery->created_at->diffForHumans() }}</p></div><span class="{{ $delivery->status==='delivered'?'badge-success':($delivery->status==='failed'?'badge-danger':'badge-warning') }}">{{ $delivery->status }}</span><span class="text-sm font-semibold">HTTP {{ $delivery->response_status ?: '—' }}</span><form method="post" action="{{ route('webhooks.retry',$delivery) }}">@csrf<button class="btn-secondary !px-3 !py-2">{{ __('v3.webhooks.retry') }}</button></form></div>@empty<div class="p-5 text-center text-sm text-slate-400">{{ __('v3.common.none') }}</div>@endforelse</div></div>
    </article>@empty<div class="empty-state">{{ __('v3.webhooks.empty') }}</div>@endforelse</div>
  </section>
</x-layouts.app>
