#!/usr/bin/env python3
from pathlib import Path
from html import escape
root=Path(__file__).resolve().parents[1]/'frontend/marketing-site'
products={
'url-shortener':('短网址','让每一次点击都更短、更快、更可控','将冗长地址转为可信品牌短链，并在一个工作区管理状态、到期策略和营销参数',['品牌营销链接','短信与邮件触达','线下物料跳转','内部知识分享'],['自定义短码与域名','密码、到期和点击上限','301/302/307/308 跳转','UTM 自动拼接'],'营销团队、增长负责人、客户成功团队'),
'bio-pages':('个人主页','一个链接，承载你的全部内容与商业价值','用模块化个人主页聚合社交账号、内容、商品和订阅入口，并持续优化点击表现',['创作者主页','音乐与播客发布','作品集展示','社群导流'],['拖拽内容模块','主题与品牌字体','社交与商品组件','访问和转化分析'],'创作者、自由职业者、艺术家、社区主理人'),
'text-sharing':('文本分享','安全发布代码、公告与长文本','无需附件即可分享格式化文本，设置密码、阅后失效和访问期限',['代码片段评审','临时凭据交接','活动公告','客服操作指引'],['Markdown 与代码高亮','密码和过期策略','阅后销毁','访问审计'],'开发者、支持团队、运营人员'),
'file-sharing':('文件分享','让大文件交付可追踪、可撤回','上传文件后生成品牌访问页，掌握下载事件并随时停止公开访问',['客户文件交付','媒体资料包','设计稿评审','活动资源下载'],['对象存储直传','病毒扫描状态','下载上限与期限','品牌下载页面'],'设计团队、代理商、销售和客户成功'),
'analytics':('链接数据分析','从点击发生到洞察呈现，不丢一条事件','实时计数与持久化事件并行，清楚区分访客、机器人、Direct 和 Unknown',['营销归因','渠道对比','地区洞察','异常流量诊断'],['实时点击和独立访客','Referer 与 UTM','国家城市和设备','CSV 与自定义日期'],'增长、数据分析、运营与安全团队'),
'qr-code':('二维码','把每个线下触点变成可分析入口','创建与短链绑定的动态二维码，目标可更新，历史扫描数据持续保留',['包装与说明书','门店海报','展会物料','菜单与名片'],['动态目标地址','品牌颜色与 Logo','高分辨率导出','扫描来源分析'],'零售、餐饮、会展和品牌团队'),
'ab-testing':('A/B 测试','用真实流量选择更有效的落地页','按权重分配目标地址，持续比较点击、访问质量和转化结果',['着陆页实验','地区报价测试','内容标题测试','合作渠道分流'],['精确流量权重','实验起止时间','目标分流报表','随时锁定胜出版本'],'增长实验、产品营销和电商团队'),
'custom-domains':('自定义域名','让每条短链都延续品牌信任','接入你的域名，自动验证 DNS 与 HTTPS 状态，并按工作区隔离管理',['品牌短域名','多品牌运营','客户独立域名','地区域名策略'],['DNS 状态诊断','HTTPS 强制','默认域名切换','域名风险监控'],'企业品牌、代理商和多产品团队'),
'smart-links':('智能链接','根据访问上下文送达正确目的地','按设备、国家、语言、来源与时间建立路由规则，让一个入口服务多类访客',['应用商店跳转','全球内容分发','多语言落地页','合作伙伴路由'],['设备与系统规则','国家地区规则','语言与来源规则','规则优先级预览'],'全球化产品、移动应用和联盟营销'),
'qr-campaigns':('QR 营销活动','从一批二维码管理完整线下活动','按活动组织二维码、链接、物料和团队协作，统一查看扫描与转化',['全国门店活动','展会批次管理','户外广告追踪','产品包装版本'],['批量生成二维码','活动与标签组织','物料级报表','团队操作审计'],'品牌市场、零售运营和活动代理商')}
nav='''<header class="siteHeader"><div class="container nav"><a class="logo" href="/">GoJet<i>.</i></a><button data-mega>产品⌄</button><a href="/solutions/marketing/">解决方案</a><a href="/pricing/">定价</a><a href="/resources/">资源</a><a href="/docs/">文档</a><a class="push" href="/app/">登录</a><a class="btn primary" href="/register/">免费注册</a><button class="mobileMenu">菜单</button><div class="mega">'''+''.join(f'<a href="/products/{slug}/"><b>{escape(v[0])}</b><small>{escape(v[1][:22])}</small></a>' for slug,v in products.items())+'''</div></div></header>'''
footer='''<footer><div class="container"><div class="footerGrid"><div><a class="logo">GoJet<i>.</i></a><p>可信、可分析的链接基础设施。</p></div><div><b>产品</b><a href="/products/url-shortener/">短网址</a><a href="/products/analytics/">数据分析</a><a href="/products/qr-code/">二维码</a></div><div><b>解决方案</b><a href="/solutions/marketing/">营销</a><a href="/solutions/creators/">创作者</a><a href="/solutions/teams/">团队</a></div><div><b>资源</b><a href="/blog/">博客</a><a href="/docs/">文档</a><a href="/developers/">开发者 API</a><a href="/browser-extension/">浏览器扩展</a><a href="/apps/">应用</a><a href="/status/">服务状态</a></div><div><b>GoJet</b><a href="/about/">关于</a><a href="/contact/">联系我们</a><a href="/changelog/">更新日志</a></div></div><div class="legal">© 2026 GoJet. 保留所有权利。</div></div></footer><script src="/assets/app.js"></script>'''
def shot(name):return f'''<div class="productShot"><div class="window"><div class="windowTop"></div><div class="windowBody"><div class="shotNav"><b>GoJet</b>{'<i></i>'*7}</div><div class="shotMain"><small>{escape(name)} · 产品界面</small><div class="shotMetrics"><b>24,892</b><b>8,416</b><b>33.8%</b></div><div class="chart"></div><div class="shotRows">{'<i></i>'*5}</div></div></div></div></div>'''
for slug,(name,title,desc,scenes,features,audience) in products.items():
    cards=''.join(f'<article class="card"><div class="icon">{i+1}</div><h3>{escape(x)}</h3><p>以真实链接与访问事件为基础，清楚配置、追踪并持续优化这一场景。</p></article>' for i,x in enumerate(scenes))
    feats=''.join(f'<div class="row"><b>{escape(x)}</b><small>已启用</small><span>→</span></div>' for x in features)
    faqs=''.join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in [(f'{name}如何开始使用？','创建工作区后按流程完成配置，发布前可预览全部规则。'),('数据是否来自真实访问？','是。实时计数来自 Redis，明细事件由 Worker 持久化到 MySQL。'),('可以随时升级套餐吗？','可以，升级立即增加配额，降级在当前计费周期结束后生效。'),('如何保护数据安全？','访客标识经过密钥哈希，敏感设置加密保存，所有管理操作进入审计日志。')])
    html=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{name} | GoJet</title><meta name="description" content="{desc}"><link rel="stylesheet" href="/assets/styles.css"></head><body>{nav}<section class="hero"><div class="container heroGrid"><div><span class="eyebrow">GoJet {name}</span><h1>{title}</h1><p>{desc}</p><div class="actions"><a class="btn primary" href="/register/">免费开始</a><a class="btn" href="/contact/">预约演示</a></div></div>{shot(name)}</div></section><div class="trust">为每一次可靠跳转而构建 <b>实时</b><b>可恢复</b><b>隐私优先</b><b>团队协作</b></div><section class="section"><div class="container"><div class="sectionHead"><span class="eyebrow">核心场景</span><h2>{name}不只是一个入口</h2><p>围绕实际工作流组织能力，而不是堆叠无法使用的开关。</p></div><div class="cards">{cards}</div></div></section><section class="section alt"><div class="container split"><div><span class="eyebrow">产品能力</span><h2>在一个清晰界面完成配置与验证</h2><p>每项规则都有状态、原因和可预览结果，发布后立即进入真实统计链路。</p></div><div class="uiPanel"><header><b>{name}配置</b><small>实时保存</small></header>{feats}</div></div></section><section class="section"><div class="container"><div class="sectionHead"><span class="eyebrow">工作流程</span><h2>从创建到洞察，只需四步</h2></div><div class="workflow"><article><h3>创建</h3><p>选择工作区并填写业务目标。</p></article><article><h3>配置</h3><p>设置品牌、安全和路由规则。</p></article><article><h3>发布</h3><p>预览无误后生成可用入口。</p></article><article><h3>优化</h3><p>依据真实事件持续改进。</p></article></div></div></section><section class="section alt"><div class="container split"><div class="uiPanel">{shot('实时分析')}</div><div><span class="eyebrow">使用对象</span><h2>为真正负责结果的团队设计</h2><p>{audience}可以在同一工作区协作。</p><div class="audience">{''.join(f'<span>{escape(x)}</span>' for x in audience.split('、'))}</div></div></div></section><section class="section security"><div class="container"><div class="sectionHead"><span class="eyebrow">数据与安全</span><h2>实时可见，失败可恢复</h2><p>Redis 原子计数、Stream 事件、MySQL 幂等持久化和审计记录组成完整闭环。</p></div><div class="cards"><article class="card"><h3>隐私访客标识</h3><p>不在事件流保存原始 IP。</p></article><article class="card"><h3>机器人单独统计</h3><p>Bot 不污染独立访客。</p></article><article class="card"><h3>队列失败可诊断</h3><p>失败事件保留并记录原因。</p></article></div></div></section><section class="section"><div class="container"><div class="sectionHead"><span class="eyebrow">套餐能力</span><h2>从个人项目到团队规模</h2></div><div class="pricing"><article class="price"><h3>Free</h3><b>核心创建与基础统计</b><p>适合验证想法。</p></article><article class="price featured"><h3>Pro</h3><b>品牌、安全与高级分析</b><p>适合专业增长。</p></article><article class="price"><h3>Business</h3><b>团队、审计与高配额</b><p>适合组织协作。</p></article></div></div></section><section class="section faq"><div class="container"><div class="sectionHead"><span class="eyebrow">FAQ</span><h2>{name}常见问题</h2></div>{faqs}</div></section><section class="cta"><div class="container ctaBox"><h2>用 GoJet 开始你的{name}</h2><p>免费创建，数据来自每一次真实访问。</p><a class="btn" href="/register/">创建免费账号</a></div></section>{footer}</body></html>'''
    out=root/'products'/slug/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(html)
home=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoJet — 让每个链接产生清晰结果</title><meta name="description" content="GoJet 短网址、二维码、智能路由与真实链接分析平台"><link rel="stylesheet" href="/assets/styles.css"></head><body>{nav}<section class="hero"><div class="container heroGrid"><div><span class="eyebrow">链接基础设施，为增长而生</span><h1>一个入口，连接每次触达与真实结果</h1><p>创建可信短链、动态二维码和智能路由，在统一工作区查看实时点击、访客与来源。</p><div class="actions"><a class="btn primary" href="/register/">免费创建链接</a><a class="btn" href="/products/analytics/">查看数据能力</a></div></div>{shot('链接总览')}</div></section><div class="trust">受到现代团队信赖 <b>营销</b><b>创作者</b><b>零售</b><b>产品团队</b></div><section class="section"><div class="container"><div class="sectionHead"><span class="eyebrow">完整产品套件</span><h2>从创建入口，到理解每次访问</h2></div><div class="cards">{''.join(f'<a class="card" href="/products/{s}/"><div class="icon">→</div><h3>{v[0]}</h3><p>{v[2]}</p></a>' for s,v in list(products.items())[:6])}</div></div></section><section class="section alt"><div class="container split"><div><span class="eyebrow">真实数据闭环</span><h2>点击发生后，数字立即更新</h2><p>高性能跳转服务先原子增加 Redis 计数并写入 Stream，后台 Worker 再持久化事件；Worker 暂停也不会显示虚假的 0。</p><a class="btn primary" href="/products/analytics/">了解分析架构</a></div>{shot('30 天趋势')}</div></section><section class="cta"><div class="container ctaBox"><h2>让下一个链接更有价值</h2><p>从免费工作区开始，不使用静态演示数据。</p><a class="btn" href="/register/">免费注册</a></div></section>{footer}</body></html>''';(root/'index.html').write_text(home)
simple={'pricing':('透明定价，为真实使用量付费','Free、Pro 与 Business 套餐覆盖个人到企业团队。'),'about':('关于 GoJet','我们构建可信、可恢复、隐私优先的链接基础设施。'),'contact':('联系我们','预约产品演示、迁移评估或技术支持。'),'resources':('资源中心','产品指南、最佳实践和链接增长知识。'),'docs':('GoJet 文档','从创建第一个短链到部署分析 Worker。'),'developers':('开发者 API','使用 REST API 和 Token 自动化链接工作流。'),'blog':('GoJet 博客','链接管理、二维码和增长分析的实践文章。'),'register':('创建 GoJet 账号','注册后自动获得个人工作区。'),'solutions/marketing':('营销解决方案','用短链、QR、UTM 与真实归因连接每个营销触点。'),'solutions/creators':('创作者解决方案','用个人主页、智能链接和受众分析沉淀长期影响力。'),'solutions/teams':('团队解决方案','以工作区、五级角色和审计记录安全协作。'),'browser-extension':('GoJet 浏览器扩展','在当前页面一键创建、复制和管理短链接。'),'apps':('GoJet 应用','通过移动端与桌面工作流随时管理品牌入口。'),'changelog':('GoJet 更新日志','查看产品、API、可靠性与安全能力的真实版本变化。'),'status':('GoJet 服务状态','实时检查跳转、分析、数据库与邮件队列。')}
for slug,(title,desc) in simple.items():
 out=root/slug/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | GoJet</title><link rel="stylesheet" href="/assets/styles.css"></head><body>{nav}<section class="hero"><div class="container"><span class="eyebrow">GoJet</span><h1>{title}</h1><p>{desc}</p><div class="actions"><a class="btn primary" href="/app/">进入控制台</a><a class="btn" href="mailto:support@gojet.example">联系团队</a></div></div></section><section class="section"><div class="container"><div class="cards"><article class="card"><h3>真实功能</h3><p>所有入口连接后端业务闭环。</p></article><article class="card"><h3>清晰状态</h3><p>加载、失败与权限状态明确。</p></article><article class="card"><h3>可部署</h3><p>提供安装、升级和回滚脚本。</p></article></div></div></section>{footer}</body></html>')
status_html=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoJet 服务状态</title><link rel="stylesheet" href="/assets/styles.css"></head><body>{nav}<section class="hero"><div class="container"><span class="eyebrow">实时运行状态</span><h1>GoJet 服务状态</h1><p>此页面直接读取数据库、Redis 分析流与邮件队列健康状态，不使用静态演示状态。</p></div></section><section class="section"><div class="container"><div id="systemStatus" class="uiPanel">正在读取真实系统状态…</div></div></section>{footer}<script src="/assets/status.js"></script></body></html>'''
(root/'status'/'index.html').write_text(status_html)
