const $=s=>document.querySelector(s);let token=sessionStorage.getItem('gojet_admin');const titles={overview:'平台概览',users:'用户与封禁',workspaces:'工作区',links:'内容与链接',mail:'邮件与失败',abuse:'举报与隔离',domains:'域名风险',security:'安全事件',announcements:'公告运营',audit:'审计日志',settings:'邮件设置'};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`请求失败 ${r.status}`);return d}function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function n(v){return Number(v||0).toLocaleString('zh-CN')}function dt(v){return new Date(v).toLocaleString('zh-CN')}
$('#gateForm').onsubmit=async e=>{e.preventDefault();token=new FormData(e.target).get('token');try{await api('/api/admin/overview');sessionStorage.setItem('gojet_admin',token);$('#gate').classList.add('hidden');$('#admin').classList.remove('hidden');load('overview')}catch(err){$('#gateError').textContent=err.message}};if(token){$('#gate').classList.add('hidden');$('#admin').classList.remove('hidden');load('overview')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.view)});$('#reload').onclick=()=>load(document.querySelector('[data-view].active').dataset.view);
async function load(view){$('#viewTitle').textContent=titles[view];$('#content').innerHTML='正在读取真实平台数据…';try{if(view==='overview')return overview(await api('/api/admin/overview'));if(view==='settings')return settings();const data=await api(`/api/admin/${view}`);table(view,data.data)}catch(e){$('#content').innerHTML=`<p class="notice">${esc(e.message)}</p>`}}
function overview(d){const metrics=[['用户总数',d.users],['工作区总数',d.workspaces],['活跃链接',d.active_links],['今日点击',d.today_clicks],['邮件失败',d.mail_failures],['滥用举报',d.abuse_reports],['域名异常',d.domain_errors]];$('#content').innerHTML=`<div class="metrics">${metrics.map(x=>`<article class="metric"><span>${x[0]}</span><b>${n(x[1])}</b></article>`).join('')}</div><div class="notice">所有数字均来自 MySQL/Analytics 真实数据；尚未接入的举报与域名风险指标明确为 0。</div>`}
function table(view,items){const configs={users:[['ID','id'],['邮箱','email'],['名称','name'],['工作区','workspaces'],['验证','email_verified'],['状态','status'],['创建时间','created_at']],workspaces:[['ID','id'],['工作区','name'],['类型','type'],['所有者','owner'],['成员','members'],['链接','links'],['创建时间','created_at']],links:[['ID','id'],['短码','code'],['目标地址','destination'],['工作区','workspace'],['创建者','creator'],['状态','status'],['创建时间','created_at']],mail:[['ID','id'],['类型','type'],['收件人','recipient'],['主题','subject'],['状态','status'],['尝试','attempts'],['最后错误','last_error']],abuse:[['ID','id'],['短码','code'],['原因','reason'],['详情','details'],['举报人','reporter'],['状态','status'],['处理结果','resolution']],domains:[['ID','id'],['域名','hostname'],['工作区','workspace'],['DNS 状态','status'],['HTTPS','https_status'],['异常原因','last_error'],['检查时间','last_checked_at']],security:[['ID','id'],['事件','event_type'],['级别','severity'],['来源','source'],['详情','description'],['状态','status'],['时间','created_at']],announcements:[['ID','id'],['标题','title'],['正文','body'],['状态','status'],['发布时间','published_at'],['创建时间','created_at']],audit:[['ID','id'],['操作者','actor'],['工作区','workspace'],['操作','action'],['目标','target_type'],['目标 ID','target_id'],['时间','created_at']]};const cols=configs[view];$('#content').innerHTML=`<div class="panel"><h2>${titles[view]}</h2><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}${actionHeader(view)}</tr></thead><tbody>${items.map(row=>`<tr>${cols.map(c=>`<td>${cell(c[1],row[c[1]])}</td>`).join('')}${actions(view,row)}</tr>`).join('')}</tbody></table></div>${view==='announcements'?'<button style="margin-top:12px" onclick="createAnnouncement()">创建公告</button>':''}`}
function cell(key,v){if(key==='created_at')return dt(v);if(key==='status')return`<span class="state ${esc(v)}">${({active:'正常',suspended:'已封禁',pending:'待发送',sent:'已发送',failed:'失败',paused:'暂停'})[v]||esc(v)}</span>`;if(key==='email_verified')return v?'已验证':'未验证';return esc(v)}window.changeStatus=(id,current)=>{$('#statusForm [name=id]').value=id;$('#statusForm [name=status]').value=current==='active'?'suspended':'active';$('#dialog').classList.remove('hidden')};$('#cancel').onclick=()=>$('#dialog').classList.add('hidden');$('#statusForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));await api(`/api/admin/users/${d.id}/status`,{method:'PATCH',body:JSON.stringify(d)});$('#dialog').classList.add('hidden');load('users')};
function settings(){$('#content').innerHTML=`<div class="panel"><h2>SMTP 邮件设置</h2><form id="mailSettings" class="settingGrid"><label>SMTP Host<input name="host" required></label><label>端口<input name="port" type="number" value="587" required></label><label>加密<select name="encryption"><option value="starttls">STARTTLS</option><option value="tls">TLS</option></select></label><label>EHLO 域名<input name="ehlo"></label><label>用户名<input name="username"></label><label>密码<input name="password" type="password" placeholder="留空保留原密码"></label><label>发件邮箱<input name="from_email" type="email" required></label><label>发件人名称<input name="from_name" value="GoJet"></label><label>回复邮箱<input name="reply_to" type="email"></label><button>保存设置</button></form></div><div class="panel"><h2>连接并发送测试邮件</h2><form id="mailTest" class="settingGrid"><label>测试收件人<input name="recipient" type="email" required></label><button>连接、认证并实际发送</button></form><p id="mailResult" class="notice hidden"></p></div>`;$('#mailSettings').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.port=Number(d.port);await api('/api/admin/settings/mail',{method:'PUT',body:JSON.stringify(d)});alert('设置已加密保存')};$('#mailTest').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const out=$('#mailResult');out.classList.remove('hidden');out.textContent='正在连接 SMTP 并发送测试邮件…';try{await api('/api/admin/mail/test',{method:'POST',body:JSON.stringify(d)});out.textContent='测试邮件已发送，邮箱验证功能现在可以启用。'}catch(err){out.textContent=err.message}};loadSettingCenter()}
async function loadSettingCenter(){
  const current=await api('/api/admin/settings');
  $('#content').insertAdjacentHTML('beforeend',`<div class="panel"><h2>基础信息与 SEO</h2><form id="basicSettings" class="settingGrid">${field('site.name','网站名称',current.basic?.['site.name']||'GoJet')}${field('site.short_name','网站简称',current.basic?.['site.short_name']||'GoJet')}${field('site.tagline','网站标语',current.basic?.['site.tagline']||'')}${field('site.description','网站描述',current.basic?.['site.description']||'')}${field('site.language','默认语言',current.basic?.['site.language']||'zh-CN')}${field('site.timezone','时区',current.basic?.['site.timezone']||'UTC')}${field('site.contact_email','联系邮箱',current.basic?.['site.contact_email']||'', 'email')}${field('site.support_email','支持邮箱',current.basic?.['site.support_email']||'', 'email')}<button>保存基础信息</button></form><form id="seoSettings" class="settingGrid">${field('seo.default_title','默认页面标题',current.seo?.['seo.default_title']||'')}${field('seo.title_template','标题模板',current.seo?.['seo.title_template']||'%s | GoJet')}${field('seo.meta_description','Meta Description',current.seo?.['seo.meta_description']||'')}${field('seo.meta_keywords','Meta Keywords',current.seo?.['seo.meta_keywords']||'')}${field('seo.canonical_url','Canonical URL',current.seo?.['seo.canonical_url']||'', 'url')}<button>保存 SEO</button></form></div><div class="panel"><h2>品牌资产（上传后立即生成公开 URL）</h2><form id="brandColor" class="settingGrid">${field('brand.primary_color','品牌主色',current.brand?.['brand.primary_color']||'#1769e0','color')}<button>保存品牌颜色</button></form><div id="brandAssets" class="settingGrid">${['logo','logo-dark','logo-light','logo-square','favicon','apple-touch-icon','pwa-icon','share-image','login-image','mail-logo'].map(asset=>brandUploader(asset,current.brand?.[asset])).join('')}</div></div><div class="panel"><h2>注册、短链与统计隐私</h2><form id="registrationSettings" class="settingGrid">${check('registration.enabled','开放注册',current.registration?.['registration.enabled'])}${check('registration.require_email_verification','强制邮箱验证',current.registration?.['registration.require_email_verification'])}${field('registration.password_min_length','最短密码长度',current.registration?.['registration.password_min_length']||10,'number')}${field('registration.login_rate_limit','登录频率限制',current.registration?.['registration.login_rate_limit']||10,'number')}<button>保存注册设置</button></form><form id="privacySettings" class="settingGrid">${check('analytics.enabled','启用统计',current.privacy?.['analytics.enabled']!==false)}${field('analytics.retention_days','数据保留天数',current.privacy?.['analytics.retention_days']||30,'number')}${check('analytics.record_full_referer','记录完整 Referer',current.privacy?.['analytics.record_full_referer'])}${check('analytics.record_city','记录城市',current.privacy?.['analytics.record_city'])}${check('analytics.exclude_bots','分析中排除 Bot',current.privacy?.['analytics.exclude_bots']!==false)}<button>保存隐私设置</button></form></div>`);
  bindSettingForm('basicSettings','basic');bindSettingForm('seoSettings','seo');bindSettingForm('brandColor','brand');bindSettingForm('registrationSettings','registration');bindSettingForm('privacySettings','privacy');
  document.querySelectorAll('[data-brand]').forEach(form=>form.onsubmit=uploadBrand);
}
function field(name,labelText,value,type='text'){return `<label>${labelText}<input name="${name}" type="${type}" value="${esc(value)}"></label>`}
function check(name,labelText,value){return `<label><span>${labelText}</span><input name="${name}" type="checkbox" ${value?'checked':''}></label>`}
function brandUploader(asset,url){return `<form data-brand="${asset}"><label>${asset}<input name="file" type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/x-icon" required></label>${url?`<img src="${esc(url)}" alt="${asset}" style="max-height:55px;max-width:180px"><button type="button" onclick="deleteBrand('${asset}')">删除</button>`:''}<button>上传并替换</button></form>`}
function bindSettingForm(id,section){const form=$('#'+id);form.onsubmit=async e=>{e.preventDefault();const values={};for(const input of form.elements){if(!input.name)continue;values[input.name]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value}await api(`/api/admin/settings/${section}`,{method:'PUT',body:JSON.stringify(values)});alert('设置已保存并立即生效')}}
async function uploadBrand(e){e.preventDefault();const form=e.target,asset=form.dataset.brand,data=new FormData(form);const response=await fetch(`/api/admin/brand/${asset}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);alert('品牌资产已上传：'+result.url);load('settings')}
window.deleteBrand=async asset=>{if(!confirm('确认删除该品牌资产？'))return;await api(`/api/admin/brand/${asset}`,{method:'DELETE'});load('settings')};
function actionHeader(view){return ['users','abuse','security'].includes(view)?'<th>操作</th>':''}
function actions(view,row){if(view==='users')return `<td><button onclick="changeStatus(${row.id},'${row.status}')">${row.status==='active'?'封禁':'恢复'}</button></td>`;if(view==='abuse'&&['open','investigating'].includes(row.status))return `<td><button onclick="resolveAbuse(${row.id})">处理</button></td>`;if(view==='security'&&row.status==='open')return `<td><button onclick="resolveSecurity(${row.id})">标记解决</button></td>`;return actionHeader(view)?'<td>—</td>':''}
window.resolveAbuse=async id=>{const status=prompt('处理状态：investigating / resolved / rejected','investigating');if(!status)return;const resolution=prompt('填写处理原因（将进入审计日志）');if(!resolution)return;await api(`/api/admin/abuse/${id}`,{method:'PATCH',body:JSON.stringify({status,resolution})});load('abuse')};
window.resolveSecurity=async id=>{if(!confirm('确认该安全事件已经解决？'))return;await api(`/api/admin/security/${id}`,{method:'PATCH',body:'{}'});load('security')};
window.createAnnouncement=async()=>{const title=prompt('公告标题');if(!title)return;const body=prompt('公告正文');if(!body)return;const status=confirm('立即发布？取消则保存草稿')?'published':'draft';await api('/api/admin/announcements',{method:'POST',body:JSON.stringify({title,body,status})});load('announcements')};
