<x-layouts.app :title="__('v3.profiles.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10" x-data="{ createOpen:false }">
    <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="page-kicker">{{ $workspace->name }}</p><h1 class="page-title mt-1">{{ __('v3.profiles.title') }}</h1><p class="page-description">{{ __('v3.profiles.subtitle') }}</p></div><button class="btn-brand" @click="createOpen=!createOpen">＋ {{ __('v3.profiles.new') }}</button></div>
    <form x-cloak x-show="createOpen" x-transition class="panel mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5" method="post" action="{{ route('profiles.store') }}">@csrf<div><label class="label">{{ __('v3.profiles.title_field') }}</label><input class="input" name="title" required></div><div><label class="label">{{ __('v3.profiles.slug') }}</label><input class="input" name="slug" required></div><div><label class="label">{{ __('v3.profiles.theme') }}</label><select class="input" name="theme">@foreach(['aurora','minimal','midnight','paper','contrast'] as $theme)<option value="{{ $theme }}">{{ ucfirst($theme) }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.profiles.domain') }}</label><select class="input" name="domain_id"><option value="">{{ config('gojet.default_host') }}</option>@foreach($domains as $domain)<option value="{{ $domain->id }}">{{ $domain->hostname }}</option>@endforeach</select></div><div class="md:col-span-2 xl:col-span-4"><label class="label">{{ __('v3.profiles.bio') }}</label><input class="input" name="bio"></div><button class="btn-brand self-end">{{ __('v3.common.create') }}</button></form>

    <div class="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($profiles as $profile)<article class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="h-28" style="background:linear-gradient(135deg,{{ data_get($profile->theme_settings,'background','#f8fafc') }},{{ data_get($profile->theme_settings,'accent','#06b6d4') }}55)"></div><div class="p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><span class="{{ $profile->status==='published' ? 'badge-success':'badge-neutral' }}">{{ __('v3.common.'.$profile->status) }}</span><h2 class="mt-3 truncate text-xl font-black text-slate-950">{{ $profile->title }}</h2><p class="mt-1 truncate text-sm font-semibold text-cyan-700">/p/{{ $profile->slug }}</p></div><div class="rounded-xl bg-slate-50 px-3 py-2 text-center"><strong>{{ number_format($profile->views_count) }}</strong><p class="text-[10px] text-slate-400">Views</p></div></div><p class="mt-4 line-clamp-2 text-sm leading-6 text-slate-500">{{ $profile->bio }}</p><div class="mt-4 flex items-center justify-between text-xs text-slate-400"><span>{{ $profile->blocks_count }} blocks</span><span>{{ ucfirst($profile->theme) }}</span></div><div class="mt-5 flex gap-2 border-t border-slate-100 pt-4"><a class="btn-primary flex-1" href="{{ route('profiles.edit',$profile) }}">{{ __('v3.common.edit') }}</a>@if($profile->status==='published')<a class="btn-secondary" href="{{ route('profiles.public',$profile->slug) }}" target="_blank">↗</a>@endif<form method="post" action="{{ route('profiles.destroy',$profile) }}" onsubmit="return confirm(@js(__('v3.common.confirm_delete'))) ">@csrf @method('delete')<button class="btn-danger">{{ __('v3.common.delete') }}</button></form></div></div></article>@empty<div class="empty-state md:col-span-2 xl:col-span-3">{{ __('v3.profiles.empty') }}</div>@endforelse</div>
    @if($profiles->hasPages())<div class="mt-6">{{ $profiles->links() }}</div>@endif
  </section>
</x-layouts.app>
