(()=>{
'use strict';
const AQ=s=>document.querySelector(s),AE=v=>escapeHTML(v??'');
const pick=(o,...keys)=>{for(const k of keys)if(o&&o[k]!==undefined)return o[k];return 0};
const dims=(a,...keys)=>{const v=pick(a,...keys);return Array.isArray(v)?v:[]};
const agoDate=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
const nextDate=value=>{const d=new Date(`${value}T00:00:00Z`);if(Number.isNaN(d.valueOf()))return value;d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)};
const requestedLink=()=>Number(new URLSearchParams(location.search).get('link')||0);
let regionNames=null;try{regionNames=new Intl.DisplayNames(['zh-CN'],{type:'region'})}catch{}
const maps={browser:{edge:'Microsoft Edge',chrome:'Google Chrome',firefox:'Firefox',safari:'Safari',other:'其他浏览器',unknown:'未识别浏览器'},device:{desktop:'桌面设备',mobile:'手机',tablet:'平板设备',other:'其他设备',unknown:'未识别设备'},os:{windows:'Windows',macos:'macOS',linux:'Linux',android:'Android',ios:'iOS',other:'其他系统',unknown:'未识别系统'},source:{direct:'直接访问',referer:'引荐访问',unknown:'未知来源'}};
function dimensionName(value,kind=''){const raw=String(value??'').trim(),low=raw.toLowerCase();if(!raw||low==='unknown'||low==='xx'||low==='other'&&kind==='country')return kind==='country'?'未识别国家 / 地区':'未识别';if(kind==='country'&&/^[a-z]{2}$/i.test(raw)){try{return regionNames?.of(raw.toUpperCase())||raw.toUpperCase()}catch{return raw.toUpperCase()}}return maps[kind]?.[low]||raw}
function bars(points){const max=Math.max(1,...points.map(x=>Number(x.clicks||x.Clicks||0)));return `<div class="analyticsBars">${points.map(x=>{const v=Number(x.clicks||x.Clicks||0),h=Math.max(v?6:2,Math.round(v/max*100));return `<div class="analyticsBar" title="${AE(x.date||x.Date)} · ${v} 次访问"><i style="height:${h}%"></i><small>${String(x.date||x.Date||'').slice(5)}</small></div>`}).join('')}</div>`}
function dimension(title,items,kind=''){return `<section class="analyticsDimension"><div class="analyticsDimensionHead"><h3>${title}</h3><span>${items.length?`前 ${Math.min(items.length,8)} 项`:'暂无数据'}</span></div>${items.length?items.slice(0,8).map((x,i)=>{const name=dimensionName(x.name??x.Name??'',kind),count=Number(x.count??x.Count??0),max=Number(items[0]?.count??items[0]?.Count??1)||1;return `<div class="dimensionRow"><b>${i+1}</b><span title="${AE(name)}">${AE(name)}</span><i><em style="width:${Math.max(3,Math.round(count/max*100))}%"></em></i><strong>${count.toLocaleString()}</strong></div>`}).join(''):'<div class="analyticsEmpty">当前时间范围内还没有足够的访问数据。</div>'}</section>`}
async function render(){
 const c=AQ('.content');c.innerHTML=`<div class="productPageHead"><div><h1>访问分析</h1><p>查看工作区整体趋势，也可以选择一条短链接进一步了解访问来源和访客设备。</p></div><button id="analyticsRefresh">刷新</button></div><div id="analyticsPage" class="productLoading">正在加载分析数据…</div>`;AQ('#analyticsRefresh').onclick=render;
 try{const wid=state.workspace,[overview,links,qrs,files,texts,bios]=await Promise.all([api(`/api/workspaces/${wid}/overview`),api(`/api/workspaces/${wid}/links?limit=100&offset=0`).catch(()=>({data:[]})),api(`/api/workspaces/${wid}/qr-codes`).catch(()=>({data:[]})),api(`/api/workspaces/${wid}/fileshares`).catch(()=>({data:[]})),api(`/api/workspaces/${wid}/text-shares`).catch(()=>({data:[]})),api(`/api/workspaces/${wid}/bio-pages`).catch(()=>({data:[]}))]);const rows=links.data||[],qrRows=qrs.data||[],fileRows=files.data||[],textRows=texts.data||[],bioRows=bios.data||[],qrVisits=qrRows.reduce((n,x)=>n+Number(x.qr_visits||0),0),downloads=fileRows.reduce((n,x)=>n+Number(x.downloads||0),0),textViews=textRows.reduce((n,x)=>n+Number(x.views||0),0),bioViews=bioRows.reduce((n,x)=>n+Number(x.views||0),0),trend=overview.trend||[],preselected=requestedLink();
 AQ('#analyticsPage').classList.remove('productLoading');
 AQ('#analyticsPage').innerHTML=`<div class="analyticsMetricGrid"><article><small>今日访问</small><strong>${Number(overview.today_clicks||0).toLocaleString()}</strong><span>今日累计</span></article><article><small>本月访问</small><strong>${Number(overview.month_clicks||0).toLocaleString()}</strong><span>本月累计</span></article><article><small>本月独立访客</small><strong>${Number(overview.unique_visitors||0).toLocaleString()}</strong><span>按访客去重</span></article><article><small>二维码访问</small><strong>${qrVisits.toLocaleString()}</strong><span>${qrRows.length} 个二维码</span></article></div><section class="analyticsTrendPanel"><div class="analyticsPanelHead"><div><span class="eyebrow">最近 30 天</span><h2>访问趋势</h2></div></div>${bars(trend)}</section><div class="resourceActivity"><article><b>${downloads.toLocaleString()}</b><span>文件下载</span><small>${fileRows.length} 个文件分享</small></article><article><b>${textViews.toLocaleString()}</b><span>文本阅读</span><small>${textRows.length} 份文本</small></article><article><b>${bioViews.toLocaleString()}</b><span>个人主页浏览</span><small>${bioRows.length} 个个人主页</small></article><article><b>${Number(overview.active_links||0).toLocaleString()}</b><span>正在使用的短链接</span><small>${rows.length} 条链接</small></article></div><section class="linkDrilldown"><div class="analyticsPanelHead"><div><span class="eyebrow">单链接分析</span><h2>查看一条链接的访问情况</h2></div></div><div class="analyticsFilters"><label>短链接<select id="analyticsLinkSelect">${rows.map(x=>`<option value="${Number(x.ID??x.id)}">/${AE(x.Code??x.code)} · ${AE((x.Title??x.title)||(x.Destination??x.destination))}</option>`).join('')}</select></label><label>开始日期<input id="analyticsFrom" type="date" value="${agoDate(29)}"></label><label>结束日期<input id="analyticsTo" type="date" value="${agoDate(0)}"></label><button class="primary" id="analyticsApply">查询</button></div><div id="analyticsLinkResult">${rows.length?'正在读取这条链接的访问详情…':'还没有短链接。'}</div></section>`;
 if(rows.length){const select=AQ('#analyticsLinkSelect');if(preselected&&rows.some(x=>Number(x.ID??x.id)===preselected))select.value=String(preselected);AQ('#analyticsApply').onclick=()=>loadLink(rows,qrRows);select.onchange=()=>{const id=Number(select.value);history.replaceState({view:'analytics'},'',`/app/analytics?link=${id}`);loadLink(rows,qrRows)};await loadLink(rows,qrRows)}
 }catch(e){const host=AQ('#analyticsPage');if(host)host.innerHTML=`<div class="productError">${AE(e.message)}</div>`}
}
async function loadLink(rows,qrRows){const id=Number(AQ('#analyticsLinkSelect').value),from=AQ('#analyticsFrom').value,to=nextDate(AQ('#analyticsTo').value),host=AQ('#analyticsLinkResult');host.innerHTML='<div class="productLoading">正在加载链接分析…</div>';try{const a=await api(`/api/workspaces/${state.workspace}/links/${id}/analytics?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),link=rows.find(x=>Number(x.ID??x.id)===id),qr=qrRows.filter(x=>Number(x.link_id)===id).reduce((n,x)=>n+Number(x.qr_visits||0),0),clicks=Number(pick(a,'clicks','Clicks')||0),unique=Number(pick(a,'unique_visitors','UniqueVisitors')||0),bots=Number(pick(a,'bot_visits','BotVisits')||0);host.innerHTML=`<div class="analyticsLinkHead"><div><h3>/${AE(link?.Code??link?.code)}</h3><p>${AE(link?.Destination??link?.destination)}</p></div><div><span><b>${clicks.toLocaleString()}</b>访问</span><span><b>${unique.toLocaleString()}</b>访客</span><span><b>${bots.toLocaleString()}</b>机器人访问</span><span><b>${qr.toLocaleString()}</b>二维码访问</span></div></div><div class="analyticsDimensionGrid">${dimension('访问来源',dims(a,'sources','Sources'),'source')}${dimension('国家 / 地区',dims(a,'countries','Countries'),'country')}${dimension('省 / 州',dims(a,'regions','Regions'),'region')}${dimension('城市',dims(a,'cities','Cities'),'city')}${dimension('设备',dims(a,'devices','Devices'),'device')}${dimension('浏览器',dims(a,'browsers','Browsers'),'browser')}${dimension('操作系统',dims(a,'operating_systems','OperatingSystems'),'os')}${dimension('语言',dims(a,'languages','Languages'),'language')}</div><div class="geoAttribution">IP 地理位置数据：<a href="https://db-ip.com" target="_blank" rel="noopener noreferrer">IP Geolocation by DB-IP</a></div>`}catch(e){host.innerHTML=`<div class="productError">${AE(e.message)}</div>`}}
function openAnalytics(id){const linkID=Number(id||0);const route=linkID?`/app/analytics?link=${linkID}`:'/app/analytics';history.pushState({view:'analytics'},'',route);return window.GoJetRouter?.show('analytics',false)}
window.gojetOpenAnalytics=openAnalytics;
window.GoJetPages=window.GoJetPages||{};window.GoJetPages.analytics=render;
})();