(()=>{
'use strict';
const modalSelectors=['.productModalLayer','#linkEditorLayer','.dialogLayer','.modalLayer'];
const visibleModal=()=>modalSelectors.map(selector=>document.querySelector(selector)).find(node=>node&&node.isConnected&&getComputedStyle(node).display!=='none');
const focusableSelector='button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
let activeModal=null,returnFocus=null;
function modalPanel(layer){return layer?.querySelector('.productModal,.dialog,.modal,[role="dialog"]')||layer}
function syncModalFocus(){const next=visibleModal();if(next===activeModal)return;if(activeModal&&!next&&returnFocus?.isConnected){try{returnFocus.focus({preventScroll:true})}catch{}}activeModal=next;if(!next){returnFocus=null;return}returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;const panel=modalPanel(next);panel?.setAttribute('role','dialog');panel?.setAttribute('aria-modal','true');requestAnimationFrame(()=>{const target=panel?.querySelector('[autofocus],input,textarea,select,button,a[href]');target?.focus?.({preventScroll:true})})}
document.addEventListener('click',event=>{const modal=visibleModal();if(!modal)return;if(event.target===modal){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation()}},true);
document.addEventListener('keydown',event=>{const modal=visibleModal();if(!modal)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();return}if(event.key!=='Tab')return;const panel=modalPanel(modal),items=[...(panel?.querySelectorAll(focusableSelector)||[])].filter(node=>node.offsetParent!==null||node===document.activeElement);if(!items.length){event.preventDefault();panel?.focus?.();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}},true);
const syncBodyLock=()=>{const open=Boolean(visibleModal());document.documentElement.classList.toggle('modalOpen',open);document.body.style.overflow=open?'hidden':'';syncModalFocus()};

const escapeCode=value=>String(value??'').replace(/[&<>]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]));
const escapeText=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function codeKind(value){const source=String(value||'').trim();if(/<!doctype\s+html|<html\b|<body\b|<div\b|<section\b|<main\b/i.test(source))return'HTML';if(/^\s*[\[{][\s\S]*[\]}]\s*$/.test(source)){try{JSON.parse(source);return'JSON'}catch{}}if(/(^|\n)\s*(const|let|var|function|import|export|class)\b/.test(source))return'JavaScript';if(/(^|\n)\s*(#!\/bin\/(ba)?sh|sudo\s|apt\s|yum\s|docker\s|curl\s)/i.test(source))return'Shell';if(/[.#][\w-]+\s*\{[^}]*\}/.test(source))return'CSS';return'源代码'}
function safeHTMLPreview(source){const parsed=new DOMParser().parseFromString(String(source||''),'text/html');parsed.querySelectorAll('script,iframe,object,embed,meta,base,link').forEach(node=>node.remove());parsed.querySelectorAll('*').forEach(node=>{[...node.attributes].forEach(attr=>{const name=attr.name.toLowerCase(),value=String(attr.value||'').trim();if(name.startsWith('on')||name==='srcdoc'||/^(?:java|vb)script:/i.test(value))node.removeAttribute(attr.name)})});return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:14px/1.6 system-ui,sans-serif;margin:18px;color:#15231d}img{max-width:100%}</style></head><body>'+parsed.body.innerHTML+'</body></html>'}
function enhanceTextComposer(){const composer=document.querySelector('.textComposer');if(!composer||composer.dataset.finalPolish==='1')return;const format=composer.querySelector('#textFormat'),textarea=composer.querySelector('textarea[name="content"]'),split=composer.querySelector('.editorSplit');if(!format||!textarea||!split)return;composer.dataset.finalPolish='1';const studio=document.createElement('section');studio.className='codeStudio';studio.hidden=true;studio.innerHTML='<div class="codeStudioHead"><div><b>代码工作区</b><span>源码始终按文本安全展示，不会在公开分享页执行。</span></div><span class="codeKind" data-code-kind>源代码</span></div><div class="codeStudioGrid"><div class="codeSource"><header>实时源码预览</header><pre><code data-code-preview></code></pre></div><div class="htmlPreview" data-html-preview><header>HTML 安全预览</header><iframe sandbox="" title="HTML 安全预览"></iframe></div></div>';split.insertAdjacentElement('afterend',studio);const preview=studio.querySelector('[data-code-preview]'),kind=studio.querySelector('[data-code-kind]'),htmlBox=studio.querySelector('[data-html-preview]'),frame=htmlBox.querySelector('iframe');const sync=()=>{const code=format.value==='code';studio.hidden=!code;if(!code)return;const value=textarea.value,type=codeKind(value);kind.textContent=type;preview.innerHTML=escapeCode(value)||'<span class="codeEmpty">开始输入代码后，这里会同步显示。</span>';const isHTML=type==='HTML';htmlBox.hidden=!isHTML;if(isHTML)frame.srcdoc=safeHTMLPreview(value)};format.addEventListener('change',()=>requestAnimationFrame(sync));textarea.addEventListener('input',sync);sync()}

async function resilientInvoiceDownload(button){
  const invoiceID=Number(button.dataset.downloadInvoice);if(!invoiceID)return;
  const layer=document.createElement('div');layer.className='productModalLayer';layer.innerHTML='<div class="productModal billingDialog"><div class="productModalHead"><h2>准备账单 PDF</h2><button type="button" data-close aria-label="关闭">×</button></div><div class="billingDialogBody"><div class="productLoading" data-pdf-state>正在生成账单文件…</div></div><div class="productModalFoot"><button type="button" data-close-secondary>关闭</button></div></div>';document.body.append(layer);syncBodyLock();
  const close=()=>{layer.remove();syncBodyLock()};layer.querySelector('[data-close]').onclick=close;layer.querySelector('[data-close-secondary]').onclick=close;const host=layer.querySelector('[data-pdf-state]');button.disabled=true;
  try{
    const ticket=await api(`/api/workspaces/${state.workspace}/billing/invoices/${invoiceID}/download-ticket`,{method:'POST',body:'{}'});
    if(!ticket?.url)throw new Error('服务器没有返回账单下载地址');
    host.className='productSuccess';host.innerHTML='<b>账单已准备完成</b><p>下载即将开始。</p>';
    const anchor=document.createElement('a');anchor.href=ticket.url;anchor.download=ticket.filename||'';anchor.style.display='none';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(close,450);
  }catch(error){host.className='productError';host.innerHTML=`<b>账单 PDF 暂时无法下载</b><p>${escapeText(error?.message||'账单服务连接异常')}</p>`}
  finally{button.disabled=false}
}
document.addEventListener('click',event=>{const button=event.target.closest?.('[data-download-invoice]');if(!button)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();void resilientInvoiceDownload(button)},true);

const observer=new MutationObserver(()=>{syncBodyLock();enhanceTextComposer()});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','hidden']});syncBodyLock();enhanceTextComposer();
})();