(()=>{
const LQ=s=>document.querySelector(s),LQA=s=>[...document.querySelectorAll(s)],LE=v=>escapeHTML(v??''),LO=()=>location.origin.replace(/\/$/,'');
const publicURL=l=>{const c=l.Code??l.code??'',d=l.Domain??l.domain??'';return d?`https://${d}/${encodeURIComponent(c)}`:`${LO()}/${encodeURIComponent(c)}`};
function linkOverlay(){let layer=LQ('#linkEditorLayer');if(!layer){layer=document.createElement('div');layer.id='linkEditorLayer';layer.className='productModalLayer hidden';layer.innerHTML='<div class="productModal" id="linkEditorModal"></div>';document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target===layer)closeLinkEditor()})}return layer}
window.closeLinkEditor=()=>linkOverlay().classList.add('hidden');
function dtLocal(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.valueOf()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
async function domains(){try{return (await api(`/api/workspaces/${state.workspace}/domains`)).data||[]}catch{return[]}}
function arrayValue(value){if(Array.isArray(value))return value;if(typeof value==='string'){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[]}catch{return[]}}return[]}
const ruleLabels={country:'国家 / 地区',device:'设备类型',language:'浏览器语言',source:'访问来源'};
function routingRow(rule={}){return `<div class="ruleRow"><select class="ruleDimension" aria-label="路由维度"><option value="country" ${rule.dimension==='country'?'selected':''}>国家 / 地区</option><option value="device" ${rule.dimension==='device'?'selected':''}>设备类型</option><option value="language" ${rule.dimension==='language'?'selected':''}>浏览器语言</option><option value="source" ${rule.dimension==='source'?'selected':''}>访问来源</option></select><input class="ruleValue" aria-label="匹配值" value="${LE(rule.value||'')}" placeholder="例如 CN、mobile、zh、example.com"><input class="ruleDestination" type="url" aria-label="规则目标网址" value="${LE(rule.destination||'')}" placeholder="https://example.com/landing"><button type="button" class="danger" data-remove-rule>删除</button></div>`}
function abRow(item={},index=0){return `<div class="abRow" data-variant-id="${LE(item.id||`variant-${index+1}`)}"><input class="abDestination" type="url" aria-label="A/B 目标网址" value="${LE(item.destination||'')}" placeholder="https://example.com/variant-${index+1}"><label class="abWeightLabel"><input class="abWeight" type="number" min="1" max="99" aria-label="A/B 权重" value="${Number(item.weight||0)}">%</label><button type="button" class="danger" data-remove-variant>删除</button></div>`}
function rebalanceVariants(){const rows=LQA('#linkABRows .abRow'),base=Math.floor(100/Math.max(rows.length,1)),remainder=100-base*rows.length;rows.forEach((row,index)=>{const input=row.querySelector('.abWeight');input.value=base+(index<remainder?1:0)})}
function wireAdvanced(){
  LQ('#addRoutingRule').onclick=()=>{LQ('#linkRoutingRows').insertAdjacentHTML('beforeend',routingRow());wireRuleRemovers()};
  LQ('#addABVariant').onclick=()=>{const rows=LQA('#linkABRows .abRow');LQ('#linkABRows').insertAdjacentHTML('beforeend',abRow({},rows.length));wireVariantRemovers();rebalanceVariants()};
  wireRuleRemovers();wireVariantRemovers();
}
function wireRuleRemovers(){LQA('#linkRoutingRows [data-remove-rule]').forEach(button=>button.onclick=()=>button.closest('.ruleRow').remove())}
function wireVariantRemovers(){LQA('#linkABRows [data-remove-variant]').forEach(button=>button.onclick=()=>{button.closest('.abRow').remove();rebalanceVariants()})}
function readRoutingRules(){const rules=[];for(const row of LQA('#linkRoutingRows .ruleRow')){const dimension=row.querySelector('.ruleDimension').value,value=row.querySelector('.ruleValue').value.trim(),destination=row.querySelector('.ruleDestination').value.trim();if(!value&&!destination)continue;if(!value||!destination)throw new Error(`${ruleLabels[dimension]||'路由规则'}需要同时填写匹配值和目标网址`);rules.push({dimension,value,destination})}return rules}
function readABDestinations(){const rows=LQA('#linkABRows .abRow').map((row,index)=>({id:row.dataset.variantId||`variant-${index+1}`,destination:row.querySelector('.abDestination').value.trim(),weight:Number(row.querySelector('.abWeight').value||0)})).filter(item=>item.destination);if(!rows.length)return[];if(rows.length<2)throw new Error('A/B 分流至少需要两个目标网址');const total=rows.reduce((sum,item)=>sum+item.weight,0);if(rows.some(item=>item.weight<1)||total!==100)throw new Error('A/B 分流权重必须为正数且总和为 100%');return rows}
async function openEditor(id=0){
 const layer=linkOverlay(),modal=LQ('#linkEditorModal'),ds=await domains();let item={Code:'',Domain:'',Destination:'',Title:'',RedirectStatus:302,Status:'active',OneTime:false};if(id)item=await api(`/api/workspaces/${state.workspace}/links/${id}`);
 const currentDomain=item.Domain??item.domain??'',routing=arrayValue(item.routing_rules??item.RoutingRules),variants=arrayValue(item.ab_destinations??item.ABDestinations);
 const initialRules=routing.length?routing:[{}],initialVariants=variants.length?variants:[{id:'variant-1',weight:50},{id:'variant-2',weight:50}];
 modal.innerHTML=`<div class="productModalHead"><div><span class="eyebrow">${id?'修改链接':'新建链接'}</span><h2>${id?'编辑短链接':'创建短链接'}</h2><p>${id?'保存后，原短网址保持不变并使用新的跳转设置。':'填写目标网址后即可得到一个可以直接复制和分享的短网址。'}</p></div><button type="button" onclick="closeLinkEditor()">×</button></div><form id="linkEditorForm"><div class="productFormGrid"><label class="full">目标网址<input name="destination" type="url" value="${LE(item.Destination??item.destination??'')}" placeholder="https://example.com/page" required></label><label>链接名称<input name="title" value="${LE(item.Title??item.title??'')}" maxlength="255" placeholder="方便自己识别"></label><label>自定义短码<input name="code" value="${LE(item.Code??item.code??'')}" ${id?'readonly':''} placeholder="留空自动生成"></label><label>短链域名<select name="domain"><option value="">默认域名</option>${ds.filter(x=>(x.status==='active'||x.Status==='active')&&(x.https_status==='active'||x.HTTPSStatus==='active')).map(x=>{const h=x.hostname??x.Hostname;return `<option value="${LE(h)}" ${h===currentDomain?'selected':''}>${LE(h)}</option>`}).join('')}</select></label><label>跳转方式<select name="redirect_status">${[302,301,307,308].map(v=>`<option value="${v}" ${Number(item.RedirectStatus??item.redirect_status??302)===v?'selected':''}>${v} · ${v===301||v===308?'永久':'临时'}跳转</option>`).join('')}</select></label><label>链接状态<select name="status"><option value="active" ${(item.Status??item.status)==='active'?'selected':''}>正常使用</option><option value="paused" ${(item.Status??item.status)==='paused'?'selected':''}>暂停使用</option></select></label><label>有效期<input name="expires_at" type="datetime-local" value="${LE(dtLocal(item.ExpiresAt??item.expires_at))}"></label><label>访问次数上限<input name="max_clicks" type="number" min="1" value="${LE(item.MaxClicks??item.max_clicks??'')}" placeholder="不限制"></label><label>访问密码<input name="password" type="password" minlength="6" placeholder="${id?'留空保持现有密码':'可选，至少 6 位'}"></label><label class="productCheck"><input name="one_time" type="checkbox" ${(item.OneTime??item.one_time)?'checked':''}>仅允许访问一次</label>${id?'<label class="productCheck"><input name="clear_password" type="checkbox">清除现有访问密码</label>':''}</div><details class="linkAdvanced"><summary>智能路由与 A/B 分流</summary><div class="advancedBlock"><div class="advancedHead"><div><h3>智能路由</h3><p>按国家、设备、语言或访问来源将匹配流量送往不同目标。</p></div><button type="button" id="addRoutingRule">添加规则</button></div><div id="linkRoutingRows" class="ruleRows">${initialRules.map(routingRow).join('')}</div></div><div class="advancedBlock"><div class="advancedHead"><div><h3>A/B 分流</h3><p>为未命中智能路由的访问分配多个目标，权重总和必须为 100%。</p></div><button type="button" id="addABVariant">添加目标</button></div><div id="linkABRows" class="abRows">${initialVariants.map(abRow).join('')}</div></div></details><div id="linkEditorError"></div><div class="productModalFoot"><button type="button" onclick="closeLinkEditor()">取消</button><button class="primary productPrimary">${id?'保存修改':'创建短链接'}</button></div></form>`;
 layer.classList.remove('hidden');wireAdvanced();
 LQ('#linkEditorForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const expires=f.expires_at?new Date(f.expires_at).toISOString():null;try{const routing_rules=readRoutingRules(),ab_destinations=readABDestinations();let saved;if(id){const next={...item,Destination:f.destination,Title:f.title,Domain:f.domain,RedirectStatus:Number(f.redirect_status),Status:f.status,OneTime:f.one_time==='on',ClearPassword:f.clear_password==='on',ExpiresAt:expires,MaxClicks:f.max_clicks?Number(f.max_clicks):null,routing_rules,ab_destinations};if(f.password)next.Password=f.password;saved=await api(`/api/workspaces/${state.workspace}/links/${id}`,{method:'PUT',body:JSON.stringify({link:next,reason:'更新短链接设置'})})}else{saved=await api(`/api/workspaces/${state.workspace}/links`,{method:'POST',body:JSON.stringify({destination:f.destination,title:f.title,code:f.code,domain:f.domain,redirect_status:Number(f.redirect_status),one_time:f.one_time==='on',expires_at:expires,max_clicks:f.max_clicks?Number(f.max_clicks):null,password:f.password||'',routing_rules,ab_destinations})})}const url=publicURL(saved);modal.innerHTML=`<div class="productModalHead"><div><span class="eyebrow">${id?'修改完成':'创建完成'}</span><h2>${id?'短链接已更新':'短链接已经可以分享'}</h2><p>${id?'保存的设置已经生效。':'复制下面的完整短网址即可分享。'}</p></div><button type="button" onclick="closeLinkEditor()">×</button></div><div class="createdLinkResult"><div class="createdLinkURL"><small>短网址</small><a href="${LE(url)}" target="_blank" rel="noopener">${LE(url)}</a></div><div class="resourceActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制短网址</button><a class="button" href="${LE(url)}" target="_blank">打开链接</a><button onclick="closeLinkEditor();gojetOpenQR(${Number(saved.ID??saved.id)})">生成二维码</button></div></div><div class="productModalFoot"><button class="primary productPrimary" onclick="closeLinkEditor();GoJetPages.links()">完成</button></div>`;setTimeout(()=>window.GoJetPages.links(),100)}catch(err){LQ('#linkEditorError').innerHTML=`<div class="productError">${LE(err.message)}</div>`}};
}
window.openLinkEditor=openEditor;
window.editProductLink=id=>openEditor(id);

async function render(){
 const c=LQ('.content');c.innerHTML=`<div class="productPageHead"><div><h1>短链接</h1><p>集中查看和管理短网址，可以直接复制、打开、生成二维码或查看访问分析。</p></div><button class="primary productPrimary" onclick="openLinkEditor()">创建短链接</button></div><div id="lhLinks" class="productLoading">正在加载链接…</div>`;
 try{const result=await api(`/api/workspaces/${state.workspace}/links?limit=100&offset=0`),items=result.data||[];state.links=items;LQ('#lhLinks').innerHTML=items.length?`<div class="resourceStack">${items.map(l=>{const url=publicURL(l),id=Number(l.ID??l.id),title=(l.Title??l.title)||'未命名链接',dest=l.Destination??l.destination??'',status=l.Status??l.status??'',code=l.Code??l.code??'';return `<article class="shareCard"><div class="shareCardMain"><div class="resourceIcon">↗</div><div class="resourceCopy"><div class="resourceTitleRow"><h2>${LE(title)}</h2><span class="productStatus status-${LE(status)}">${status==='active'?'正常使用':status==='paused'?'已暂停':LE(status)}</span></div><div class="shareLine"><div><small>短网址</small><a href="${LE(url)}" target="_blank">${LE(url)}</a></div><div class="shareActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制</button><a class="button" href="${LE(url)}" target="_blank">打开</a></div></div><p class="destinationText">${LE(dest)}</p><div class="miniMeta"><span>${Number(l.Clicks??l.clicks??0).toLocaleString()} 次访问</span><span>${Number(l.Visitors??l.visitors??0).toLocaleString()} 位访客</span><span>${date(l.CreatedAt??l.created_at)}</span></div></div></div><div class="resourceActions"><button onclick="gojetCopy('${String(url).replace(/'/g,"\\'")}',this)">复制链接</button><a class="button" href="${LE(url)}" target="_blank">打开链接</a><button onclick="gojetOpenQR(${id})">二维码</button><button onclick="gojetOpenAnalytics(${id})">访问分析</button><button onclick="editProductLink(${id})">编辑</button></div></article>`}).join('')}</div>`:`<div class="productEmpty"><div class="emptyIcon">↗</div><h3>还没有短链接</h3><p>创建第一条短链接后，可以在这里复制、打开和管理。</p><button class="primary" onclick="openLinkEditor()">创建第一条链接</button></div>`}catch(err){LQ('#lhLinks').innerHTML=`<div class="productError">${LE(err.message)}</div>`}
}
window.GoJetPages=window.GoJetPages||{};window.GoJetPages.links=render;
})();
