(()=>{
const H=v=>escapeHTML(v??'');
const statusText={open:'待处理',customer_reply:'等待客服回复',staff_reply:'客服已回复',in_progress:'处理中',resolved:'已解决',closed:'已关闭'};
const priorityText={low:'低',normal:'普通',high:'高',urgent:'紧急'};
let botPolicyPromise=null,turnstileScriptPromise=null;
const turnstileWidgets=new Map();
async function botPolicy(){if(!botPolicyPromise)botPolicyPromise=fetch('/api/public/turnstile').then(r=>r.ok?r.json():{enabled:false}).catch(()=>({enabled:false}));return botPolicyPromise}
function loadTurnstile(){if(window.turnstile)return Promise.resolve();if(turnstileScriptPromise)return turnstileScriptPromise;turnstileScriptPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.defer=true;s.onload=resolve;s.onerror=()=>reject(new Error('人机验证组件加载失败'));document.head.appendChild(s)});return turnstileScriptPromise}
async function ensureTurnstile(surface,action,form){const policy=await botPolicy(),enabled=policy.enabled&&policy.surfaces?.[surface];if(!enabled)return null;if(!policy.site_key)throw new Error('人机验证暂不可用，请稍后重试');await loadTurnstile();let slot=form.querySelector('[data-turnstile-slot]');if(!slot){slot=document.createElement('div');slot.dataset.turnstileSlot='1';slot.style.margin='14px 0';const submit=form.querySelector('button[type="submit"]');form.insertBefore(slot,submit?.parentElement||submit||null)}let id=turnstileWidgets.get(form);if(id===undefined){id=window.turnstile.render(slot,{sitekey:policy.site_key,action,theme:'auto'});turnstileWidgets.set(form,id)}return id}
async function turnstileToken(surface,action,form){const id=await ensureTurnstile(surface,action,form);if(id===null)return'';const token=window.turnstile.getResponse(id);if(!token)throw new Error('请先完成人机验证');return token}
function resetTurnstile(form){const id=turnstileWidgets.get(form);if(id!==undefined&&window.turnstile)window.turnstile.reset(id)}
function ticketStatus(v){return `<span class="state ${H(v)}">${H(statusText[v]||v)}</span>`}
function when(v){const d=new Date(v);return Number.isNaN(d.valueOf())?'—':d.toLocaleString('zh-CN',{hour12:false})}

async function renderTickets(){
 const [tickets,depts]=await Promise.all([api('/api/support/tickets'),api('/api/support/departments')]);
 const content=document.querySelector('.content'),items=tickets.data||[];
 content.innerHTML=`<div class="productPageHead"><div><h1>支持工单</h1><p>查看服务进度或继续回复已有问题。</p></div><button class="primary" id="newTicket">新建工单</button></div>${items.length?`<div class="supportList">${items.map(t=>`<article class="supportRow" data-ticket-id="${t.id}" tabindex="0"><div><b>${H(t.ticket_number)}</b><small>${when(t.created_at)}</small></div><div><div class="supportSubject">${H(t.subject)}</div><small>${H(t.department_name)}</small></div><div>${H(priorityText[t.priority]||t.priority)}<small>优先级</small></div><div>${ticketStatus(t.status)}</div><div>${t.last_reply_by==='customer'?'等待客服':'客服已回复'}<small>最后回复方</small></div><div>${when(t.last_reply_at)}</div></article>`).join('')}</div>`:`<div class="productEmpty"><div class="emptyIcon">?</div><h3>暂无工单</h3><p>需要协助时，可以直接创建一张工单。</p><button class="primary" id="emptyNewTicket">新建工单</button></div>`}`;
 const openNew=()=>renderNewTicket(depts.data||[]);content.querySelector('#newTicket').onclick=openNew;content.querySelector('#emptyNewTicket')?.addEventListener('click',openNew);content.querySelectorAll('[data-ticket-id]').forEach(row=>{const open=()=>renderTicketDetail(Number(row.dataset.ticketId));row.onclick=open;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})
}

function renderNewTicket(departments){
 const content=document.querySelector('.content');
 content.innerHTML=`<div class="productPageHead"><div><h1>新建支持工单</h1><p>选择问题类型并说明需要协助的内容。</p></div><button id="backTickets">返回列表</button></div><form id="ticketCreateForm" class="resourceForm"><div class="grid"><label>支持部门<select name="department_id" required>${departments.map(d=>`<option value="${d.id}">${H(d.name)}</option>`).join('')}</select></label><label>优先级<select name="priority"><option value="normal">普通</option><option value="low">低</option><option value="high">高</option><option value="urgent">紧急</option></select></label></div><label>主题<input name="subject" maxlength="220" required placeholder="例如：自定义域名无法验证"></label><label>问题内容<textarea name="message" rows="10" maxlength="50000" required placeholder="请说明问题现象，以及已经尝试过的操作。"></textarea></label><div id="ticketCreateError" class="error"></div><footer class="supportCreateActions"><button type="button" id="cancelTicket">取消</button><button class="primary" type="submit">提交工单</button></footer></form>`;
 content.querySelector('#backTickets').onclick=renderTickets;content.querySelector('#cancelTicket').onclick=renderTickets;const form=content.querySelector('#ticketCreateForm');ensureTurnstile('ticket_create','support_ticket_create',form).catch(err=>content.querySelector('#ticketCreateError').textContent=err.message);form.onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(form));payload.department_id=Number(payload.department_id);try{payload.turnstile_token=await turnstileToken('ticket_create','support_ticket_create',form);const created=await api('/api/support/tickets',{method:'POST',body:JSON.stringify(payload)});await renderTicketDetail(created.id)}catch(err){content.querySelector('#ticketCreateError').textContent=err.message;resetTurnstile(form)}}
}

async function renderTicketDetail(id){
 const d=await api(`/api/support/tickets/${id}`),t=d.ticket,messages=d.messages||[],content=document.querySelector('.content');
 content.innerHTML=`<div class="productPageHead supportDetailHead"><div><h1>${H(t.ticket_number)} · ${H(t.subject)}</h1><div class="ticketSummary">${ticketStatus(t.status)}<span>${H(t.department_name)}</span><span>${H(priorityText[t.priority]||t.priority)}优先级</span></div></div><div class="supportDetailActions"><button id="backTickets">返回列表</button><button id="toggleTicket" class="${t.status==='closed'?'':'danger'}">${t.status==='closed'?'重新打开':'关闭工单'}</button></div></div><section class="supportTicketPage"><div class="supportConversation" aria-label="工单会话">${messages.map((m,index)=>`<article class="supportMessage ${m.author_type==='administrator'?'staff':'customer'}"><div class="supportTimelineMarker" aria-hidden="true"></div><div class="supportMessageHead"><b>${m.author_type==='administrator'?'GoJet 支持团队':H(m.author_name||'我')}</b><small>${when(m.created_at)}</small></div><div class="supportMessageBody">${H(m.body)}</div>${m.author_type==='customer'&&m.ip_address?`<div class="ticketMessageMeta"><span>${index===0?'工单 IP':'回复 IP'}</span><code>${H(m.ip_address)}</code></div>`:''}</article>`).join('')||'<div class="empty">暂无回复</div>'}</div>${t.status==='closed'?'<div class="supportClosedNotice">该工单已关闭。如需继续沟通，请先重新打开工单。</div>':`<form id="ticketReplyForm" class="supportReply"><div class="supportReplyHead"><b>回复工单</b><small>回复会直接追加到上方会话中。</small></div><textarea name="message" rows="7" maxlength="50000" required placeholder="输入回复内容"></textarea><div id="ticketReplyError" class="error"></div><footer class="supportActions"><button class="primary" type="submit">发送回复</button></footer></form>`}</section>`;
 content.querySelector('#backTickets').onclick=renderTickets;content.querySelector('#toggleTicket').onclick=async()=>{await api(`/api/support/tickets/${id}/state`,{method:'PATCH',body:JSON.stringify({action:t.status==='closed'?'reopen':'close'})});await renderTicketDetail(id)};const form=content.querySelector('#ticketReplyForm');if(form){ensureTurnstile('ticket_reply','support_ticket_reply',form).catch(err=>content.querySelector('#ticketReplyError').textContent=err.message);form.onsubmit=async e=>{e.preventDefault();try{const payload={message:new FormData(form).get('message'),turnstile_token:await turnstileToken('ticket_reply','support_ticket_reply',form)};await api(`/api/support/tickets/${id}/replies`,{method:'POST',body:JSON.stringify(payload)});await renderTicketDetail(id)}catch(err){content.querySelector('#ticketReplyError').textContent=err.message;resetTurnstile(form)}}}
}
window.GoJetSupport={renderTickets};window.GoJetPages=window.GoJetPages||{};window.GoJetPages.tickets=renderTickets;
})();