<x-layouts.app :title="$textShare->title ?: __('v3.texts.title')">
  <section class="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><a class="text-sm font-semibold text-slate-500" href="{{ route('texts.index') }}">← {{ __('v3.texts.title') }}</a><h1 class="page-title mt-4">{{ $textShare->title ?: $textShare->slug }}</h1><a class="mt-2 block text-sm font-semibold text-cyan-700" href="{{ route('texts.public',$textShare->slug) }}" target="_blank">{{ route('texts.public',$textShare->slug) }} ↗</a></div><div class="flex gap-2"><a class="btn-secondary" href="{{ route('texts.raw',$textShare->slug) }}" target="_blank">{{ __('v3.texts.raw') }}</a><a class="btn-secondary" href="{{ route('texts.download',$textShare->slug) }}">{{ __('v3.common.download') }}</a></div></div>
    <div class="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
      <form class="panel space-y-5" method="post" action="{{ route('texts.update',$textShare) }}">@csrf @method('patch')
        <div><label class="label">{{ __('v3.links.title_field') }}</label><input class="input" name="title" value="{{ $textShare->title }}"></div>
        <div><label class="label">{{ __('v3.texts.content') }}</label><textarea class="input min-h-[520px] font-mono text-sm" name="content" required>{{ $textShare->content }}</textarea></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="label">{{ __('v3.texts.format') }}</label><select class="input" name="format">@foreach(['plain','markdown','code'] as $format)<option value="{{ $format }}" @selected($textShare->format===$format)>{{ $format }}</option>@endforeach</select></div><div><label class="label">{{ __('v3.texts.syntax') }}</label><input class="input" name="syntax_language" value="{{ $textShare->syntax_language }}"></div><div><label class="label">{{ __('v3.texts.visibility') }}</label><select class="input" name="visibility">@foreach(['public','unlisted','private'] as $visibility)<option value="{{ $visibility }}" @selected($textShare->visibility===$visibility)>{{ __('v3.texts.'.$visibility) }}</option>@endforeach</select></div></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="label">{{ __('v3.texts.password') }}</label><input class="input" type="password" name="password" autocomplete="new-password"></div><div><label class="label">{{ __('v3.texts.expires_at') }}</label><input class="input" type="datetime-local" name="expires_at" value="{{ $textShare->expires_at?->format('Y-m-d\TH:i') }}"></div><div><label class="label">{{ __('v3.texts.max_views') }}</label><input class="input" type="number" name="max_views" min="1" value="{{ $textShare->max_views }}"></div></div>
        <div class="flex flex-wrap gap-4"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="burn_after_read" value="1" @checked($textShare->burn_after_read)>{{ __('v3.texts.burn') }}</label>@if($textShare->password_hash)<label class="flex items-center gap-2 text-sm text-rose-700"><input type="checkbox" name="remove_password" value="1">{{ __('ui.link.remove_password') }}</label>@endif</div>
        <button class="btn-brand w-full py-3">{{ __('v3.common.save') }}</button>
      </form>
      <aside class="space-y-5">
        <div class="panel"><h2 class="font-bold text-slate-950">{{ __('v3.texts.revisions') }}</h2><div class="mt-4 space-y-3">@forelse($textShare->revisions as $revision)<div class="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div class="flex justify-between gap-3 text-xs text-slate-500"><span>#{{ $revision->id }}</span><span>{{ $revision->created_at?->diffForHumans() }}</span></div><p class="mt-2 line-clamp-4 whitespace-pre-wrap text-xs leading-5 text-slate-600">{{ Str::limit($revision->content,240) }}</p></div>@empty<p class="text-sm text-slate-400">{{ __('v3.common.none') }}</p>@endforelse</div></div>
        <div class="panel"><h2 class="font-bold text-slate-950">{{ __('v3.common.status') }}</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">{{ __('v3.texts.views',['count'=>'']) }}</dt><dd class="font-bold">{{ number_format($textShare->views_count) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">{{ __('v3.texts.visibility') }}</dt><dd>{{ __('v3.texts.'.$textShare->visibility) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">{{ __('v3.common.created_at') }}</dt><dd>{{ $textShare->created_at->format('Y-m-d') }}</dd></div></dl></div>
      </aside>
    </div>
  </section>
</x-layouts.app>
