<?php
declare(strict_types=1);
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
$root = dirname(__DIR__);
$state = $root . '/deploy/native';
$expected = @file_get_contents($state . '/.installer-token') ?: '';
$token = (string)($_GET['token'] ?? $_POST['token'] ?? '');
if ($expected === '' || !hash_equals($expected, $token)) { http_response_code(403); exit('安装会话无效或已过期'); }
function h(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }
function envq(string $v): string { return '"' . str_replace(['\\','"','$','`'], ['\\\\','\\"','\\$','\\`'], $v) . '"'; }
$errors=[]; $done=false;
$defaults=['mysql_host'=>'127.0.0.1','mysql_port'=>'3306','mysql_database'=>'gojet','mysql_user'=>'gojet','mysql_admin_user'=>'root','redis_address'=>'127.0.0.1:6379','public_url'=>'https://go.example.com','admin_email'=>'admin@example.com','alert_email'=>'ops@example.com'];
$v=array_merge($defaults, array_map('strval', $_POST));
if ($_SERVER['REQUEST_METHOD']==='POST') {
 if (!preg_match('/^[A-Za-z0-9_]+$/',$v['mysql_database']) || !preg_match('/^[A-Za-z0-9_]+$/',$v['mysql_user'])) $errors[]='数据库名和用户名只能使用字母、数字和下划线';
 if (!filter_var($v['public_url'],FILTER_VALIDATE_URL) || !str_starts_with($v['public_url'],'https://')) $errors[]='正式网址必须是有效的 https:// 地址';
 if (!filter_var($v['admin_email'],FILTER_VALIDATE_EMAIL)) $errors[]='管理员邮箱格式不正确';
 foreach (['mysql_password','mysql_admin_password','redis_password','admin_password','visitor_key','qr_key','log_token'] as $key) if (strlen($v[$key] ?? '') < 16) $errors[]="$key 至少需要 16 个字符";
 if (($v['mysql_password'] ?? '') !== ($v['mysql_password_confirm'] ?? '')) $errors[]='MySQL 用户密码两次输入不一致';
 if (($v['admin_password'] ?? '') !== ($v['admin_password_confirm'] ?? '')) $errors[]='管理员密码两次输入不一致';
 if (!$errors) {
  try { $pdo=new PDO("mysql:host={$v['mysql_host']};port={$v['mysql_port']};charset=utf8mb4",$v['mysql_admin_user'],$v['mysql_admin_password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $version=(string)$pdo->query('SELECT VERSION()')->fetchColumn(); if (!str_starts_with($version,'8.0.')) $errors[]="需要 MySQL 8.0，当前为 $version"; } catch(Throwable $e) { $errors[]='无法连接 MySQL：'.$e->getMessage(); }
  [$rh,$rp]=array_pad(explode(':',$v['redis_address'],2),2,'6379'); $sock=@stream_socket_client("tcp://$rh:$rp",$eno,$estr,2); if (!$sock) $errors[]="无法连接 Redis：$estr"; else { fwrite($sock,"*2\r\n$4\r\nAUTH\r\n$".strlen($v['redis_password'])."\r\n{$v['redis_password']}\r\n"); $reply=fgets($sock); if (!str_starts_with((string)$reply,'+OK') && !str_contains((string)$reply,'no password')) $errors[]='Redis 密码验证失败'; fclose($sock); }
 }
 if (!$errors) {
  $settings=base64_encode(random_bytes(32));
  $dsn=$v['mysql_user'].':'.$v['mysql_password'].'@tcp('.$v['mysql_host'].':'.$v['mysql_port'].')/'.$v['mysql_database'].'?parseTime=true&charset=utf8mb4';
  $env=[
   'MYSQL_HOST'=>$v['mysql_host'],'MYSQL_PORT'=>$v['mysql_port'],'MYSQL_DATABASE'=>$v['mysql_database'],'MYSQL_USER'=>$v['mysql_user'],'MYSQL_PASSWORD'=>$v['mysql_password'],'MYSQL_ADMIN_USER'=>$v['mysql_admin_user'],'MYSQL_ADMIN_PASSWORD'=>$v['mysql_admin_password'],'MYSQL_DSN'=>$dsn,
   'REDIS_ADDRESS'=>$v['redis_address'],'REDIS_PASSWORD'=>$v['redis_password'],'SETTINGS_ENCRYPTION_KEY'=>$settings,'ADMIN_BOOTSTRAP_EMAIL'=>$v['admin_email'],'ADMIN_BOOTSTRAP_PASSWORD'=>$v['admin_password'],'PUBLIC_BASE_URL'=>rtrim($v['public_url'],'/'),'VISITOR_HASH_KEY'=>$v['visitor_key'],'QR_TRACKING_KEY'=>$v['qr_key'],'LOG_INGEST_TOKEN'=>$v['log_token'],'LOG_WEBHOOK_TOKEN'=>$v['log_token'],'LOG_WEBHOOK_URL'=>'http://127.0.0.1:18092/v1/logs','PLATFORM_HTTP_ADDRESS'=>'127.0.0.1:18090','HTTP_ADDRESS'=>'127.0.0.1:18080','LOG_RECEIVER_HTTP_ADDRESS'=>'127.0.0.1:18092','UPLOAD_STORAGE_PATH'=>$root.'/deploy/data/uploads','FILE_STORAGE_PATH'=>$root.'/deploy/data/files','FILE_STORAGE_DRIVER'=>'filesystem','CLAMAV_ADDRESS'=>'127.0.0.1:3310','ANALYTICS_GROUP'=>'gojet-mysql','ANALYTICS_CONSUMER'=>'native-worker-1','ANALYTICS_BATCH_SIZE'=>'100','ANALYTICS_RECONCILE_BATCH'=>'500','ANALYTICS_RECONCILE_INTERVAL_SECONDS'=>'60','OPERATIONS_MONITOR_INTERVAL_SECONDS'=>'60','ALERT_RECIPIENT'=>$v['alert_email']];
  $body="# Generated by the GoJet guided installer.\n"; foreach($env as $k=>$val) $body.=$k.'='.envq((string)$val)."\n";
  if (file_put_contents($state.'/gojet.env',$body,LOCK_EX)===false) $errors[]='无法写入生产配置'; else { chmod($state.'/gojet.env',0600); file_put_contents($state.'/.install-request',$token,LOCK_EX); $done=true; }
 }
}
$checks=['PHP 8.3+'=>version_compare(PHP_VERSION,'8.3.0','>='),'PDO MySQL'=>extension_loaded('pdo_mysql'),'OpenSSL'=>extension_loaded('openssl'),'64 位系统'=>PHP_INT_SIZE===8];
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoJet 安装向导</title><style>
:root{font-family:Inter,"Noto Sans SC",system-ui;background:#07111f;color:#e8f0ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#17365d 0,transparent 35%),#07111f}.wrap{max-width:900px;margin:48px auto;padding:0 20px}.brand{font-size:28px;font-weight:800}.brand b{color:#43d6a7}.card{background:#0d1b2d;border:1px solid #203651;border-radius:18px;padding:28px;margin-top:22px;box-shadow:0 22px 70px #0008}h1{font-size:30px;margin:0 0 8px}p{color:#9db0c9;line-height:1.7}.checks,.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.check{padding:12px;border-radius:10px;background:#11243a}.ok{color:#43d6a7}.bad,.errors{color:#ff8b8b}.errors{background:#351923;padding:15px;border-radius:10px}label{display:block;color:#b8c8dc;font-size:13px;margin-top:12px}input{width:100%;margin-top:6px;padding:12px;border:1px solid #29425f;border-radius:9px;background:#081522;color:white}button{margin-top:22px;padding:14px 24px;border:0;border-radius:10px;background:#43d6a7;color:#052017;font-weight:800;cursor:pointer}.done{text-align:center;padding:50px 10px}@media(max-width:700px){.grid,.checks{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><div class="brand">Go<b>Jet</b></div><section class="card">
<?php if($done): ?><div class="done"><h1>配置已提交，正在自动安装</h1><p>请不要刷新页面。后台启动器正在迁移数据库、注册 systemd 服务并配置 Nginx。完成后临时安装页面将自动关闭。</p></div>
<?php else: ?><h1>生产环境安装向导</h1><p>适用于 Debian 12 / 宝塔面板 / Nginx 1.28.1 / PHP 8.3.31 / MySQL 8.0。填写一次即可，无需手工编辑环境文件。</p><div class="checks"><?php foreach($checks as $name=>$ok): ?><div class="check"><span class="<?= $ok?'ok':'bad' ?>"><?= $ok?'✓':'✕' ?></span> <?=h($name)?></div><?php endforeach ?></div>
<?php if($errors): ?><ul class="errors"><?php foreach($errors as $e): ?><li><?=h($e)?></li><?php endforeach ?></ul><?php endif ?>
<form method="post"><input type="hidden" name="token" value="<?=h($token)?>"><h2>MySQL 8.0</h2><div class="grid">
<?php foreach(['mysql_host'=>'主机','mysql_port'=>'端口','mysql_database'=>'数据库名','mysql_user'=>'GoJet 用户','mysql_admin_user'=>'管理员用户'] as $k=>$label): ?><label><?=$label?><input required name="<?=$k?>" value="<?=h($v[$k])?>"></label><?php endforeach ?>
<label>MySQL 管理员密码<input required type="password" name="mysql_admin_password"></label><label>GoJet 数据库密码<input required type="password" name="mysql_password"></label><label>再次输入数据库密码<input required type="password" name="mysql_password_confirm"></label></div>
<h2>站点与 Redis</h2><div class="grid"><label>正式 HTTPS 网址<input required name="public_url" value="<?=h($v['public_url'])?>"></label><label>Redis 地址<input required name="redis_address" value="<?=h($v['redis_address'])?>"></label><label>Redis 密码<input required type="password" name="redis_password"></label><label>告警邮箱<input required type="email" name="alert_email" value="<?=h($v['alert_email'])?>"></label></div>
<h2>管理员与安全密钥</h2><div class="grid"><label>管理员邮箱<input required type="email" name="admin_email" value="<?=h($v['admin_email'])?>"></label><label>管理员初始密码<input required type="password" name="admin_password"></label><label>再次输入管理员密码<input required type="password" name="admin_password_confirm"></label><label>访客哈希密钥<input required minlength="32" name="visitor_key"></label><label>QR 跟踪密钥<input required minlength="32" name="qr_key"></label><label>日志接收密钥<input required minlength="32" name="log_token"></label></div><button type="submit">验证配置并开始安装</button></form><?php endif ?>
</section></main></body></html>
